### PR TITLE
lua module ds18b20: fixed missing forward declaration

### PR DESCRIPTION
**Pull request by glumanda**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [- ] This PR is for the `dev` branch rather than for `master`.
- [x ] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x ] The code changes are reflected in the documentation at `docs/*`.

\<Description of and rationale behind this PR\>
bugfixing

### CODE REVIEW

**Comment by TerryE** [comment]
Hi @glumanda Andreas, 
```Lua
local function conversion(self)
```
is just syntactic sugar for 
```Lua
local  conversion;  conversion = function(self)
```
(This is _not_ the same as `local  conversion = function(self)` as the former makes the local `conversion` available and the latter is evaluated right to left and will use whatever was in scope before the `local  conversion` declaration.)

Since the preceding `readout()` makes to reference to `conversion`, moving the local declaration above this has _zero_ effect.  So sorry, there is no point in making this null change.  Also on  a procedural note changes go into `dev` first.

**Comment by HHHartmann** [comment]
@TerryE Terry, I don't understand your comment.

> Since the preceding readout() makes **to** reference to conversion, moving the local declaration above this has zero effect. ...

Did you mean **no** reference?

In this case your assumption is incorrect as `readout()` does reference `conversion` in line 108.

@glumanda The PR would still have to be prepared against dev.

**Comment by TerryE** [comment]
Gregor, you are right: I did look through the source but missed this reference :scream: so my _zero effect_ conclusion was wrong.

**Comment by vsky279** [comment]
Hi, I don't get what is the implication of this missing forward declaration.
I thought the module worked fine. Or not?

**Comment by TerryE** [comment]
Lukáš, do a `luac.cross -l -l` to get a Lua VM code listing for the functions in the module.  The parser has to compile the function `function() return conversion(self) end` within `readout()`.  If `conversion` isn't local which it isn't here then it

-  creates an upval reference (in both this anon function and in `readout()` _if_ there is a `local conversion` in one or more of its parents, or
-  it generates a global reference.

Referencing only resolves backwards so this changes the generated code and the runtime behaviour.

**Comment by vsky279** [comment]
Got it. Thanks Terry.

**Pull request closed without merging**
