### PR TITLE
DHT temperature sensor module

### PR DESCRIPTION
**Pull request by patrickhwood**
Internal module for DHT11/22 temperature sensor.  Adds less to ROM size than compiled .lua drivers.  Module returns temp/hum x 10 for DHT22, temp/hum for DHT11 (note: DHT11 untested as I don't have this device); Lua test script assumes float support.

### CODE REVIEW

**Comment by vowstar** [comment]
Hello, we already have dhtlib and support all kinds of dht-sensor, including dht11, 21, 22, 33, 44 and after testing.
https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_en#dhtread,
Thank you for support NodeMCU opensource project.
Please try our latest release.
https://github.com/nodemcu/nodemcu-firmware/releases
```lua
pin = 5
status,temp,humi,temp_decimial,humi_decimial = dht.read(pin)
if( status == dht.OK ) then
  -- Integer firmware using this example
  print(     
    string.format(
      "DHT Temperature:%d.%03d;Humidity:%d.%03d\r\n",
      math.floor(temp),
      temp_decimial,
      math.floor(humi),
      humi_decimial
    )
  )
  -- Float firmware using this example
  print("DHT Temperature:"..temp..";".."Humidity:"..humi)
elseif( status == dht.ERROR_CHECKSUM ) then
  print( "DHT Checksum error." );
elseif( status == dht.ERROR_TIMEOUT ) then
  print( "DHT Time out." );
end
```

**Comment by patrickhwood** [comment]
Oops.  I forked your repo a couple of days before you merged this into master.  Guess I should have checked the dev branch first!

Thanks a lot for all your work on nodemcu.  If you have any other items on your to-do list that I can help with, let me know.

Pat Wood

**Comment by vowstar** [comment]
Thank you very much and we want nodemcu support many devices. 
Our TODO list:
1. Fix documents
2. Support SDK v1.1.2
3. Mesh network
4. NTP and mDNS
5. OTA
6. More devices ...

**Comment by patrickhwood** [comment]
NTP is definitely possible.  
    
    I did a port of a Java mDNS library to Android a few years ago. 
    mDNS is pretty big; the linux executables (built from the Apple C
    code base) run from 225K (armhf) to 280K (x86), dynamically linked. 
    I assume you want to use it for device discovery, which means you
    can't subset out just the device registration code -- each device
    has to perform discovery so it can handle name conflicts (e.g., if I
    have 2 devices that want to use the name "esp8266", the first gets
    this name and the second sees a device already registered and tries
    to get "esp8266-1", "esp8266-2", etc., until it finds an available
    name).  This means keeping around the names of all the registered
    devices (using up valuable RAM).
    
    For basic device discovery, I did this:
    
    usrv=net.createServer(net.UDP)
    usrv:on("receive",function(conn,payload)
      local i,_ = payload:find('esp8266find')
      if (i) then
        local ipaddr,_,_ = wifi.sta.getip()
        for j = 1,3 do
          tmr.delay(math.random()*20000)
          conn:send('esp8266reply:' .. ipaddr .. ':' .. chipid .. ':' ..
    payload)
        end
      end
      end)
    usrv:listen(6310)
    
    It responds to any UDP broadcast that contains the string
    "esp8266find".  The 3 replies at random intervals is based on what
    mDNS does.
    
    Pat
    
    On 6/26/2015 11:37 PM, Vowstar wrote:
    
    
      Thank you very much and we want nodemcu support many devices. 
        Our TODO list:
        1. Fix documents
        2. Support SDK v1.1.2
        3. Mesh network
        4. NTP and mDNS
        5. OTA
        6. More devices ...
      —
        Reply to this email directly or view
          it on GitHub.

**Pull request closed without merging**
