### PR TITLE
Add go-mcu to the list of upload tools

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
- [x] This PR is for the `dev` branch rather than for the `release` branch.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

Not sure if a GH issue is required for such a small change.

This PR adds a reference to [`go-mcu`](https://github.com/matiasinsaurralde/go-mcu), a tool that works as an upload tool but also as a standalone Go package that people may use to interact with their NodeMCU-enabled chips.

### CODE REVIEW

**Comment by nwf** [comment]
LGTM

**Review by nwf — APPROVED** [review]

**Comment by matiasinsaurralde** [comment]
@nwf Thanks!

**Review by HHHartmann — CHANGES_REQUESTED** [review]
Sorry but I disagree with the approval. 
This page lists a selection of projects which seem to be popular, which does not apply to this one (yet).
Maybe the folks at https://frightanic.com/iot/tools-ides-nodemcu/ will list your project.

**Comment by marcelstoer** [comment]
I'm with Gregor here.

@matiasinsaurralde thanks for the heads up!

**Pull request closed without merging**
