### PR TITLE
adjustments for esptool.py.

### PR DESCRIPTION
**Pull request by kmpm**
Can now do make && make flash directly from root.
Also removed unnecessary stuff from app/Makefile.

It might need some adjustments for windows though.

### CODE REVIEW

**Comment by nodemcu** [comment]
thanks, currently make and make flash is needed within app/ for eclipse toolchain.
because the project root in eclipse is /app.
and for now, a \\ can not pass to esptool.py as a para.

**Comment by kmpm** [comment]
ok
* make and make app works within app even with this change, as well as from repository root. I can not test with eclipse and or windows at the moment though.
* So you are saying that esptool.py needs backslash on windows but we can't pass it because of something? Is there something I can do about it?

**Comment by vowstar** [comment]
Could we use eclipse project file in SDK root folder?

**Comment by nodemcu** [comment]
@kmpm 
my mistake. a linux-style(./../../)  path can not pass to esptool.py as a para on windows.

**Pull request merged**
