### PR TITLE
Change a number of default values

### LINKED ISSUE #872: Changing the default user settings.
At the moment the "default" `dev` compile doesn't load on the vast majority of ESP modules out there (the 512Kb parts).  My recommendation is that we change the default in user_config.h and user_modules.h so that if  a developer downloads the repo dev branch or zip and does a make then the binary is usable on a 512Kb part.  

Anyone who needs to add anything that needs an additional module can uncomment the relevant line and do the make again.  My suggestion for defaults are:
```
bit_rate               = 115200
client_ssl             = disable
gpio_interrupt         = enable
spiffs_cache           = enable
optimize_debug         = 2
led_high_count_default = 10
led_low_count_default  = 0

builtin = string,table,coroutine,math,debug_minimal
modules = node,file,gpio,wifi,net,i2c,spi,tmr,adc,uart,ow,bit
```
This summary is in my `cnf` format for the sake of brevity,  but the change would be in terms of `//` edits of the `user_*.h` files of course.

### PR DESCRIPTION
**Pull request by marcelstoer**
fixes #872

### CODE REVIEW

**Comment by TerryE** [comment]
Marcel, I have been thinking about this. The questions we should be asking ourselves are: why do w have a default setting and what should be in it?

I feel that the answer to the first is that it is a build configuration that enables a beginner to make a basic firmware build that fits in a 512 KB module, with a useful minimal SPIFFS (say 64 KB) and is sufficiently functional to allow initial familiarisation with bread-boarded modules or a Devkit. 

On reflection, SPI isn't that common and needs more than the pins available on the ESP-01. I am not sure that i would include it.

**Comment by dnc40085** [comment]
I give this a :+1: because I develop on a 512k esp, for the faster upload, and it gets a bit irritating having to change `user_config.h` and `user_modules.h` every time I do a reset on my local branch.

It would also be nice to update `.cproject` for eclipse to have the paths and symbols set for the include directories.

Just for fun I figured I'd check to see how much free space is available with the new defaults:
* With the new defaults, `file.fsinfo` reports 83081 bytes.
* With the new defaults - DHT + [PR 1018](https://github.com/nodemcu/nodemcu-firmware/pull/1018), `file.fsinfo` reports 83081 bytes.
* With the new defaults + PR 1018 (with wifi station status monitor and wifi disconnect reasons are disabled), `file.fsinfo` reports 83081 bytes.

**Comment by marcelstoer** [comment]
It's fine for me to target 512 KB modules like ESP-01. However, I believe beginners nowadays go for USB-ready modules such as NodeMCU devkits or WeMos D1 mini. It's all just guess work and we'll never know for sure, so we might as well roll the dice.

Since we don't provide up-to-date downloadable binaries anymore we seem to pretty much agree that whatever the modules included by default are that set has close to zero impact. It would just be nice to have a good enough guideline and explanation why a certain module is enabled/disabled by default.

Arnim says
> i2c, spi, ow, adc, and gpio are general purpose interface modules

You say
> SPI isn't that common and needs more than the pins available on the ESP-01

And I agree with both of you. So, how about

"The default configuration targets 512 KB modules like ESP-01 and includes general purpose interface modules which require at most two GPIO pins"

**Comment by marcelstoer** [comment]
@dnc40085 don't you think reporting `node.heap` rather than `file.fsinfo` would provide more meaningful information?

**Comment by marcelstoer** [comment]
> It would also be nice to update `.cproject` for eclipse to have the paths and symbols set for the include directories.

That's IMO OT for this PR but I've actually wanted to get rid of `.settings/`, `.cproject`, and `.project` for quite some time. To my knowledge none of the current committers uses Eclipse for this project so those artifacts obviously are unmaintained.

**Comment by dnc40085** [comment]
>@dnc40085 thanks for testing but don't you think reporting node.heap rather than file.fsinfo would provide more meaningful information?

I was thinking more about the limited space aspect for the 512K ESPs. 

Here's the heap outputs:
* With the new defaults, `node.heap` = 45424 bytes.
* With the new defaults - DHT, `node.heap` = 45448 bytes. `file.fsinfo` = 83081
* With the new defaults - DHT + [PR 1018](https://github.com/nodemcu/nodemcu-firmware/pull/1018), `node.heap` = 45344 bytes.
* With the new defaults + PR 1018 (with wifi station status monitor and wifi disconnect reasons are disabled), `node.heap` = 45376 bytes.

>That's IMO OT for this PR

I just didn't think it was a big enough deal to open a separate issue for it, my apologies.

**Comment by TerryE** [comment]
Marcel suggestion for a slight tweak to your working.  (The _italics_ is only to markup the changes.)

> The default configuration is _designed to run on all ESP modules including_ the 512 KB modules like ESP-01 and _only_ includes general purpose interface modules which require at most two GPIO pins

**Comment by marcelstoer** [comment]
Thanks Terry for the tweak, makes sense. As seem to finally be approaching a common understanding where do we persists that? It's nice we got it here on GitHub but I wouldn't want to send people to #1127 if they ask about our defaults. Can I add the statement to `user_modules.h` as a comment just above the module definition? How about adding it also as a new paragraph to http://nodemcu.readthedocs.org/en/dev/en/build/?

**Comment by jmattsson** [comment]
I'm sure Terry will be pleased to hear it, but the more I'm building NodeMCU, the less I'm liking user_modules.h. The ability to do e.g. `make MODULES="file gpio sntp"` or `make MODULES="@common.cfg @extra.cfg adc ow"` with no "default" config per se, though perhaps providing the common.cfg in the aforementioned example would be nice. The key aspect would be that there would be no header file listing the modules, nor one generated - any #defines needed would go on the command line. Keep the module list away from the code.

In the meantime, this PR seems a reasonable step. The cloud builder stats are our best source of guidance I believe.

**Comment by pjsg** [comment]
At some point, one of my PRs got committed which accidentally included the feature that I use to configure local builds. 

If you have a user_config.h file in the root of the firmware, then it will be included everywhere. It can only add extra modules (and predefine other things). Since it isn't part of the repo, it persists across branch changes etc. It doesn't have to exist, and, if it doesn't exist, then everything is backwards compatible. It is driven with a little bit of makefile magic.

**Comment by pjsg** [comment]
There doesn't appear to be much we can do about the heap size. The vast majority of the rest of the ram is consumed by the espressif code (and lwip). It will make a difference which modules we include only to the extent that bits of the sdk get included or not.

**Comment by TerryE** [comment]
I think that there are two separate issues: is this PR a sensible step forward; should we move to a config approach. I would keep these separate. But I :+1: on both.

**Comment by marcelstoer** [comment]
Terry, Philip, Johny do you have a preference as for where to document our default settings (https://github.com/nodemcu/nodemcu-firmware/pull/1127#issuecomment-193289044)?

**Comment by jmattsson** [comment]
A note on the "why" in user_modules.h together with a "new modules should be disabled by default", plus a more friendly note plus pointer to cloud-builder in the docs proper?

**Comment by marcelstoer** [comment]
All done, hope this is finally ready for merging.

**Pull request merged**
