### PR TITLE
Major upgrade to SDK 1.4.0 & open LWIP

### PR DESCRIPTION
**Pull request by jmattsson**
This pull request brings NodeMCU up to speed with the latest SDK. I've been working on this with input from both @TerryE and @marcelstoer (thanks guys!), and I believe it is now at a point where it's ready for a bit wider exposure. Here at DiUS we have successfully switched our main project over to this and there are currently no known issues. However, we only use a subset of the entire NodeMCU functionality, so more testing is both welcome and needed.

If there are no major issues encountered I intend to merge this next week.

Overview of changes:
- Upgraded to SDK 1.4.0.
- SDK split out "on the side" to make it easier to upgrade going forward. It is now very obvious which parts are SDK and which are not, so they can be left alone.
- Added ability to override SDK includes to effectively patch the SDK as needed without making changes to the SDK files themselves.
- The IP stack "LWIP" has been upgraded to the latest open-LWIP provided by Espressif. This took a bit of back-and-forth with Espressif to make work, but they've been very responsive and helpful.
- Lua input handling has been switched from polled to event driven in anticipation of being able to use the new sleep features eventually.
- The WiFi SmartConfig API had changed, so that module got some updates but haven't seen any actual testing yet. If someone has a setup to test this, please do!

### CODE REVIEW

**Comment by eku** [comment]
:thumbsup:

**Comment by pastukhov** [comment]
Integral build, no float point math?

**Comment by TerryE** [comment]
> Integral build, no float point math?

I am using an F/P version.

**Comment by 3dot3** [comment]
Wow, reborn. Thumbs up.

**Comment by TerryE** [comment]
I've just done a floating point build for my ESP-01 with:

*    **built-ins**: string, table, coroutine, math		
*    **modules**: node, file, gpio, wifi, net, i2c, tmr, adc, uart, ow, bit, rc, rtcmem, rtctime, rtcfifo, sntp

`file.fsinfo()` reports **22,841** free and `node.heap()` after reboot is `43,248`.  So Flash is tight on 512Kb modules but you should have comfortable space on large SRAM modules.  The **objdump** sumary is:
```
Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .irom0.text   00062a0b  40210000  40210000  00007f30  2**4 CONTENTS, ALLOC, LOAD, CODE
  1 .data         00000900  3ffe8000  3ffe8000  000000e0  2**4 CONTENTS, ALLOC, LOAD, DATA
  2 .rodata       00000008  3ffe8900  3ffe8900  000009e0  2**2 CONTENTS, ALLOC, LOAD, DATA
  3 .bss          000075c0  3ffe8908  3ffe8908  000009e8  2**4 ALLOC
  4 .text         0000753b  40100000  40100000  000009e8  2**2 CONTENTS, ALLOC, LOAD, READONLY, CODE
 ```

**Comment by marcelstoer** [comment]
>  it is now at a point where it's ready for a bit wider exposure

I only tested the CI build on Travis so far. I built with different module and config combinations and they all passed. You seem to have also fixed #432 along the way (incidentally?).

> And despite Johny's thanks most of the work has been done by him. Fair acknowledgement where it is due.

I can only speak for myself but I definitely agree. I haven't done anything but observe in awe how you guys pulled this off. Thanks Johny and Terry!

Sidenote: I suggest you remove the dev096 and dev120 branches once this is merged into dev.

**Comment by TerryE** [comment]
Johny, I've added a `-Wl,--cref` option to the `LINKFLAGS_eagle.app.v6` target in the makefile, so I can analyse the mapfile for duplicate functions..  As far as I can see, your build has picked up all the str\* and mem\* duplicates that I removed in my dev130 version, but I'll go through this more rigorously in the next few days.  One request: could we roll into this  the `luac.cross` and `node.stripdebug()` patches in `master`?  See this [wiki page](http://www.esp8266.com/wiki/doku.php?id=nodemcu-lcd) which documents these.

**Comment by jmattsson** [comment]
@TerryE Yes I was forced to free up some iram0 space to even fit in the NodeMCU stuff, so I started with evicting the libc versions of strxxx/memxxx and using the in-ROM versions thereof instead. As a side effect, by doing this via the linker it a) saved me from having to chase down #defines or incorrect usage in the source, and b) took care of any instances referenced by the SDK (I can't remember if there were any, though). In short, there should be no duplicates any more. If you find any, add whatever I missed to ld/defsym.rom please :)

Also @TerryE, we should absolutely keep your eLua memory optimisations! I had intended to go through master and see what's hiding there that hadn't made it onto dev, once this was merged. If you guys prefer I can cherry-pick things across before I merge, just give me a list of commits to pick!

@marcelstoer I was wondering about that when I was working in that file but decided I didn't know enough about all the targets to change it, so I kept what was already there and just added the EXTRA_CCFLAGS to it.

**Comment by TerryE** [comment]
@jmattsson The P/Rs for luac,cross are d0f32b36de83512bab073c1aa5842711f3bc6a31 and f687223fe7bba2d29585124e19f09fede70f1215.  I never raised the P/R for stripdebug, and a couple of minor fixes to the luac.cross.  Let me pull these all together and I'll issue a P/R for you.

**Comment by TerryE** [comment]
I've just gone through the mapfile and especially the Cross Reference section.  You've done a great job of removing duplicated code.  I used the following sed command to script out the garbage so you can focus on the detail (needs localisation):
```bash
sed -e 's!/home/terry/esp-open-sdk/xtensa-lx106-elf!ELF!g' \
    -e 's!/lib/gcc/xtensa-lx106-elf/4.8.2/../../../..!!g' \
    -e 's!../sdk/esp_iot_sdk_v1.4.0/lib!SDKLIB!' \
    -e 's!.output/eagle/debug/lib!LIB!g' \
    -e '/ 0x0 /d' -e '/ 0x00000000 /d' -e '/\*fill\*/d' -e '/size before relaxing/d' \
    -e '/\.comment/d' -e '/\.debug/d' -e '/^Discarded input sections/,/^Memory Configuration/d' \
     /tmp/mapfile > /tmp/mapfile1
```
This cull leaves one garbage debug block just above the Cross Reference section.  Looking at this, the main area of duplication left is the `libc/c_stdio.c` code.  This defines `c_sprintf()`,`vsprintf()`, `c_strtod()`.  OK, **c_strintf** is just a small wrapper around **vsprintf**, but this latter is just under 1Kb.  We should really be using **ets_vsprintf** here.  Similarly **c_strtod** is ~530 bytes and it tries to be clever to avoid f/p conversions.  There's a KISS approach that we could use by wrapping this around **ets_strtol**.

However, these are pretty minor and only impact Flash rather than RAM utilisation.  So all in all, looking good.

**Comment by TerryE** [comment]
Update on my previous sizing post.  I noticed that I had `CLIENT_SSL_ENABLE` in my `user_config.h`.  disabling this dropped the Flash size by around 40Kb, so that the blank FS space is **68,021** and the RAM is **43440**.  Houston we are good for lift off!

**Comment by samedcildir** [comment]
I'm not sure if this is a bug or I'm doing something wrong but the code below is working on dev branch but it doesn't work on this branch. It receives UDP message but cannot send anything.
I tried it with and without `net.multicastJoin`.

    wifi.setmode(wifi.SOFTAP)
    cfg={}
    cfg.ssid="experiment"
    wifi.ap.config(cfg)
    
    net.multicastJoin(wifi.ap.getip())
    svr=net.createServer(net.UDP)
    svr:on("receive",function(svr, pl)
        print("received: "..pl)
        print("sending: "..pl)
        svr:send(pl)
        collectgarbage()
    end)
    svr:on("sent",function(s) 
        print("on sent called")
    end)
    svr:listen(1453)

**Comment by devsaurus** [comment]
> `file.fsinfo()` reports 22,841 free

spiffs really drops low with 1.4.0. I compared it against current dev and got the following flash consumption for a build containing node, file, gpio, wifi, net, i2c, spi, tmr, uart, bit, mqtt, u8g, rtcmem, rtctime, rtcfifo, sntp (it's a typical use case for me here). On 1.4.0 there's no space left at all for a file system in this configuration.

This renders a 512k module more or less unusable as long as there's no room for spiffs. Is there anything that can be done to resolve this?

                 | v1.4.0 | dev | delta
-----------------|--------|-----|-------
libdriver.a	 | 4362 | 4513 | -151
libphy.a	 | 34411 | 34981 | -570
libpp.a		 | 22419 | 16506 | 5913
libnet80211.a	 | 41094 | 30235 | 10859
libwpa.a	 | 21230 | 20616 | 614
libmain.a	 | 20155 | 13069 | 7086
libsmartconfig.a | 24406 | 14375 | 10031
libssl.a	 | 47722 | 31341 | 16381
liblwip.a	 | 42687 | 36580 | 6107
libplatform.a	 | 4131  | 3906  | 225
liblua.a	 | 71665 | 71924 | -259
libmodules.a	 | 50945 | 42808 | 8137
libuser.a	 | 716   | 541   | 175
spiffs.a	 | 18786 | 18496 | 290
libc.a		 | 1777  | 314   | 1463
mqtt.a		 | 2086  | 1934  | 152
u8glib.a	 | 15254 | 15254 | 0
libgcc.a	 | 0     | 256   | -256
fill		 | 2313  | 2147  | 166
		 |       |       |
TOTAL		 | 426159 | 359796 | 66363

**Comment by jmattsson** [comment]
@samedcildir Nope, don't think you were doing something wrong. The 1.4.0 SDK changed how UDP sockets behaves, which broke udp server send. I've updated to cater for this change, please try again with the latest :)

@devsaurus Nice table! As you can see though, the majority of the increase is in the SDK itself. I am curious as to why libmodules.a would have grown by 8k though - I've barely made any changes there. Any chance you could do some further analysis on that?

**Comment by volca** [comment]
Hi,

I tried the branch with default config.

```
NodeMCU 1.4.0 build 20151006 powered by Lua 5.1.4 on SDK 1.4.0
```

I got this. Is it a bug?

```
> gpio.mode(4, gpio.OUTPUT)
stdin:1: attempt to call field 'mode' (a nil value)
```

**Comment by samedcildir** [comment]
@jmattsson thank you :) now its working

**Comment by jmattsson** [comment]
@volca I don't see any possible configuration where the gpio module not contain the 'mode' function. The two possibilities I can think of would be if the flashing wasn't fully successfult, or if you've somehow managed to run something along the lines of `gpio = {}` to replace the gpio module at runtime. And to use the classic line: running `gpio.mode(4, gpio.OUTPUT)` works fine for me.

**Comment by TerryE** [comment]
@devsaurus your results confirm mine.  **mqtt**, **u8g**, **ssl** will be enough to overflow a 512Kb SRAM.  I see 1024Kb as a practical minimum for a full library application.  I use RPi based HA as my main application tier with a pretty bare MD5+shared secret signed UDP packet protocol between the RPi and the ESPs so 512Kb parts are usable in my case.

**Comment by pastukhov** [comment]
I'm getting 
```invalid clock divider```
with 
```spi.setup(1, spi.MASTER, spi.CPOL_LOW, spi.CPHA_LOW, spi.DATABITS_8, 0)``` on u8glib examples with spi display and 1.4 sdk

**Comment by devsaurus** [comment]
> I'm getting invalid clock divider

This is not related to the SDK update, but a separate change in dev branch. Ref #674.

**Comment by pastukhov** [comment]
@devsaurus thanks. I move my issue to #674

**Comment by devsaurus** [comment]
@jmattsson 

> I am curious as to why libmodules.a would have grown by 8k though - I've barely made any changes there. Any chance you could do some further analysis on that?

My bad, sorry - The v1.4.0 figures were from a `NODE_DEBUG` compile. I update the table with a matching compile result. Now just the SDK remains with its increased flash footprint.

**Comment by karrots** [comment]
Upgraded a MQTT project I am helping with. It works great! Memory leaks on HTTP requests are gone. Same with the other random memory leaks. Aside from the random MQTT bugs which are unrelated to this patch set it seems good. Thanks for this patch set its going to be a great help to a [project](https://saintcon.org/badge/) I am helping with.

**Comment by pastukhov** [comment]
Can anyone create dev140 branch with this pull request, or it is not good idea?

**Comment by TerryE** [comment]
@jmattsson and I can amongst others.  I think that Jonhy was just soliciting consensus before doing so and he's got it :)

**Comment by creationix** [comment]
Is there somewhere that has the advantages of moving to the new SDK somewhere?  I mean other than being up-to-date with upstream tools which is always a good thing.

**Comment by devsaurus** [comment]
Apart from my headaches with the tight flash situation, there's no issue from my side with this upgrade. Both u8g and ucg modules are working as before.
On top of all the SDK improvements, I experience a significantly better responsiveness to interactive commands (using ESPlorer) - feels much more reliable.
One cosmetic thingy is the change in handling of CR+LF. Before, the interpreter would consume both as one and come back with a single newline. Now it returns two prompts when the command was terminated with a CR+LF sequence. Was this introduced intentionally?

A great job, indeed! I'm looking forward to having this in upstream :smiley:

**Comment by marcelstoer** [comment]
> Is there somewhere that has the advantages of moving to the new SDK

I guess the best bet would be to crawl through the [Espressif SDK change logs](http://espressif.com/new-sdk-release/).

**Comment by marcelstoer** [comment]
@vowstar in the discussions on #577 I was under the impression we all agreed that it'd be desirable to have _fewer_ branches rather than _more_? I was hoping that when this gets merged to dev you would remove dev096 and dev120 but instead we now also have dev140. What's your strategy?
Sidenote: if you removed dev120 #543, #552, #563, #625 and #573 could also be closed.

**Comment by TerryE** [comment]
+1 on retiring `dev096` and  `dev120`.  I see no further benefts of doing any more work on these.

**Comment by marcelstoer** [comment]
@TerryE would you want to keep `dev140`? IMHO this should be retired as well.

**Comment by TerryE** [comment]
@marcelstoer, in my view we should have a minimum of three active branches;

*    **Stable release**.  (though it might not be called this) -- the last stable version that has been fully tested and we can recommend to general programmer / developers as a "safe bet" 
*     **Master**.  The main stable branch is current testing, with content that has been reasonably peer tested/
*    **DevNNN** (in this case dev140) -- the current active development version.  We would encourage advanced developers to try this out and give feedback .  It would be he most feature-rich but not necessarily 100% stable.

In this sort of scenario, there is a role for `dev140`.

**Comment by karrots** [comment]
Would **Stable Release** be a tag or branch?

**Comment by TerryE** [comment]
IMO, both a tag on a branch designated for that release.  Branches are lightweight on Gut.

**Pull request merged**
