### PR TITLE
Next master drop

### PR DESCRIPTION
**Pull request by marcelstoer**
As said earlier I don't know whether this should land on master or release. @nwf your advice required here.

### CODE REVIEW

**Comment by nwf** [comment]
I think we should land it on `release` and then bump `master` to match (easily done from the command line: `git push origin origin/release:master`) as we are currently keeping both labels for downstream consumers (notably RTD, right?).

**Comment by marcelstoer** [comment]
Fine for me. Who's willing to approve and merge (but not squash 😉) this?

Oh, and I just noticed this will shrink our LoC significantly:  +2,942 −218,841 😄 👍

**Comment by HHHartmann** [comment]
I would like to add a win luac.cross to the Abonnenten of the release. I did so for the last release but as a change which Akaik doesn't get sent out again

**Comment by marcelstoer** [comment]
> nwf merged commit

Thanks.

>  I don't know whether this should land on master or release

I see we now have two tags: https://github.com/nodemcu/nodemcu-firmware/releases. We're certainly not going to write release notes twice but which one is it gonna be?

@HHHartmann sorry, I don't understand this remark.

**Comment by HHHartmann** [comment]
@marcelstoer When cutting a new release we write a release note which has download links attached. Usually the source code.
To the last release I added, after the release was announced, a luac.cross.exe binary. I would like to add this right on the announcement, so that all receivers of it know that the download exists.
I built the binary locally on my machine, as I did now.
So how can we get this done. I can send it to whoever, as requested.

**Comment by marcelstoer** [comment]
> So how can we get this done.

Attach it to your comment above. Once I get feedback on

> I see we now have two tags: https://github.com/nodemcu/nodemcu-firmware/releases. We're certainly not going to write release notes twice but which one is it gonna be?

(from @nwf maybe?) I can write release notes and announce the master drop. Would maybe then also allow us to close #3164?

Side note: just realized that #3191 is still open but should have been "included" before the last master drop.

**Comment by nwf** [comment]
I'd go for writing the release notes on the `release` tag, and maybe add a forwarding link from the `master` tag citing #3164?

**Comment by marcelstoer** [comment]
And https://github.com/nodemcu/nodemcu-firmware/#releases needs to be updated, too. I stopped publishing `master` to RTD and `/master` redirects to `/release`: https://nodemcu.readthedocs.io/en/master/

**Comment by HHHartmann** [comment]
Since merging this there have been some fixes which might make sense to have in release rather sooner than later.

These are the file fix #3280 , not being able to red files of certain sizes, which I think is essential
and the two enduser_setup PRs #3275 and #3282 would be nice.

BTW: There is also a reference to master in the issue template.

**Comment by marcelstoer** [comment]
@HHHartmann you may now attach your binaries to https://github.com/nodemcu/nodemcu-firmware/releases/tag/3.0-release_20200910

**Comment by marcelstoer** [comment]
> BTW: There is also a reference to master in the issue template.

Sorry, didn't find it. Fortunately [GitHub uses the _default_](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates) rather than the _master_ branch:

> Issue templates are stored on the repository's default branch

**Comment by HHHartmann** [comment]
> @HHHartmann you may now attach your binaries to https://github.com/nodemcu/nodemcu-firmware/releases/tag/3.0-release_20200910

Done.
Maybe we can add it before sending out the announcement, so people will more likely spot it.
Should we add this to the docs somewhere?

**Comment by HHHartmann** [comment]
> > BTW: There is also a reference to master in the issue template.
Its here: https://github.com/nodemcu/nodemcu-firmware/blob/release/.github/PULL_REQUEST_TEMPLATE.md 
- [ ] This PR is for the `dev` branch rather than for `master`.

**Comment by marcelstoer** [comment]
Thanks, that'll eventually bubble up to the default branch.

**Pull request merged**
