### PR TITLE
Update flash.md

### PR DESCRIPTION
**Pull request by robertio**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [ ] This PR is for the `dev` branch rather than for `master`.
- [ ] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/en/*`.

\<Description of and rational behind this PR\>
Hi, 
please update Flashing section with my two comments:

Flashing tricks for ESP-01 and ESP-12 from different forum posts like http://www.esp8266.com/viewtopic.php?f=23&t=11233&start=4 and http://www.esp8266.com/viewtopic.php?p=52965#p52965

### CODE REVIEW

**Comment by marcelstoer** [comment]
Thanks for trying to help improve our documentation. I personally find the examples unnecessary because the information is redundant. I see no added value but let's hear what my fellow collaborators think.

Closing because it's for `master` rather than `dev`.

**Comment by robertio** [comment]
Hi Marcel,

Thanks for quick reply.
More than 5 hours digging of forums needed to flash ESP-01 with the new Nodemcu. :) 

Lots of things has been changed from previous Nodemcu flash method:
1. Needed to give  -fs (Flash Size) and -fm (Flash Mode). 
(And in addition fs size is wrong in case of ESP-1 not 4 but 8!)
2. Needed flash in two step (not in one step) in case of ESP-12.
3. after flash Baud Rate must be set to 115200 or else garbage coming to terminal.

So please allow my comments to help others! to save them hours of googleing.

Best Regards,
Robert

**Comment by marcelstoer** [comment]
My point is that all information is already in the docs. `esptool.py` parameters, esp init data, etc....all there: http://nodemcu.readthedocs.io/en/master/en/flash/. 1-step is supported, is documented and it works.
For `dev` which is going to get merged to `master` in a few weeks esp init data flashing is no longer necessary but that's documented as well: ttp://nodemcu.readthedocs.io/en/dev/en/flash/.

**Comment by robertio** [comment]
Hi Marcel,

You are right esp init data flashing is no longer necessary.
But documentation is wrong in ESP-01 FS size not 4 but 8!!
and after flash Baud Rate must be set to 115200 or else garbage coming to terminal.
Is this last thing mentioned anywhere?

Best Regards,
Robert

**Comment by marcelstoer** [comment]
> But documentation is wrong in ESP-01 FS size not 4 but 8!!

Since when did "they" start selling ESP-01 with 1MB? All ESP-01 _I_ ever saw had 512KB.

> and after flash Baud Rate must be set to 115200 or else garbage coming to terminal.

Yes, as the next step after flashing is uploading we placed it here http://nodemcu.readthedocs.io/en/latest/en/upload/ (and here http://nodemcu.readthedocs.io/en/latest/en/modules/uart/). However, auto-baud detection is supposed to kick-in if you don't use 115'200. @pjsg are you aware of any issues regarding auto-baud detection?

**Comment by robertio** [comment]
Hi,

>Since when did "they" start selling ESP-01 with 1MB? All ESP-01 I ever saw had 512KB.
I dont think esp01 has 1MB but the fact is I tried with -fs 4m as written in documentation and having blue LED blinking issue, for half day. 
but later I found this forum post:  http://www.esp8266.com/viewtopic.php?p=52749#p52749
I tried this and now it is working like a charm.
 python esptool.py --port /dev/ttyUSB0 write_flash  -fm qio  -fs 8m 0x00000 ./nodemcu-master-9-modules-2016-11-08-09-33-18-integer.bin

Best Regards,
Robert

**Comment by pjsg** [comment]
As far as I can tell, the autobaud stuff is working. In esplorer, if you set the wrong speed (say 9600) and then reset the board (e.g. by clicking RTS twice), then you see the garbage characters.

Then click 'send' and send in a few characters a couple of times and the speed will adjust and it will echo.

**Comment by marcelstoer** [comment]
@robertio can you tell us what the functions to return flash size report in your case: http://stackoverflow.com/a/39633139/131929

**Comment by devsaurus** [comment]
> Since when did "they" start selling ESP-01 with 1MB?

I can confirm that there are modules on the market which have the same shape, footprint, etc like the original ESP-01 but contain a 1 MByte flash. I have some on my desk and used them already for projects with extended spiffs requirements.
For these the `-fs 8m` was necessary with `master` or the old `dev`, since firmware detects the flash size automatically.

**Comment by marcelstoer** [comment]
Oh, not good. Then we should mention that in the flashing docs and also add a small chapter about how to determine flash size. I can prepare something later so we have that ready before the next master drop.

**Comment by robertio** [comment]
Hi Marcel, and Arnim

Thanks for response me.
print(node.flashsize())
1048576 (which is 0x100000 in hex.)

=node.flashid()
1327328  (which is 0x1440E0 in hex.)

I tried to find the hex value in the link you gave (
https://code.coreboot.org/p/flashrom/source/tree/HEAD/trunk/flashchips.h )
but didnt find.


Thanks Arnim for confirm 8m is needed in certain cases!


Marcel, did You do "NodeMCU custom builds" ?
You are genius!  :) It is marvelous. It is docker based in cloud.
fascinating technologies all together!  Free for community -  Thank you
very much!  :)))

Best Regards,
Robert


2016-11-09 7:17 GMT+01:00 Marcel Stör <notifications@github.com>:

**Comment by marcelstoer** [comment]
> Marcel, did You do "NodeMCU custom builds" ?

Yes, the cloud builder and the [Docker image](https://hub.docker.com/r/marcelstoer/nodemcu-build/) are from me.

> You are genius!  :)

Far from it, it's all a matter of perspective. To me my fellow NodeMCU collaborators who can actually write firmware code are geniuses. I just watch in awe what they pull off.

**Comment by nickandrew** [comment]
All my ESP-01 modules are 1Mbyte flash. At least that's what the ID code on the flash chip represents.

**Comment by robertio** [comment]
Hi,

Can someone help why I didnt find my ESP-01 device ID?

print(node.flashsize())
> 1048576 (which is 0x100000 in hex.)
>
> =node.flashid()
> 1327328  (which is 0x1440E0 in hex.)


yesterday I re flash two another ESP-01 device and also need to use 8m or
else blue led was blinking continously.
So it seems I also has only 1M units...

best regards,
Robert


2016-11-09 11:10 GMT+01:00 Robert Szabo <robert1968@gmail.com>:

**Comment by marcelstoer** [comment]
You need to get the flash ID with esptool as per http://nodemcu.readthedocs.io/en/latest/en/flash/#determine-flash-size.

**Comment by robertio** [comment]
Thanks again Marcel, I will try on my next esp. (planned within few days.)

I congratulation for the well organised documentation as well.
It looks very professional!

I would thank you very much for all the work :)

Best Regards,
Robert


2016-11-16 14:33 GMT+01:00 Marcel Stör <notifications@github.com>:

**Comment by robertio** [comment]
Hi Marcel,

I spend 1 hour because esptool.py always throw "Failed to connect" error.
This was also the case when I ever tried it earlier.
Then I realized GPIO0 must be grounded...

esptool.py --port /dev/ttyUSB0 --baud 115200 flash_id
> esptool.py v1.2.1
> Connecting...
> Manufacturer: e0
> Device: 4014


So probably in the documentation should be mention in Determine flash size
section:
Keep in mind that the ESP8266 needs to be put into flash mode
<http://nodemcu.readthedocs.io/en/latest/en/flash/#putting-device-into-flash-mode>
before
you can query device information (similar to Flashing)

Best Regards,
Robert

2016-11-16 14:33 GMT+01:00 Marcel Stör <notifications@github.com>:

**Pull request closed without merging**
