### PR TITLE
Make tmr.time() more resilient against RTC changing frequency

### PR DESCRIPTION
**Pull request by jmattsson**
While we normally use the `rtctime` module for good timekeeping, we had a use-case where we needed `tmr.time()` and then got caught out by it drifting wildly (and even going backwards). This is the patch to address that.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Wouldn't that fix #690?

**Comment by jmattsson** [comment]
Yes, I believe it would.

**Comment by devsaurus** [comment]
Looks good to me :+1:

**Comment by TerryE** [comment]
And me :+1:  Johny you can merge it.

**Pull request merged**
