### PR TITLE
2.1.0-follow-up master drop

### PR DESCRIPTION
**Pull request by marcelstoer**
Contains all issues referenced in the ["2.1 follow-up" milestone](https://github.com/nodemcu/nodemcu-firmware/milestone/6?closed=1).

### CODE REVIEW

**Comment by TerryE** [comment]
@marcelstoer Marcel, I notice that no one has commented on #2048.  OK, let's do this drop, but I really feel that we should discuss and resolve this before any more master drops.  We shouldn't make this sort of change to master as we have done without assessing the implications.

**Comment by dnc40085** [comment]
@TerryE My apologies I have been busy and I haven't been able to get on here and comment, but I have been working on a solution to #2048. I'll push a branch later with the changes and post back.

On a side note: I have found that SDK 2.1.0 broke the timed light sleep functionality and I think it would be a good idea to disable it before the master drop.

**Comment by marcelstoer** [comment]
@TerryE That sounds reasonable, sure. No one has commented on that issue and no one has come forward volunteering to do these master drops aka releases for the past year. That's why I just keep sticking to our self-imposed 2 months interval - unless there's good reason not to.
Feel free to close this PR.

**Comment by TerryE** [comment]
@dnc40085 has opened #2056, but this is something that we should do for a dev release first.  The only change that I would propose for merging in to incorporate into this push from dev to master would be to make the `ENABLE_TIMER_SUSPEND` and `PMSLEEP_ENABLE` defines (see [user_config.h:118-119](/nodemcu/nodemcu-firmware/blob/master/app/include/user_config.h#L118)) commented out by default rather than enabled by default.

**Comment by TerryE** [comment]
@marcelstoer Marcel, why close this? why not just a a push for the two liiner I suggest?

**Comment by dnc40085** [comment]
@marcelstoer PR #2064 covers the modifications @TerryE is suggesting.

**Comment by marcelstoer** [comment]
@fellow maintainers
Just in case you were waiting for me, I won't be merging my own PRs 😜

**Comment by TerryE** [comment]
Marcel, that's a bit of a catch-22, isn't it?  Shoot me later.

**Comment by marcelstoer** [comment]
I finished up as per https://github.com/nodemcu/nodemcu-firmware/blob/master/CONTRIBUTING.md#handling-releases and created a new release: https://github.com/nodemcu/nodemcu-firmware/releases/tag/2.1.0-master_20170811

Feel free to revise the release notes.

**Comment by TerryE** [comment]
Very impressive.  Thanks Marcel! :smile:

**Comment by TerryE** [comment]
No, the process and that you drive it.

**Pull request merged**
