### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by timg11**
This is only a suggested page to improve the documentation. 

- [x ] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).

### CODE REVIEW

**Comment by TerryE** [comment]
Leaving aside you've some done this PR of an old dev so it's messed up, I really think that you should raise this as an issue and we should address this in the FAQ as specific point on io and file.

> If you came here looking for the Lua `io` module that doesn't exist in NodeMCU, read on. 

> The only mention of the `io` module in NodeMCU is in the [NodeMCU Developer FAQ](https://nodemcu.readthedocs.io/en/master/en/lua-developer-faq/), where it says 
"For example, the standard `io` and `os` libraries don't work, but have been largely replaced by the NodeMCU `node` and `file` libraries."

> Unfortunately, if you are new to NodeMCU and Lua, there is little to go on to understand how to proceed.  If you have read the Lua documentation on [The Simple I/O Model](https://www.lua.org/pil/21.1.html),  you might be looking for io.write as a way to output text similar to print() but with more control. With NodeMCU, the `file` library is suggested as a replacement, but it will not write to stdout like io.write. `file.write(string)` will not work because there is no file open.

> It is not clear how to proceed without the `io` module. There is nothing analagous to stdout to open.  The solution is to use the uart module.  The Lua example `io.write("hello", "Lua")` would be written `uart.write(0,"hello", "Lua")`

> Note that the UART ID value of 0 has to be added. UART 0 is the same one the the print() function uses.

The ESP is an IoT device and does not have a POSIX OS or the like, so the full features offered by a typical OS aren't available.  The original authors chose to mirror the then features of the SPIFFS implementation and basic UART drivers.  The current developers here had all become familiar with this before they became committers so have never seen the need.  Perhaps we should spell this out, but the answer is not a "this module is not here" in dummy `io` and `os` slots in the modules section but as as a more expanded point in the FAQ.

**Comment by marcelstoer** [comment]
@timg11 I have to agree with Terry here. I think you raised a valid point and kudos for offering this as PR. Unfortunately we can't accept it as-is due to the issues Terry mentioned.

-> I created #2462

**Comment by timg11** [comment]
As a newcomer to NodeMCU and Lua, I found the existing FAQ (although well written) did not point me in the right direction to find my solution. The statement "The current developers here had all become familiar with this," while undoubtedly true, is still not helpful to a newcomer. If you would like to use any of my text to edit the FAQ, please do so. I can also make an attempt of another PR on the FAQ directly if you would consider it.

**Comment by marcelstoer** [comment]
#2462 is one specific topic in the broader context of #2332.

**Pull request closed without merging**
