### PR TITLE
Corrected SPI CPOL/CPHA relationships

### PR DESCRIPTION
**Pull request by jfollas**
Fix for issue #1161

### CODE REVIEW

**Comment by TerryE** [comment]
This looks sensible, but I'd rather have another committer who has an SPI test rig, such as Arnim (@devsaurus) take a look and OK this.

**Comment by jfollas** [comment]
I saw the opportunity to do a tiny refactoring to remove duplicate code in my implementation, so added that to the PR.

**Comment by devsaurus** [comment]
I can reproduce the fixed MOSI generation and it's in line with the expected [polarity and phase](https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus#Clock_polarity_and_phase).

Next I need to figure out how to verify that the correct SPICLK edge is used for sampling MISO in all four modes. It'll take a couple of days until I've set up a testbench for that.

**Comment by devsaurus** [comment]
Sampling of MISO works also well. Although a bit differently from how I expected it to be.

I built a test slave that outputs to MISO with surrounded-by-low instead of NRZ to identify the sampling edge. This revealed that the ESP samples on the very same edge on which it outputs MOSI data. 

This is a transaction with CPOL=0 and CPHA=0. The ESP requires that MISO bits are available at falling clock edge (slave transmits 0xaa):

spi_sbl

Summary: MOSI and MISO timing is controlled by `SPI_CK_OUT_EDGE` only. There's no influence on MISO sampling from `SPI_CK_I_EDGE`. It's probably used for SPI slave mode.

**Comment by jfollas** [comment]
I'm surprised about the `SPI_CK_I_EDGE` finding. But, given the documentation (or lack of), I'm not too surprised. 

So we can take `SPI_CK_I_EDGE` out of the code altogether without changing the behavior?

**Comment by devsaurus** [comment]
> So we can take `SPI_CK_I_EDGE` out of the code altogether without changing the behavior?

No change in behavior regarding MISO sampling as far as I can tell, yes.
But it'd be a certain risk since we don't know which other side effects might be triggered. Without design docs I can't derive a dedicated test case to check for regressions when `SPI_CK_I_EDGE` is removed; except for running "everything" and hoping to trigger & observe deviations.

How about keeping `SPI_CK_I_EDGE` as it is now but just correct the comments (they say that MISO is read on the other edge atm) and update the documentation accordingly?

**Comment by jmattsson** [comment]
Any updates on this?

**Comment by jfollas** [comment]
@devsaurus's test shows that the ESP isn't behaving per spec - not sure if that's by design, or if we have a wrong bit setting (or need to use yet-another undocumented bit). I tried asking Espressif for clarification, but you know how that goes. Crickets.

This PR fixes my specific issue when CPOL=1, and there doesn't seem to be any problems for my slave devices with the ESP sampling MISO data half a clock cycle too soon. 

I'm personally okay with the PR as is, and if we get a better understanding for how to shift the input to the correct clock edge, there can always be another PR later.

**Comment by devsaurus** [comment]
I'm also fine this conclusion.

@jfollas please remove the comments that make assumptions about MISO sampling like "`MISO is read on falling edge of clock`". Then we're ready to go.

**Pull request merged**
