### PR TITLE
Add note on dev board usage of SPI bus 0

### PR DESCRIPTION
**Pull request by mdpye**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] (NA) I have thoroughly tested my contribution.
- [x] (NA) The code changes are reflected in the documentation at `docs/en/*`.

Documentation only.

I spent time and effort researching the mapping from bus number to the SPI/HSPI pin groups and also ran in to confusion with bus 0 being already in use by my dev board. This note is what I wish I'd found when first opening this module.

### CODE REVIEW

**Comment by jmattsson** [comment]
:+1:

**Comment by marcelstoer** [comment]
Should we also add a back-reference to this new chapter from each `id` parameter description ("SPI ID number: 0 for SPI, 1 for HSPI")? Something like "see note on bus IDs".

**Comment by luismfonseca** [comment]
Back-reference too much noise, given how short the document is.

Maybe highlight this using the `note` syntax:
```
!!! note
    some test

```

**Comment by marcelstoer** [comment]
Ok, I'll add that after the merge.

**Pull request merged**
