### PR TITLE
Add i2c based module for am2320 humidity sensor

### PR DESCRIPTION
**Pull request by hvegh**
- rebased on dev
- added documentation page
- removed ICACHE_FLASH_ATTR

Example use:
> sda=1
> scl=2
> am2320.init(sda,scl)
> print(string.format("Temperature: %s degrees C", t / 10))
> print(string.format("RH: %s %%", rh / 10))

signed-off-by: henk.vergonet@gmail.com

### CODE REVIEW

**Comment by pjsg** [comment]
It would be nice if the API was compatible with the AM2302/DHT22 code.

**Comment by hvegh** [comment]
Hmm I don't fancy the API of the dht module much :(. 
For one thing it relies on the use of floating point logic. 
The second thing that is less optimal. It tries to accommodate two data versions for a single measurement.
The 3rd thing that is somewhat less optimal, is the incarnation of 3 different methods to read stuff from the sensor (read read11 readxx) of what is essentially a integer reading of temperature and humidity. 

I do agree that it would be nice to have a more generic API in order to communicate measurement data. Something that would allow to give additional information on the unit type (voltage/current/time/temperature celcius/distance meters/percentage .....) and the scaling in order to automatically be able to nortmalize to  internationalized SI standards https://en.wikipedia.org/wiki/SI_base_unit

Regards,
Henk 

But this would require a more generic discussion on  

know , the for sure the initialisation is different  the API is pretty simple as is

**Comment by marcelstoer** [comment]
Oh, a PR with proper documentation, great! Ok, just realized that @devsaurus pointed you to our `CONTRIBUTING.md` in your old PR.

I'm willing to merge this once you squash the 6 commits into 1 and force push them.

**Comment by hvegh** [comment]
Nice! Will try to merge this stuf.

**Comment by marcelstoer** [comment]
No need to close it and create another one. Just keep (force) pushing to your branch. GitHub will update this PR automatically.

**Comment by hvegh** [comment]
This is advanced git stuff for me :) messing around with:

git rebase -i HEAD~8
git push origin dev --force

At least this merged stuff in my dev fork...

**Comment by hvegh** [comment]
Looks like the merging worked...

**Comment by marcelstoer** [comment]
Life's a dance, you learn as you go :wink:  See how GitHub updated the PR and now only shows a single commit? Nice, isn't it.

**Comment by mariocytr** [comment]
I have bought one am2320 recently and this library works after I changed the i2c address to 0x5c and recompiled the nodemcu firmware

**Comment by marcelstoer** [comment]
It would be handy if the module allowed you configure the address, wouldn't it 😞

**Comment by HHHartmann** [comment]
But we will need a new bug/PR for that.

**Comment by marcelstoer** [comment]
Certainly 😄It would be desirable IMO to do this consistently for all I2C modules.

**Pull request merged**
