### PR TITLE
Don't allocate flash to SPIFFS that is reserved by the system.

### LINKED ISSUE #3208: Wifi connection lost..... No reconnection
NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: dev
	commit: 2fa63a1303493aa66831af5466311436d11cf827
	release: 
	release DTS: 202007071335
	SSL: false
	build type: integer
	LFS: 0x40000 bytes total capacity
	modules: file,gpio,mqtt,net,node,rtctime,sntp,tmr,uart,wifi
 build 2020-07-08 00:54 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

I am using above build....
In long run wifi gets disconnected and does not reconnect automatically. even if i do a soft reset using  node.restart() but if i toggle power supply it reconnects.
had this issue with 4 esp-07 devices .
not sure if it is a bug or not......

### PR DESCRIPTION
**Pull request by pjsg**
Fixes #3208

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.

This PR just subtracts the 20k reserved memory from the end of the flash before setting up the SPIFFS partition. This also explains why the contents of SPIFFS would get corrupted on the dev branch.

The downside of this change is that this will trigger a SPIFFS reformat (if you didn't have a fixed size spiffs). However, that is a good thing as it will no longer overwrite *important stuff*.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Thanks Philip!

**Comment by TerryE** [comment]
My concern here is that this area hasn't been reserved or used by the system since SDK 2.x. Since SDK 3.0, the system used the areas defined in the PT. See [user_main.c:L81-83](../blob/release/app/user/user_main.c#L81).  I did check at the time of testing this that SDK now uses the `RF_CAL`,`PHY_DATA` and `SYSTEM_PARAMETER` system partitions by erasing the old 5 pages and running a chip for a bit before checking again, but I might have missed something or some code path still uses the old locations.  So this might be work validating.  

However _if_ I am right this fix won't fix anything.  I've just checked Wemos D1 mini pro that I've been testing on for a few weeks using ` esptool --port /dev/ttyUSB0 --baud 460800 read_flash 0xfb000 0x05000 /tmp/x.bin` and this area is still all `0xFF`s.

**Review by TerryE — CHANGES_REQUESTED** [review]
Please do not merge or restart using SDK 2.x features until we have bottomed this issue.  Thanks.

**Comment by pjsg** [comment]
@TerryE What was interesting is that when this happened, the old contents of the last 12k (I was only saving 12k) did include my SSID and password, and then, when it stopped working, the SSID and password was gone.

Also I I do `wifi.sta.config({ssid="test ssid 1234", pwd="test pwd 1234"})` then those strings show up in the last 20k of flash.

*Something* is certainly writing to that area, and there is strong evidence for something reading from that area.

**Comment by NicolSpies** [comment]
@pjsg, as mentioned in #3148, I have been doing continuous ongoing testing related to the SPIFFS, I also started experiencing the problem of the failing WiFi connection. Both the failures (SPIFFS related corruption & disappearing files and WiFi connection) happened at least once every 24 hours.

I have implemented your suggested change, since then none of the long time present problems have been observed so far. I will report if it changes.

**Comment by TerryE** [comment]
@pjsg Philip  We have 3 reserved system partitions: `RF_CAL`,`PHY_DATA` and `SYSTEM_PARAMETER` .  We moved these to the "dead" region before the firmware, that is 0xB000 - 0xFFFF back when we did the 2.x to 3.0 upgrade; the pros and cons were debated then on the issue and PR.  I accept that I made a mistake in not including WiFi connection tests in my testing at the time and so I missed the fact that the SDK / BIOS code for the WiFi fixed the SP are as the last 3 pages in the flash, so we need to accept and implement this move.

What I don't understand is why we should also move the other two back since we _have_ validated that the SDK correctly uses the current versions.  

My suggestion is that we only move the SP partition back. We also need to check the `node.setpartitiontable()` and `nodemcu-partition.py` code to make sure that these still work.  We also need to check that this interplays well with the RFcal initialisation code ad the flash size reset.   

I will prepare and push an update along these lines, so please post back here if you disagree and then we can open this debate for resolution, before doing the change.

**Comment by pjsg** [comment]
I don't have any evidence that it is using the 2 pages before the last 3
for anything. I just assumed (yes, I know) that if they screwed up the
system parameter area, they probably screwed up the other areas as well. If
those areas do seem to be mapped down low, then that is great.

**Comment by galjonsfigur** [comment]
> I missed the fact that the SDK / BIOS code for the WiFi fixed the SP are as the last 3 pages in the flash, so we need to accept and implement this move.

It was very easy to miss, as Espressif stated in the [first documentation of partition table](https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/documents/EN/%20Partition%20Table.md) that SYSTEM_PARAMETER partition has to be declared and can have custom address. But in "Notes" section of [README](https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/README.md) they state that SYSTEM_PARAMETER partition has fixed address - very inconsistent.

**Comment by TerryE** [comment]
> they probably screwed up the other areas as well. If those areas do seem to be mapped down low, then that is great

No, I don't think the other two are screwed up.  These partitions are updated as per the PT, and there is no evidence that the corresponding high pages are touched.  As @galjonsfigur points out, the documentation states: "`SYSTEM_PARTITION_RF_CAL`, `SYSTEM_PARTITION_PHY_DATA` and `SYSTEM_PARTITION_SYSTEM_PARAMETER` have to be defined in the partition table in application. _Users can change their addresses according to practical needs_."  However, the README also states that this last must be at the "correct address" (the 3 three pages of flash)

Even if we do move the SP partition back to end of flash, we still need to keep the PT valid and my code assumes that (and also validates that) the individual partitions are in ascending address and are non-overlapping, so we need to resort and update the PT to avoid side-effects.  I've made the changes and tested the load + node functions.  

`nodemcu-partition.py` doesn't crash now.  I am not really happy with this, but it is as good as it was.  I think that it is better to get this patch in before the next drop.  We can reconsider  `nodemcu-partition.py` as a low priority.

**Review by TerryE — APPROVED** [review]

**Pull request merged**
