### PR TITLE
ADC extension for ESP32

### PR DESCRIPTION
**Pull request by zelll**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

Supports ADC1 in ESP32.

### CODE REVIEW

**Comment by devsaurus** [comment]
Looks good, thank you very much!

Once Espressif enables ADC2 support, how will it be integrated?
Eg by separate functions in `adc` module or an extra `id` parameter?

**Comment by zelll** [comment]
ADC2 can not work with WiFi/BT, so personally I don't think it's important for most users. But it would be great if someone wants many ADC channels.

Maybe, like this?
```
adc.setwidth(bits, adc = 2)
adc.read(8) , adc.read(17)
```

**Comment by devsaurus** [comment]
Unfortunately, the [Technical Reference Manual](http://espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf) doesn't provide any details on ADC1 and ADC2, so it's kind of guessing how the API for ADC2 will look like.
Since the current IDF has dedicated functions like `adc1_config_width()`, I'd expect that there will also be dedicated ones for ADC2 like `adc2_config_width()`. This could be handled with a parameter for each Lua function:
```lua
adc.setwidth(adc.ADC1, 8)
adc.setwidth(adc.ADC2, 12)

print(adc.read(adc.ADC1, 0)
print(adc.read(adc.ADC2, 1)
```

But that's guessing, what is your view?

**Comment by zelll** [comment]
Yes, there should be dedicated functions for ADC2 in IDF. https://github.com/espressif/esp-idf/pull/466 does in this way.

I thought we could add a second parameter for ADC2 ` adc.setwidth(channel [, adc = adc.ADC1]) `, but it maybe better to add it as 1st parameter now ` adc.setwidth(adc.ADCn, channel) `...

**Comment by devsaurus** [comment]
Thanks for the link, I wasn't aware of this PR.

Regarding the instance id as the first parameter, it's just by convention that many other existing modules already do it this way.

**Comment by zelll** [comment]
Added adc.ADC1 as 1st parameter and updated docs.

**Comment by devsaurus** [comment]
Thanks again for sharing!

**Pull request merged**
