### PR TITLE
SDK 3.0 release

### PR DESCRIPTION
**Pull request by TerryE**
See #2689

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have ~thoroughly~ tested my contribution.  This one is so big that it needs extra independent testing
- [x] The code changes are reflected in the documentation at `docs/en/*` _but further polish is needed_.

This PR implements the SDK 3.0 partition-enabled support as per #2689 and the previous #2467.  The Lua VM now uses the PT located at offset 0x10000 in the flash image to allocate LFS and SPIFFS as well as being generally compliant with the SDK 3.0 changes.

I am still working on what I've decided to call the nodemcu-partition tool which is a python wrapper script around esptool to handle flash configuration and loading of the nodemcu firmware and partitions.  I had hoped to get the base version out in this PR but I will add this push tomorrow.

As reviewers will see, this has ended up as a pretty large patch.  Sorry for this.  Time for me to have a break and a rest. 

Perhaps reviews can scan through the files changes and ask any relevant Qs and I will answer these points.

Note that:
-  One area that has been updated and streamlined is the SPIFFS code.  This now assumes the partition allocation in PT and doesn't try to do further hidden smarts.  This shortens the startup overhead quite a bit. 
-  Not withstanding this, the user_main code will allocate a 64Kb LFS region and the remainder of the flash to SPIFFS is the compiled PT isn't updated by **nodemcu-partition**
-  You must correctly size your flash using the esptool `-fs` parameter.

### CODE REVIEW

**Comment by galjonsfigur** [comment]
I've tested it on 1MB ESP8285 with just change of `#define FLASH_4M` to `#define FLASH_1M` in `user_config.h` and everything seems to work (tested only simple script that uses LFS, HTTP client, SSL + cert validation, `sjson` and `u8g2`) - having more than 10kb more RAM is really helpful when it comes to connecting to HTTPS client. Some comments:
- new `esptool` warns about using depreciated options when using `flash4m` or `flash1m-dout` targets
- change of `SPIFFS_MAX_FILESYSTEM_SIZE` broke Makefile in `tools` folder
- there are some spelling errors in `getting-started.md` documentation page

Those are not really important issues - I'm not an expert so i try to spot those I can understand.

Will building one image for all flash sizes be possible like on 2.2.1 SDK? From what I can understand partition table introduction in SDK 3.0 complicated everything and for now adjusting `FLASH_xM` parameter is necessary.

**Comment by TerryE** [comment]
> Will building one image for all flash sizes be possible like on 2.2.1 SDK? From what I can understand partition table introduction in SDK 3.0 complicated everything and for now adjusting FLASH_xM parameter is necessary.

You set the flash size using the esptool `-fs` parameter.

**Comment by dtran123** [comment]
I wish I could build the image like galjonsfigur did using TerryE's commits. I've been struggling to get a successful build using the docker method. I am really a beginner in git so building from individual commits is outside my reach at this point. galjonsfigur: can you share the instructions how you got a successful build ? I did a download zip of https://github.com/nodemcu/nodemcu-firmware/tree/d4974c61ce92be7331db2a094464ad4deca0d828 but the build failed due to the missing .git folder in the nodemcu-firmware folder. Keep getting the error:

  inflating: ESP8266_NONOS_SDK-3.0/lib/strip_libc_funcs.txt
  inflating: ESP8266_NONOS_SDK-3.0/lib/strip_libgcc_funcs.txt
PRUNE libmain.a libc.a
make: xtensa-lx106-elf-ar: Command not found
make: *** [/opt/nodemcu-firmware/sdk/.pruned-3.0] Error 127
make: Leaving directory `/opt/nodemcu-firmware'

**Comment by TerryE** [comment]
@dtran123, you can get the zip directly from my branch: https://github.com/TerryE/nodemcu-firmware/archive/dev-sdk-3.0.zip

Unpack it into the nodemcu-firmware folder and make sure to `make clean`  and dump any old cache contents.  `xtensa-lx106-elf-ar` is on the toolchain so you shouldn't be failing to resolve this.

Also read the OP in the PR re your `user_config.h` comment.

**Comment by TerryE** [comment]
I've just added a first cut of the `nodemcu-partition.py` tool.  I am not feeling 100% ATM, and Python isn't a strong language for me, so any improvements will be welcome. 

So what you do to provision the ESP is first to flash the base firmware and then configure the PT / add any LFS ./ SPIFFS image, e.g. 
```bash
tools/toolchain/esptool.py -p /dev/ttyUSB0 -b 460800 write_flash -fs 32m --flash_mode=dio 0x00000 bin/0x00000.bin 0x10000 bin/0x10000.bin
tools/nodemcu-partition.py -ls 128kb -lf ../bin/lfs.img -sa 1mb -ss 1mb
```
The whole tool probably needs a better interface and syntax, but at least this will get developers going with this and SDK 3.0

**Pull request merged**
