### PR TITLE
Dev096 - 433MHz transmit code

### PR DESCRIPTION
**Pull request by mikewen**
Hi There,

I ported 433MHz transmit code from RCSwitch project. 
(For my NodeUSB project.)

Hopfully I can find some free time soon to add receive part.

- Mike,

### CODE REVIEW

**Comment by klukonin** [comment]
I think gpio.serout is the best solution for protocol emulation.
Never mind 433Mhz or IR protocol.

**Comment by pastukhov** [comment]
@mikewen Can you provide some lua examples?

**Comment by mikewen** [comment]
It is very simple to use, just one line of code:
rc.send(gpioPin, code, codeBits, PulseLen, Protocol, Repeat )

Lua code likes like that:
rc.send(4,267724,24,185,1,10)

I only ported transmit code so far, so you need use Arduino to read the
433MHz code first.

**Comment by pastukhov** [comment]
Thanks!

**Comment by ripper121** [comment]
Do you found the time to complete the Receive Part?

**Pull request merged**
