### PR TITLE
Upgrade to SDK 1.5.0 + Espressif's Open LWIP 1.5.0.

### PR DESCRIPTION
**Pull request by TerryE**
This is Johny's SDK 1.5 upgrade including the binary of the SDK in the repo. I suggest that we rebaseline `dev` to this so we can work with 1.5 changes

### CODE REVIEW

**Comment by dnc40085** [comment]
I cherry picked the commit onto my local dev branch. It compiles fine in Eclipse, but even after I added `esp-open-sdk/sdk/include` to `Properties->c/c++ General->Paths and Symbols->includes->GNU C`, I'm still getting a bunch of unresolved types in `wifi.c` (bool, true, false, TRUE, FALSE, sint8_t, uint8_t, etc.) other types (sint8, uint8, etc) are fine though.
any ideas?

**Comment by dnc40085** [comment]
In eclipse, I cherry picked this commit onto my local dev branch, compiled and flashed to my esp-07 and everything worked fine.
However, when I ran `make clean`, it removed the `sdk` directory causing a bunch of "codan errors" in `wifi.c` since it couldn't access the header files in the sdk include directory(/sdk/esp_iot_sdk_v1.5.0/include) to resolve the types and symbols. I solved this by commenting out the line `$(RM) -r "$(TOP_DIR)/sdk"`under the clean target in the main makefile, and all was good after that.

it's more a nuisance than a problem but I thought I might mention it.

**Comment by TerryE** [comment]
@dnc40085, no this is good feedback and we need to fix this before we do the commit.

**Comment by devsaurus** [comment]
Had a test drive with some of my MQTT application - works fine, great :smile:
I also got the impression that heap increased a bit.

Definitely a +1.

**Comment by marcelstoer** [comment]
I don't understand why the SDK should be placed in a directory called `cache`. Seems like a left-over from the attempts in https://github.com/jmattsson/nodemcu-firmware/tree/sdk150dl.

Even with only 8 modules the firmware crashes upon booting when both SSL and debug are ON. I tested with a V2 NodeMCU devkit. ESPlorer at 115k reports:

```
 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x40100000, len 28776, room 16
tail 8
chksum 0x4c
load 0x3ffe8000, len 2404, room 0
tail 4
chksum 0x7f
load 0x3ffe8964, len 8, room 4
tail 4
chksum 0x0f
csum 0x0f 
```

**Comment by TerryE** [comment]
> I don't understand why the SDK should be placed in a directory called `cache`.

For other readers, we have two SDKs:

*   **tools/esp-open-sdk.tar.gz** is the custom build of the esp-open-sdk for Ubuntu 12.04-LTS which is referenced in the `.travis.yml` and unpacked into the `esp-open-sdk` for Travis CI builds,  It isn't used at all on local builds.  An even for Travs builds it contains a _lot_ of unused components and is stored in the inefficient **GZ** format so s about 3× bigger than it needs to be.  However this will only change if Travis CI rebaselines its VM infrastructure.

*    **The Espressif V1.5.0 SDK** (actually a stripped don version only containing the libraries and include files that we use in our build).  This is in cache but is unpacked into the top level directory in the make.  IMO, this should be in `tools` for the `bin` variant as this is part of the repo.

The cache directory is cached by travis, and should be part of `.gitignore` IMO.  So it actually makes sense to explode both SDKs into this folder.  The only material difference for the dl builds should be that (i) we should definitely use a squeezed `esp-open-sdk` tarball and this should be downloaded into cache by the YML file.  (ii) the 1.5 SDK should be downloaded into cache as a make target as this is done by all makes, Travis CI or local.

@marcelstoer, as I said if you are happy to swap to the dl version then let's do that. This is my config (in my `cfg` format.  If you tell me what your failing one is, I will have a go at using it; look at the mapfile, etc..

```
;
; ESP-01 512KB Module config
;
flash_size       = 512K
bit_rate         = 115200
client_ssl       = disable
gpio_interrupt   = enable
spiffs_cache     = enable
sha2             = disable
builtin = string,table,coroutine,math,debug_minimal
modules = node,file,gpio,wifi,net,i2c,tmr,uart,ow,bit

**Comment by marcelstoer** [comment]
> **tools/esp-open-sdk.tar.gz** is the custom build of the esp-open-sdk... It isn't used at all on local builds.

The cloud builder and the [Docker image](https://hub.docker.com/r/marcelstoer/nodemcu-build/) also use it.

> This is my config (in my cfg format). If you tell me what your failing one is, I will have a go at using it

It's more than a tad embarrassing but since I had somehow missed the changes in https://github.com/nodemcu/nodemcu-firmware/commit/4e8ef87d03feb683c753390e2372be6abbf9945d#diff-7a71b1406a9beef39ed3e5f1ff6df026 the cloud builder has ignored the user's module configuration for every build in the last two weeks and used the "default" instead :disappointed: I'm surprised no one had noticed and reported that. I only found out late last night.
So, when I said the crashing firmware had only 8 modules that was not correct. The cloud builder would *report* 8 modules but the firmware actually included a lot more. I feel like a total idiot.

Anyway, with 31 modules and SSL & debug ON the *build* fails because there's just not enough memory.

```
xtensa-lx106-elf-gcc -L/opt/nodemcu-firmware/sdk/esp_iot_sdk_v1.5.0/lib -L/opt/nodemcu-firmware/sdk/esp_iot_sdk_v1.5.0/ld  -Wl,--gc-sections -Wl,-Map=mapfile -nostdlib -T../ld/nodemcu.ld -Wl,@../ld/defsym.rom -Wl,--no-check-sections -Wl,--wrap=_xtos_set_exception_handler -Wl,-static -u ADC_module_selected -u BIT_module_selected -u BMP085_module_selected -u CJSON_module_selected -u COAP_module_selected -u CRYPTO_module_selected -u DHT_module_selected -u ENDUSER_SETUP_module_selected -u FILE_module_selected -u GPIO_module_selected -u HX711_module_selected -u I2C_module_selected -u MQTT_module_selected -u NET_module_selected -u NODE_module_selected -u OW_module_selected -u PWM_module_selected -u RC_module_selected -u RTCFIFO_module_selected -u RTCMEM_module_selected -u RTCTIME_module_selected -u SNTP_module_selected -u SPI_module_selected -u TMR_module_selected -u TSL2561_module_selected -u U8G_module_selected -u UART_module_selected -u UCG_module_selected -u WIFI_module_selected -u WS2801_module_selected -u WS2812_module_selected -Wl,--start-group -lc -lgcc -lhal -lphy -lpp -lnet80211 -lwpa -lwpa2 -lmain -ljson -lsmartconfig -lssl -lcrypto user/.output/eagle/debug/lib/libuser.a driver/.output/eagle/debug/lib/libdriver.a json/.output/eagle/debug/lib/libjson.a upgrade/.output/eagle/debug/lib/libupgrade.a platform/.output/eagle/debug/lib/libplatform.a libc/.output/eagle/debug/lib/liblibc.a lua/.output/eagle/debug/lib/liblua.a lwip/.output/eagle/debug/lib/liblwip.a coap/.output/eagle/debug/lib/coap.a mqtt/.output/eagle/debug/lib/mqtt.a u8glib/.output/eagle/debug/lib/u8glib.a ucglib/.output/eagle/debug/lib/ucglib.a smart/.output/eagle/debug/lib/smart.a wofs/.output/eagle/debug/lib/wofs.a spiffs/.output/eagle/debug/lib/spiffs.a cjson/.output/eagle/debug/lib/libcjson.a crypto/.output/eagle/debug/lib/libcrypto.a dhtlib/.output/eagle/debug/lib/libdhtlib.a tsl2561/.output/eagle/debug/lib/tsl2561lib.a modules/.output/eagle/debug/lib/libmodules.a -Wl,--end-group -lm -o .output/eagle/debug/image/eagle.app.v6.out 
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .output/eagle/debug/image/eagle.app.v6.out section `.irom0.text' will not fit in region `irom0_0_seg'
collect2: error: ld returned 1 exit status
make[1]: *** [.output/eagle/debug/image/eagle.app.v6.out] Error 1
make[1]: Leaving directory `/opt/nodemcu-firmware/app'
make: *** [.subdirs] Error 2
```

**user_modules.h**
```
...
#define LUA_USE_MODULES_NODE
#define LUA_USE_MODULES_FILE
#define LUA_USE_MODULES_GPIO
#define LUA_USE_MODULES_WIFI
#define LUA_USE_MODULES_NET
#define LUA_USE_MODULES_PWM
#define LUA_USE_MODULES_I2C
#define LUA_USE_MODULES_SPI
#define LUA_USE_MODULES_TMR
#define LUA_USE_MODULES_ADC
#define LUA_USE_MODULES_UART
#define LUA_USE_MODULES_OW
#define LUA_USE_MODULES_BIT
#define LUA_USE_MODULES_MQTT
#define LUA_USE_MODULES_COAP
#define LUA_USE_MODULES_U8G
#define LUA_USE_MODULES_WS2812
#define LUA_USE_MODULES_CJSON
#define LUA_USE_MODULES_CRYPTO
#define LUA_USE_MODULES_RC
#define LUA_USE_MODULES_DHT
#define LUA_USE_MODULES_WS2801
#define LUA_USE_MODULES_RTCMEM
#define LUA_USE_MODULES_RTCTIME
#define LUA_USE_MODULES_RTCFIFO
#define LUA_USE_MODULES_SNTP
#define LUA_USE_MODULES_BMP085
#define LUA_USE_MODULES_TSL2561
#define LUA_USE_MODULES_UCG
#define LUA_USE_MODULES_ENDUSER_SETUP
#define LUA_USE_MODULES_HX711
...
```
**user_config**
```
....
#define DEVELOP_VERSION
#ifdef DEVELOP_VERSION
#define NODE_DEBUG
#define COAP_DEBUG
#define BIT_RATE_DEFAULT BIT_RATE_74880
#else
#define BIT_RATE_DEFAULT BIT_RATE_9600
#endif /* DEVELOP_VERSION */
...
#define CLIENT_SSL_ENABLE
...
```

If I disable a few modules the build passes but the firmware crashes on startup.
**user_modules.h**
```
...
#ifndef LUA_CROSS_COMPILER
#define LUA_USE_MODULES_NODE
#define LUA_USE_MODULES_FILE
#define LUA_USE_MODULES_GPIO
#define LUA_USE_MODULES_WIFI
#define LUA_USE_MODULES_NET
#define LUA_USE_MODULES_PWM
#define LUA_USE_MODULES_I2C
#define LUA_USE_MODULES_SPI
#define LUA_USE_MODULES_TMR
#define LUA_USE_MODULES_ADC
#define LUA_USE_MODULES_UART
#define LUA_USE_MODULES_OW
#define LUA_USE_MODULES_BIT
#define LUA_USE_MODULES_MQTT
#define LUA_USE_MODULES_COAP
#define LUA_USE_MODULES_U8G
#define LUA_USE_MODULES_WS2812
#define LUA_USE_MODULES_CJSON
#define LUA_USE_MODULES_CRYPTO
#define LUA_USE_MODULES_RC
#define LUA_USE_MODULES_DHT
#define LUA_USE_MODULES_WS2801
#define LUA_USE_MODULES_RTCMEM
#define LUA_USE_MODULES_RTCTIME
#define LUA_USE_MODULES_RTCFIFO
#define LUA_USE_MODULES_SNTP
//#define LUA_USE_MODULES_BMP085
//#define LUA_USE_MODULES_TSL2561
//#define LUA_USE_MODULES_UCG
//#define LUA_USE_MODULES_ENDUSER_SETUP
//#define LUA_USE_MODULES_HX711
...
```

**Comment by TerryE** [comment]
Marcel,  I wondered why you were the only one reporting these issues, but as to "I feel like a total idiot": welcome to an illustrious club.  I've been there many times myself! :laughing:

Your point about Docker and Cloud builder is apt.  The ELF build is against Ubuntu 12.04.5 LTS (32bit) so this tarball can be used as a fast way of installing the toolchain on any such VM or appliance.  But in fact you only need  is a small subset of this to execute the make for the firmware.  Maybe I should update my "Build a VM" section of the esp8266.com wiki.

**Comment by TerryE** [comment]
I will also close this issue, since it's scope was to do the upgrade to the Espressif SDK 1.5, thugh I am sure that we will be opening other issues to sort out gremlins during the course of this Monday.   

Anyway, happy New Year to everyone tracking this repository!! :tada:

**Comment by marcelstoer** [comment]
> I am sure that we will be opening other issues to sort out gremlins

To be clear, do you want me to open a new issue about the crashing firmware configuration?

**Comment by TerryE** [comment]
Marcel, email me your mapfile.

**Comment by pjsg** [comment]
I just tried the new 1.5.0 version and it works fine for me. In particular, it seems faster, and also it increases the amount of available heap by 5k (from 15k to 20k in my app). This seems surprising... Any idea why?

**Comment by TerryE** [comment]
My LCD patch?

**Comment by pjsg** [comment]
There is a 2k boost as the heap_start moves down (in my build) by around 2k. This is *solely* due to merging 2f655de (which is the sdk1.5 merge commit). When I built this for the first time, I had to upgrade my docker image -- so I went back and rebuilt the old code with the new docker image, and the heap effect still shows up.

I.e. there is a 2k boost from the sdk (in esp_buf.o, the .bss requirement drops by 2k). The rest of the increase (i suspect) comes from a reduced memory requirement in the SDK for open network connections.

All in all, this is a good thing!

**Pull request merged**
