### PR TITLE
Update dht_lib.lua

### PR DESCRIPTION
**Pull request by iWladi**
misprint

### CODE REVIEW

**Comment by TerryE** [comment]
The way that Martin coded this seems peculiar to me, but to your specific correction, this does seem to be a cut and paste error.

**Comment by marcelstoer** [comment]
Why was this merged to `master` rather than `dev`?

**Comment by TerryE** [comment]
Because I am a prat :oops:

**Comment by TerryE** [comment]
This is now dead. See #789

**Pull request merged**
