### PR TITLE
Change HTTP failures from debug to error messages

### LINKED ISSUE #1546: HTTP request with "large" response body fails or resets device
This is a follow-up to #1485 and a more-to-the-point description of #1545. Seems like a serious regression bug in the HTTP module or some SDK characteristic the HTTP module relies upon.

### Expected behavior
HTTP GET to an HTTP resource should return the HTTP resource.

### Actual behavior
Depending on the response size (I believe) this either works, fails or resets the device.

### Test code
```Lua
http.get("http://nodemcu-build.com", nil, function(code, data)
  if (code < 0) then
    print("HTTP request failed")
  else
    print(code, data)
  end
end)
```
- http://frightanic.com/jquery-highlight.js ✅ , 2.7 KB
- http://frightanic.com 🔴 , 17.7 KB
- http://nodemcu-build.com 🔴 ♻️ , 6.6 KB
- http://nodemcu-build.com/about.php 🔴 ♻️ , 2.8 KB
- http://nodemcu-build.com/jumbotron-narrow.css ✅ , 433 B
- http://www.google.com, 🔴 , 66.9 KB
- http://clients5.google.com/pagead/drt/dn/, ✅ , 270 B
- http://httpbin.org 🔴 , 12.1 KB
- http://httpbin.org/get ✅ , 798 B

🔴 : fails
♻️ : reset

### NodeMCU version
Current `master` and `dev` with SDK 1.5.4.1. According to #1545 this worked fine with 1.5.1. Did the SDK used to buffer responses in earlier versions?

### Hardware
NodeMCU devkit 1.0.

### PR DESCRIPTION
**Pull request by marcelstoer**
Addendum to #1558, fixes #1546

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.

### CODE REVIEW

**Comment by devsaurus** [comment]
I think this is the right thing to do.

How about adding a tag to immediately understand where the messages come from? Like in
```c
#define HTTPCLIENT_TAG "http client"

NODE_ERR( "%s: Response too long (%d)\n", HTTPCLIENT_TAG, new_size );
```

**Comment by marcelstoer** [comment]
Good idea, thanks. Fixed.

**Comment by dnc40085** [comment]
>I wouldn't know how to do that in C

A macro should help you do what you are trying to accomplish
```c
#define HTTPCLIENT_DBG(fmt, ...) NODE_ERR("\n\tHTTP client:"fmt"\n",  __VA_ARGS__)

//example
HTTPCLIENT_DBG("Response too long (%d)", new_size)

//Output
    HTTP client:Response too long (9001)
```

**Comment by marcelstoer** [comment]
Thanks, fixed that as well. Once I started implementing the changes I realized I could, and should, have noticed that `HTTPCLIENT_DEBUG` works exactly like that, sorry.

- I improved `HTTPCLIENT_DEBUG` slightly so that it behaves the same as `HTTPCLIENT_ERR` in terms of newline handling.
- I didn't squash my commits as whoever merges this can do that right here in the web UI.

**Pull request merged**
