### PR TITLE
WIP Mahony AHRS filter

### PR DESCRIPTION
**Pull request by hiperiondev**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [ ] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/en/*`.

\<Description of and rationale behind this PR\>
Add Mahony AHRS filter.
Need to be tested with magnetometer (like Mpu9250). Only tested with MPU6050.
Still not have documentation

### CODE REVIEW

**Comment by marcelstoer** [comment]
Could the experts @devsaurus @jmattsson @pjsg @TerryE maybe give this a quick glance to assess whether it's worth pursuing?

@hiperiondev not sure if you noticed that CI failed: https://travis-ci.org/nodemcu/nodemcu-firmware/builds/451689258

**Comment by hiperiondev** [comment]
Mahony filter and MPU6050 driver are my first includes in nodemcu-firmware.
I'm still understanding the all project.
I have experience in work in plain C projects for microcontrolers but I want to experiment on a fast prototipe architecture. I think nodemcu/lua is a very good approach
The next week I'll have an Mpu9250 to test the driver with Mahony and Madgwick filters for a personal project (next I'll use Ad8232 for another project).
My intention is share all my code to the nodemcu-firmware project.
All comments will be appreciated

**Comment by dadosutter** [comment]
My "comment" is a simple Thank You for your contributions.

Dado Sutter

**Comment by nwf** [comment]
Looking at the MPU-60X0 data sheet, I think its I2C driver is better provided in Lua than in C.  It does not appear to need any sensitive timing behavior or complex math on the host, and the less we have running in C, the better, IMHO.  The filter may still merit being in C for numerical performance reasons, tho'.

**Comment by devsaurus** [comment]
> Could the experts ... maybe give this a quick glance to assess whether it's worth pursuing?

Personally, I'm missing the background for the mentioned filter topics, thus it's hard to provide constructive feedback at this point.

@hiperiondev please roughly outline the use case for a Mahony filter. Since you've also mentioned Madgwick filter, do you intend to add further filter types in the future?

**Comment by TerryE** [comment]
I have a number of implementation comments, but we are doing this all in the wrong order.  As far as I know the Mahony AHRS in only one component of an inertial measurement system implementation and isn't really usable without (for example) a decent matrix library support covering 3×1 and 3×3 matrix operations including addition multiplication and inversion.  If this going to be done in C or Lua?  

How performant is this library going to be?  Is it going to run fast enough on an 8266 platform?  There are wider issues that we should first discuss and resolve before we get into detailed implementation.  First raise the feature request and once this has been broadly agreed, then the PR.

**Comment by TerryE** [comment]
@hiperiondev Hi Hyperión.  I didn't explain myself well, and I guess from your location that English is a second language for you :smile: Having the pull request (PR) is very useful, but if you reread the template, we normally raise an issue first and discuss requirements and objectives first to try to get a good understanding of the objectives for and goals of a new library, because if we add it to our distribution and you move onto other work then the core team will still need to support it.

So for example take Nathaniel's point that it would be a lot easier and just as fast to handle the I2C interface as a Lua module.  I did some research on this before I replied and from previous experience I am familiar with matrix calcs, quaternions, MLE and Kalman filter -- the maths stuff but what I want to understand is what advantage is there to us adding this to our libraries.  The code itself is a secondary issue.  The MPU9250 driver and the Madewick filter are only part of the jigsaw.  We need understand the whole picture to be able to move forward.

**Comment by hiperiondev** [comment]
TerryE: To say that English is my second language is very optimist, I know is very ugly! My project need to measure the position of an object and generate an alarm when is in a position, or make  some movement (or acceleration) that put it in a falling danger.
I don't know if a pure lua project can deal with this requirements .

**Pull request closed without merging**
