### PR TITLE
Switch to SDK downloading + replacement libmain.a for timer fix

### PR DESCRIPTION
**Pull request by jmattsson**
Just in case it is wanted, here's a branch for the replacement libmain.a to address the timer issue in #907. Given earlier discussion about the -dl branch, I shifted the SDK zip to be downloaded as well as the replacement libmain.a zip. I didn't want to add more binaries to the repo unnecessarily...

If the final call is to not use the replacement libmain, just close this PR :)

### CODE REVIEW

**Comment by TerryE** [comment]
To download or not to download, that is the question. 

With a retry count of 20, and caching this should be pretty resilient. I haven't tried this but what happens if the 20th retry download is short rather than a total failure?  Won't we get into a latched failure where we have a short tarball in the cache? Should we do the wget if the tarball doesn't exist _or_ is too short? That way retrying a failed download should recover. This should address Marcel's resillience concerns. 

I know others have stronger views on this.

My only other comment is that if we agree on the dl approach then I would do the same for the esp-open-sdk.tar.gz tarball, but this is pretty low priority so doesn't need to be done now.

**Comment by marcelstoer** [comment]
> Should we do the wget if the tarball doesn't exist *or* is too short?

+1

**Comment by jmattsson** [comment]
Does wget leave short files in place? I can easily add a `|| { rm -f $@; exit 1; }` to guard against that. Automatically re-downloading would take a bit more make file logic that I'm not sure would be worth it vs just having to re-run make. I can have a play tonight if you want (subject to time availability).

**Comment by TerryE** [comment]
Just thinking about this, the main reason for the brown outs on download is that we are downloading the SDKs from **bbs.espressif.com** through the CN firewalls. This would be a lot faster and resilient if we used a github dedicated user account to hold these zips.

**Comment by marcelstoer** [comment]
Those are valid concerns but to me this discussion is getting a bit absurd. Why would you *not* want to use Git submodules but then go to great length to manually build something reliable and resilient that (in essence) is not too different from what Git would do?

**Comment by jmattsson** [comment]
Because a sub module is a complete git repository, so you would end up with all the historical versions, for good and bad. And if we want that, we might as well just stick with keeping it all in this repo.

**Comment by marcelstoer** [comment]
Riiight :flushed:.. and that's where the debate started, you want to reduce the amount of data pulled from where ever.
There's no way to tell Git to only clone revision X of a sub module, that's true. If we picked up Terry's suggestion of a dedicated GitHub repo we could still do `git clone --depth 1 --branch <SDK-version> <repo>` to reduce amount data to transfer. I suspect, but haven't tested, that using `git` over `wget`/`curl` would get us better stability as Git should ensure consistency of its operations.

**Comment by jmattsson** [comment]
SDK 1.5.1 was [just released](http://bbs.espressif.com/viewtopic.php?f=46&t=1609) but it doesn't appear to have the timer fix. Either that or they copy/pasted the wrong fix description. I'll follow up with Espressif; I'd say hold off merging this for now at least.

**Comment by jmattsson** [comment]
Gah, I forgot to post the follow up earlier. Alright, so the timer fix isn't in 1.5.1, which pretty much gives us three options:
  1. Use this PR and fix a reported issue in NodeMCU right away.
  1. Upgrade to 1.5.1 and get those improvements but leave the reported issue outstanding.
  1. Refuse to pick one of those and instead wait for SDK 1.5.2 or 1.6.0.

All have merit. Suggestions?

**Comment by TerryE** [comment]
IMO, In the great scheme of things, it makes little difference whether the maximum period is 30 odd minutes, 60 odd minutes or somewhere in between.  The overall epoch is the same and it's not days, so if you are waiting on ToD then you are going to have to use a timer loop and it makes bugger all difference in terms of power consumption or coding complexity whether you wake up every 30 mins or 60 mins to count down.  

I suggest that you either toss a coin or do the easiest for you.  We've got far higher priority stuff to worry about.

**Pull request closed without merging**
