### PR TITLE
Update ESP-IDF to v3.3

### PR DESCRIPTION
**Pull request by marcelstoer**
When @jmattsson last upgraded ESP-IDF in #2805 it was done so against whatever version happened to be the latest in their [v3.3 branch](https://github.com/espressif/esp-idf/tree/release/v3.3) (I believe). They have since created a 3.3-RC. It makes IMO sense to stick to tagged / released version unless there are compelling reasons not to do so. #2805 might have been such a case.

This PR updates IDF to ~~3.3-RC~~v3.3.

### CODE REVIEW

**Comment by jmattsson** [comment]
Sounds good to me. I was holding out for a 3.3.0 before I was going to do a PR, but I'm quite happy to step via 3.3-RC too.

And yes, definitely prefer to be on tagged versions. Last paragraph in #2805 explains why I couldn't do so at the time.

**Comment by marcelstoer** [comment]
> Sounds good to me.

Cool. Is the fact that you didn't merge yet an indication that you are waiting for more feedback from e.g. @devsaurus?

**Comment by jmattsson** [comment]
More that I haven't had a chance to test it!

**Comment by jmattsson** [comment]
IDF 3.3 release just dropped, should probably update to that?

**Comment by marcelstoer** [comment]
Done. It's great to see they're adopting an LTS model.

**Comment by marcelstoer** [comment]
@chilipeppr @jmattsson does one of you by any chance already code against IDF v3.3?

**Comment by chilipeppr** [comment]
No, I have not.

**Comment by jmattsson** [comment]
I haven't had a chance to test anything later than the beta, sorry. $work is keeping me _very_ busy with other things at the moment :(

**Comment by marcelstoer** [comment]
Guess I need to update this again: https://github.com/espressif/esp-idf/releases/tag/v3.3.1

**Comment by marcelstoer** [comment]
I'm merging this now to give the community a chance to work it.

**Pull request merged**
