### PR TITLE
Add HTTP client module and documents.

### PR DESCRIPTION
**Pull request by vowstar**
HTTP client Demo code
```lua
-- Support HTTP and HTTPS, For example
-- HTTP POST Example with JSON header and body
http.post("http://yourtesting.url/",
           "Content-Type: application/json\r\n", 
           "{\"hello\":\"world\"}", 
            function(code, data) 
                print(code) 
                print(data) 
            end)
-- HTTPS GET Example with NULL header
http.get("https://www.vowstar.com/nodemcu/","",
            function(code, data) 
                print(code) 
                print(data) 
            end)
-- You will get
-- > 200 
-- hello nodemcu
-- HTTPS DELETE Example with NULL header and body
http.delete("https://10.0.0.2:443","","",
            function(code, data) 
                print(code) 
                print(data) 
            end)
-- HTTPS PUT Example with NULL header and body
http.put("https://testput.somewhere/somewhereyouput.php","","",
            function(code, data) 
                print(code) 
                print(data) 
            end)
-- HTTP RAW Request Example, use more HTTP/HTTPS request method
http.request("http://www.apple.com:80/library/test/success.html","GET","","",
            function(code, data) 
                print(code) 
                print(data) 
            end)

```
Please try!  :)

### CODE REVIEW

**Comment by TerryE** [comment]
Hi. I am not sure what is happening here with the other 32 commits. It may be that I screed up something in my rebaselining. Let me check.

**Comment by vowstar** [comment]
@TerryE  I have remove all version information including how http module is build, and combine all commits to 1 now.

https://github.com/nodemcu/nodemcu-firmware/pull/887

**Comment by vowstar** [comment]
@TerryE 25af2b9 d34ac77 50dcea3 is discarded by 5b6acee, from 0380e49 to 0c8e1a2 is the process to build http module.

**Comment by TerryE** [comment]
@vowstar I am just trying to get our SDK 1.5-based `dev` stable.  Do you mind if we delay merging in this for a few days?  Doing both of these at the same time will get really confusing.  Sorry to inconvenience you.  Terry :sweat:

**Comment by vowstar** [comment]
Hi @TerryE I'm very understand, it doesn't matter, SDK 1.5 is a big change, all push request may pending until 1.5 done.

**Comment by marcelstoer** [comment]
> I have remove all version information including how http module is build, and combine all commits to 1 now.

So, this can be closed in favor of #887, right?

**Comment by TerryE** [comment]
#887 is a rebase and commit so only shows the cone commit, but we need to go through this carefully.  However, since these has been superseded by #887, I fell that we can close this multipe-commit anologue.

**Pull request closed without merging**
