### PR TITLE
Removing large number of #defines from Makefile and push them to a separate file

### LINKED ISSUE #1863: sqlite3 support
I did a port of sqlite3 to nodemcu and would like to know if it would be interesting to the nodemcu community too.
The motivation was that I am about to build an access control system using RFIDs tags that would depend on a database with allowed tags and keys built on a pc or on a pi 3 or beagle bb. This database would be broadcasted to nodemcus via a secured connection over wifi using ssl or something like that.
The first thing I needed was to first enable nodemcu to work with sqlite3 databases and this is what I got.
This patch is based on sqlite3 (of course) and luasqlite3 (half way there) with a esp8266 sqlite3 vfs developed by me.

Would this patch be of interest of nodemcu community?

### PR DESCRIPTION
**Pull request by luizfeliperj**
Fixes #1863 ("Feature enhancement").

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [X] This PR is for the `dev` branch rather than for `master`.
- [X] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [X] I have thoroughly tested my contribution.
- [X] The code changes are reflected in the documentation at `docs/en/*`.

This pull request removes logs of defines from inside the makefile and pushes them into a separated file. This file is sources by the compiles by a flag that forces its inclusion on all source files within sqlite3 directory (-include config_ext.h).

### CODE REVIEW

**Comment by TerryE** [comment]
Why is  SQLITE _DEFAULT_ LOOKASIDE 125×512? That's more RAM then we have on the ESP. Have you any non-trivial Lua application where SQLite is working?

**Comment by luizfeliperj** [comment]
This is 125 x 512 bytes which is 64kb, doesn't the ESP specs RAM as 80Kib?
Anyway, it is really too big, what would be the best configuration for the lookaside?

**Comment by TerryE** [comment]
> what would be the best configuration for the lookaside?

Luiz, if you do a `node.heap()`  on a virgin restarted ESP them you will typically see that you have 40-44Kb total RAM available.  Yes there is more RAM but some of this is used as a ROM bootstrap an ISRs, the SDK and a smaller amount for the core NodeMCU firmware.   You should really get SQLite3 working with a non-trivial application before you raise a PR.  Getting to a clean compile means nothing.

**Comment by luizfeliperj** [comment]
@TerryE Never hit this limit, I did no tests using a ten of kilobytes large database. The library use should be kept trivial otherwise one would blow the time limit for the callback, because "The SDK states that if any tasks run for more than 15 mSec, then services such as WiFi can fail.", according to the NodeMCU docs.

I submitted the PR because others shown interest in it, having a broader audience helps fixing the problems we may face.

**Comment by TerryE** [comment]
@luizfeliperj, I think that you miss my point.  The FS on a ESP8266 can be up to 4Mb, so their may be applications where SQLite3 is relevant. It's just that my initial reaction was that I couldn't see how anyone could get this working for a chip will so little memory. A full relational DB seemed unrealistic.  However, others think differently so I accept this as a consensus.  But this isn't an academic exercise.  If the orginal developer hasn't got it working an a real-life application which needs / uses it and reasonably stress tested it, then all that will happen is that when some other Lua (not C) developer tires to build her or his application using the library then we will get issues raised: "I can't get this to work".  Can you fix it?  And by then you may have lost interest in ESP8266s as a project and we have to respond.

So this has work robustly for a reasonable set of usecases that it might be used in.  Or we can't distribute it.

**Comment by TerryE** [comment]
@luizfeliperj Luìz, I will merge this as it improved the make and does not impact the implementation otherwise. But see my new issue which I will just open

**Pull request merged**
