### PR TITLE
update tabs to spaces

### PR DESCRIPTION
**Pull request by ffedoroff**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [X] This PR is for the `dev` branch rather than for `master`.
- [X] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [X] I have thoroughly tested my contribution.
- [X] The code changes are reflected in the documentation at `docs/en/*`.

\<Description of and rational behind this PR\>

### CODE REVIEW

**Comment by devsaurus** [comment]
Thanks @ffedoroff
There are further tabs in `platform_gpio_register_intr_hook()`, may I ask you to cover them in this PR as well? Then we're good to go.

**Comment by marcelstoer** [comment]
It's good to fix that but it's just a drop in the ocean 🙁  Relates to #1168 that I said I would tackle at some point.

**Comment by marcelstoer** [comment]
I removed the 2.0.0 milestone as we're past the two-weeks-before-master-drop milestone.

**Comment by marcelstoer** [comment]
No feedback from author in a long time -> closing

**Pull request closed without merging**
