### PR TITLE
Remove sqlite3 module

### PR DESCRIPTION
**Pull request by nwf**
It's not clear that this ever worked, AFAICT nobody uses it, and it's an old version of the sqlite3 engine at this point.  Absent a maintainer, let's just get rid of it after this `master` cuts (#3066).

"Fixes" #2913 and #2300

### CODE REVIEW

**Comment by TerryE** [comment]
If none of the other committers objects strongly, then I'll merge this in a day or so.

**Comment by nwf** [comment]
How about we cut `master` (and close #3066) and then merge this?  Gives us time to back it out if someone does object.

**Comment by TerryE** [comment]
I feel that I need to do some extra work checking out telnet and FTP server against Dev before we cut to master, and I also feel that this and the cut to master are independent issues.

**Comment by HHHartmann** [comment]
I would also want to wait til after the master cut. That way we have our discontinuation note in the docs for one cycle. 
OTOH nobody really seems to miss it really.

**Comment by marcelstoer** [comment]
> I feel that I need to do some extra work checking out telnet and FTP server against Dev before we cut to master

👍 

> I would also want to wait til after the master cut.

👍

**Comment by marcelstoer** [comment]
Missing: removal of `sqlite3.md` from `mkdocs.yml`. Now fixed.

**Pull request merged**
