### PR TITLE
Add http.put()

### LINKED ISSUE #3456: ESP32 http module miss PUT
### http module miss PUT
why miss PUT?

### Justification
We need PUT to upload objects to the Object Storage Service

### Workarounds
POST works, but it will take more time to convert the object to the "POST" format

### PR DESCRIPTION
**Pull request by marcelstoer**
Fixes #3456.

- [x] This PR is for the `dev-esp32` branch rather than for the `release` branch.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

@jmattsson @tomsci I've had this laying around for quite some time and was wondering if you'd support adding it.

### CODE REVIEW

**Comment by tomsci** [comment]
Seems like a beneficial change. My only concern would be about removing the `setpostdata()` API. Should we also expose `http_lapi_setbody` as `setpostdata` in `http_context` to maintain compatibility?

**Comment by marcelstoer** [comment]
@tomsci I briefly considered this before putting up the PR but decided against it for two reasons
- `setpostdata()` also set the method to POST; `setbody()` doesn't. Hence, we'd either have a breaking change anyway or we'd somehow have to iron this out.
- `dev-esp32` has always been a development branch without any guarantees as for API stability. That doesn't mean we should carelessly break APIs but IMO we don't have to be as strict as on the `release` branch.

**Review by jmattsson — COMMENTED** [review]
Seems like a good change to make. I don't see a clear/good way of keeping backwards compatibility though, so should we consider merging this only onto the idf4 branch, since we already have breaking changes there?

**Comment by marcelstoer** [comment]
> should we consider merging this only onto the idf4 branch, since we already have breaking changes there?

Sounds good to me.

**Comment by marcelstoer** [comment]
> merging this only onto the idf4 branch

Ok, I changed the base branch. Will resolve the conflicts now.

**Comment by jmattsson** [comment]
Merged, thanks. Am I good to remove the feat/http-put branch?

**Comment by jmattsson** [comment]
Dear heavens now everything broke when I merged that?! But it showed all green for the merge?! Aaaah!
I can't reproduce the build failure locally. @marcelstoer help, please? 😢

**Comment by marcelstoer** [comment]
Well, you couldn't have merged if the PR build hadn't succeeded. Here's that build: https://github.com/nodemcu/nodemcu-firmware/runs/3668105377 - I won't touch it as it's green now 😜 

I'll take a look at the others.

**Comment by marcelstoer** [comment]
https://github.com/nodemcu/nodemcu-firmware/runs/3798787408#step:10:1249
> gen_crt_bundle.py: Invalid certificate in /home/runner/work/nodemcu-firmware/nodemcu-firmware/sdk/esp32-esp-idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem
Invalid certificate

May have to bump the IDF again?

**Comment by jmattsson** [comment]
I considered it, but since the build isn't failing for me locally I'm wondering if the test runner host(s) aren't getting their time set properly for some reason all of a sudden?

**Comment by marcelstoer** [comment]
> the build isn't failing for me locally

Right, you said so. Sorry I forgot.

> aren't getting their time set properly

That would certainly explain it. https://www.githubstatus.com/ isn't aware (yet) of any issues with the runners.

We could temporarily add a few debugging commands to the build script. I assume you inspected `cacrt_all.pem` locally and found it to be valid, right?

**Comment by jmattsson** [comment]
> I assume you inspected cacrt_all.pem locally and found it to be valid, right?

Only in so far that a `make clean; make` did not have it complain about it being invalid.

I also re-ran the github actions on one of my own branches, which had previously also been a fully green build, and it went all red on the re-run.

Please be my guest and see if you can find a workaround for this issue; I'm a bit occupied with other $work bits at the moment. I just thought I'd sneak in the re-review/merge of this PR before I had to get stuck into $work...

**Comment by marcelstoer** [comment]
I addressed this with 32f66e3 but I wasn't (and still am not) sure whether pinning the cryptography version was more appropriate for our project than putting `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=n` into `sdkconfig.defaults`.

**Pull request merged**
