### PR TITLE
ESP32: uart 1/2 supports

### LINKED ISSUE #1960: ESP32: uart1/uart2 support
I'm adding uart1/uart2 support to uart module. I noticed there had been some code for more uart(s) in `platform.c` and `platform.h` . So I tried to do it in the way expected...

I added `start()` and `stop()` functions, and changed signature of `on()` and `setup()`. Docs is updated [here](https://github.com/zelll/nodemcu-firmware/blob/dev-esp32-uart12/docs/en/modules/uart.md).
> uart.on(**[id],** method, [number/end_char], [function], [run_input])
> uart.setup(id, baud, databits, parity, stopbits, **echo_or_pins**)

@jmattsson Can you review it? 
https://github.com/zelll/nodemcu-firmware/tree/dev-esp32-uart12

### PR DESCRIPTION
**Pull request by zelll**
Fixes #1960.

- [x] This PR is for the `dev-esp32` branch.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

Added non-console UARTs (uart1 & uart2 when console is uart0, or uart0 & uart2 when console is uart1) to `uart` module.

Docs: [uart.md](https://github.com/zelll/nodemcu-firmware/blob/dev-esp32-uart12/docs/en/modules/uart.md)

### CODE REVIEW

**Comment by joysfera** [comment]
I have tested this patch with uart(1) and uart(2), on pins 16/17 and 23/22. It sort of works but not 100 %, on my particular hardware setup (an old dev board talking to a picky HW peripheral). Did you test it on various GPIO pins with better luck?

**Comment by zelll** [comment]
@joysfera Sorry, I made a mistake in last minutes before committing and did not flash/test since then... :(
Can you test the latest code on your hardware? It should work now. I tried 16/17, 23/22 and a few other pins on my esp32 module.

**Comment by joysfera** [comment]
@zelll I have applied the two new commits and now I'm getting this error:
```lua
> uart.setup(1, 9600, 8, uart.PARITY_NONE, uart.STOPBITS_1, { tx = 17, rx = 16 })
uart.setup(1, 9600, 8, uart.PARITY_NONE, uart.STOPBITS_1, { tx = 17, rx = 16 })
E (72042) uart: uart_set_line_inverse(194): inverse_mask error
```
This line of code worked before.

**Comment by zelll** [comment]
@joysfera 
Function `uart_set_line_inverse()` in IDF does not accept inverse_mask `0`. I opened a issue https://github.com/espressif/esp-idf/issues/673 . Before it is resolved, you can remove ` && (inverse_mask != 0)` from file `sdk/esp32-esp-idf/components/driver/uart.c`. (Or just ignore the error... LUA should work although IDF prints that error)

**Comment by joysfera** [comment]
@zelll it's working, thank you!

Guys, please merge this PR, it's a great addition to dev-esp32. Thanks.

**Comment by jmattsson** [comment]
I'm not currently in a position to review this, so don't let me hold it up :)

**Pull request merged**
