### PR TITLE
Next master drop

### PR DESCRIPTION
**Pull request by marcelstoer**
https://github.com/nodemcu/nodemcu-firmware/milestone/13?closed=1

I actually hope we can resolve https://github.com/nodemcu/nodemcu-firmware/pull/2830#discussion_r312716630 before we merge this.

### CODE REVIEW

**Comment by marcelstoer** [comment]
I see that when @nwf merged #2830 he didn't use a GitHub's "squash & merge" but a regular fast-forward merge. Hence, the history contains @HHHartmann's "intermediary" commits as well. Anyone feel free to manually squash those commits if this bothers you. It personally doesn't bother me enough to do that.

**Comment by nwf** [comment]
Whoops, sorry.

**Comment by marcelstoer** [comment]
Nobody interested in moving on and creating that release? I won't merge my own PR 😉

**Comment by TerryE** [comment]
Why not follow my precedent? 🤣

If not then the honour should go to @nwf

**Comment by TerryE** [comment]
@marcelstoer, I am not sure why there is a great reluctance on the part of the other committers to push the go button on this, but I need to move forward with dev, so I have done this myself.

I hope that you are happy with this.  //Terry

**Comment by TerryE** [comment]
@marcelstoer, can I leave preparing the release to you?  I have my hands rather full at the moment with Lua 5.3

**Pull request merged**
