### PR TITLE
Create PCD8544.c

### PR DESCRIPTION
**Pull request by aguaviva**
Quick and simple module to drive a pcd8544 without needing the ug8.

More info here: http://codinglab.blogspot.be/2015/06/simple-nodemcu-module-to-drive-nokia.html

Also note that i wrote a lua module to drive the display, although it works it takes too much mem.

### CODE REVIEW

**Comment by marcelstoer** [comment]
I don't think this should be added to the firmware for the following reasons:
- it's not (yet) a proper module that can be turned on/off in `app/include/user_modules.h`
- the pins are not configurable
- I'd argue that the use case (pcd8544) is too specific

**Comment by aguaviva** [comment]
I can add the missing files app/include/user_modules.h and make the pins configurable, no problem.

As for the pcd8544 (Nokia5110) LCD, these babies are everywhere and cost about 2 dollars. 

How about I add the missing files, and then we let the users decide through frightanic?

**Comment by marcelstoer** [comment]
> How about I add the missing files, and then we let the users decide

I guess this is more of a general question that should be answered by @vowstar or @MarsTechHAN. Should the firmware provide "bindings" (of some sort) for widely used input/output components? If so, when is a component considered "widely used"? 

In issue #394, adding support for the MAX7219 8x8 LED matrix, I raised this issue before.

**Comment by aguaviva** [comment]
Understood. Ideally I'd like nodemcu to support as many I/O componets as possible (provided I can disable them in the build). The same thing happens in the linux kernel, you have a mainstream build that has most of the stuff people need, and you can also optimize/customize it by removing/adding the bits you don't need.

**Comment by MarsTechHAN** [comment]
We can just add them to he code, and defualtly turn it off. So the guys who use it can turn it on...How about this?

**Comment by MarsTechHAN** [comment]
As for I myself, I will agree to add that modules. I believe the best way is defaultly turn it off, and for some one who needs it, he can open that. And the coming ACC (auto cloud compileing) system can solve it, by just opening the modules the users will use...

Many moudles like ws2812, dht, rc, crypto...lib someone may dont need them, but default lib turn tem on, which I believe is a bad idea.

As a conclusion, more lib? Absolutely yes. But remember to turn them off by default, and as marcelstoer saying
- [ ] Add turned on/off function in app/include/user_modules.h (And default close)
- [ ] Make the pins configurable

**Comment by aguaviva** [comment]
Agreed! I'll be glad to make those changes.

**Comment by MarsTechHAN** [comment]
I cannot decide it, the user of NodeMCU will decide it...both 8544 and 7219 are useful(At least for me) for someone and that's enough. Dont cause problem for others and make the user feel right, that's enough.

**Comment by vowstar** [comment]
Thank you very much, and we will help modify it after merge, we will make it can be turned on/off in app/include/user_modules.h and pins are configurable. Welcome every PR!

**Comment by dvv** [comment]
Wonder if it is feasible to take frankenstein code and build system and salt it with just Lua interpreter?

**Comment by vowstar** [comment]
May be using jmattsson's code https://github.com/nodemcu/nodemcu-firmware/pull/504 very possible ;)

**Comment by vowstar** [comment]
Web build service is useful, if possible we will develop a local build tool and let user choose what modules on/off, just like linux kernel.

**Comment by aguaviva** [comment]
awesome!

**Comment by goliatone** [comment]
is this going to get merged?

**Comment by jmattsson** [comment]
Will this PR see the requested updates as requested, or should I close this for now?

**Comment by marcelstoer** [comment]
@aguaviva hasn't responded to last request over a month ago. I'm, therefore, closing this PR.

**Pull request closed without merging**
