### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nailujx86**
Fixes no issue.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

\<Description of and rationale behind this PR\>
Updated the percentage of C-Code used in the firmware.

### CODE REVIEW

**Comment by TerryE** [comment]
Why?  I am not sure why the original overview left out 1.9% as non-C what is this? the Makefiles? The loader files? All of the source in the firmware is C, and the small amount of assembler is embedded in C sources using the `asm()` directive.  We don't use any other high level language in the firmware, though we do have some host-side python.

**Comment by marcelstoer** [comment]
>  I am not sure why the original overview left out 1.9% as non-C what is this? the Makefiles? The loader files?

It's just what GitHub reports if you click that color bar (which in our case isn't that colored at all).
screen shot 2018-06-15 at 13 58 27

**Comment by TerryE** [comment]
Thanks @marcelstoer, but this is also misleading as the Lua is the Lua examples which are not part of the firmware, and the Python is the host-end `esptool.py`.  Not sure where the C++ is as we don't have any .cpp files in the app, though some of the headers are "bilingual" in that they are designed to be included in C++ source as sell as C and may have been therefore classified as C++; so the real % is 100% C.

**Comment by marcelstoer** [comment]
Well, that whole sentence isn't particularly helpful

> The code repository consists of 98.6% C-code that glues the thin Lua veneer to the SDK.

**Comment by TerryE** [comment]
Closing this; see #2418.   Thanks @nailujx86  Julian.  :smile:

**Pull request closed without merging**
