### PR TITLE
Added full support for DS3231

### PR DESCRIPTION
**Pull request by Takkuz**
Added many new functions for full supporting DS3231 RTC.

### CODE REVIEW

**Comment by pastukhov** [comment]
Great!

**Comment by nickandrew** [comment]
I have no way to test this, but it looks like a nice piece of work.

**Comment by Takkuz** [comment]
Thank you @nickandrew... I've fixed those errors.

**Comment by theopensourcerer** [comment]
Could this also be used to wake the ESP8266 from Deep Sleep? I am thinking about using one of these devices as I want to use a cycle time longer than ~70mins I can configure directly in the ESP?

**Comment by Takkuz** [comment]
@theopensourcerer I tried, but the NodeMCU needs a pulse on GPIO0. When it's in deep sleep if you set GPIO0 to LOW it wakes up but doesn't boot until setted to HIGH again. DS3231 sets the pin to LOW until reloaded, so it keeps the NodeMCU in a state of useless coma. You need a phisical circuit that cut the link after a while. I found it but I can't remember it's name.

**Comment by theopensourcerer** [comment]
@Takkuz Thanks for the reply. 

So it seems as though technically it might be possible but perhaps some kind of Monostable is required in between... i will do some more investigations.

**Pull request merged**
