### PR TITLE
Delete esptool.py

### PR DESCRIPTION
**Pull request by marcelstoer**
I really don't think it makes much sense to host a replica of `esptool.py` in this repository. As #594 showed once again it isn't efficient if bugs have to be fixed/PR'ed in two repositories. We had problems with this not too long ago with the DIO issue (#523 and https://github.com/themadinventor/esptool/issues/40).

### CODE REVIEW

**Comment by zerog2k** [comment]
Should it be a git submodule reference to the other project instead?
This should ensure that any dependency projects are pulled in.

**Comment by marcelstoer** [comment]
Ouch, just burned myself badly. Sorry, I spoke too soon. I didn't realize the makefile depends on this.

> ../tools/esptool.py elf2image .output/eagle/debug/image/eagle.app.v6.out -o ../bin/

How to best go about this?

**Comment by marcelstoer** [comment]
> Should it be a git submodule reference to the other project instead?

Yeah, that sounds like a reasonable plan:
- add the `themadinventor/esptool` repository as a submodule into the `/tools` folder
- add the following commands to the makefile to make sure people can still just clone this repo and start the build (rather than using a variation of `git clone` which also inits submodules):
 - `cd tools/esptool`
 - `git submodule init`
 - `git submodule update`

Ok?

**Comment by zerog2k** [comment]
Looks like it might work. I can checkout your branch and test it out.

If nodemcu repo starts using submodule (which is the right way to depend on other projects), may also want to update some of the docs/readmes, e.g.,:
1. initial repo clone should include --recursive command
2. updating/rebuilding will need some submodule update (i think?)

Fine examples from esp-open-sdk:
https://github.com/pfalcon/esp-open-sdk

**Comment by marcelstoer** [comment]
> 1. initial repo clone should include --recursive command

Assumption I: you only need `esptool.py` if you want to build the firmware (and for flashing of course). 
Assumption II: if you flash with `esptool.py` rather than any other flashing tool you download a copy independently of the NodeMCU binaries i.e. it can/should be decoupled from this firmware.

IMO there's no need to clone with `--recursive`. My intention was to keep as much as possible as-is. People building the firmware themselves shouldn't notice `esptool.py` is no longer replicated in this repository. That's why I proposed to add `git submodule init/update` to the makefile.

**Comment by jmattsson** [comment]
The problem I see is that upstream esptool.py can be really slow to merge in fixes (such as the DIO, or lately the SPIEraseArea bug stuff). Perhaps more importantly, there was also no guarantee that we'd get the entrypoint change into upstream, yet that change was what made it possible for me to kick the constants out of RAM into ROM. At this point I'm somewhat hesitant to give up the control that having our own esptool.py brings. Just my opinion, of course.

**Comment by marcelstoer** [comment]
> The problem I see is that upstream esptool.py can be really slow to merge in fixes

Yeah, I also noticed...see https://github.com/nodemcu/nodemcu-firmware/issues/594#issuecomment-129601586

**Comment by devsaurus** [comment]
> Assumption I: you only need esptool.py if you want to build the firmware (and for flashing of course).
> Assumption II: if you flash with esptool.py rather than any other flashing tool you download a copy independently of the NodeMCU binaries i.e. it can/should be decoupled from this firmware.

> Perhaps more importantly, there was also no guarantee that we'd get the entrypoint change into upstream.

I agree with @marcelstoer and @jmattsson. We're facing the fact that esptool is dual-purpose (not a good approach IMO, [dotadiw](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)).

nodemcu firmware is quite innovative on the compile-time features and has specific requirements for section usage eg. We'll probably have to care for this part within nodemcu community. But downloading should be decoupled from that and moved to upstream or forks.

**Comment by zerog2k** [comment]
+1 for fork and submodule

**Comment by jmattsson** [comment]
Sounds like what's wanted is to trim down the in-tree esptool.py to only contain the image building parts (presumably under a different name, e.g. mkespimage.py), and leave out the flashing functionality, but potentially maintain a fork of esptool.py where we can merge in fixes quicker. Is that a fair summary so far?

In this case there wouldn't even be a need to submodule it. The fork would just be something that sits "next" to nodemcu-flasher, available for those who don't use Windows.

**Comment by marcelstoer** [comment]
> Sounds like what's wanted is to trim down the in-tree esptool.py to only contain the image building parts (presumably under a different name, e.g. mkespimage.py), and leave out the flashing functionality, but potentially maintain a fork of esptool.py where we can merge in fixes quicker.

I wouldn't have a problem with that even though I'd still rather submodule the original esptool.py. But if there's some consensus in the community that your proposal is more desirable I wouldn't mind closing this PR.

**Comment by udif** [comment]
@jmattsson, you can always fork themadinventor/esptool into your own esptool repository, THEN submodule it inside nodemcu. What this brings you is the ability to do both the things you want:
1. Maintain your own patches for esptool.py on your fork, and even send a pull request to the original repository, hopefully your PR will be accepted.
2. Easily merge upstream fixes and updates by rebasing your patches once in a while, when you feel like.

**Comment by jmattsson** [comment]
@marcelstoer As per @devsaurus' suggestion of dotadiw, I [trimmed down](https://github.com/DiUS/nodemcu-firmware/tree/mkespimage)  esptool.py to only contain image creation/info capabilities (under the name of tools/mkespimage.py), and also made it able to produce a combined image which should help with the issues around flash erase reported elsewhere. I.e. you only get one larger 0x00000.bin image by default, rather than the 0x00000.bin + 0x10000.bin. Do you want to give it a spin and see if you like this approach?

This effectively cuts the dependency on esptool as far as the nodemcu firmware building itself is concerned, and avoids having to introduce a submodule. The image creation logic is unlikely to change much given how limited in scope it is.

Oh, and I noticed two more references to esptool - both the 'flash' target in the Makefile, and a mention in the README.md which would need to be updated if you remove esptool.

**Comment by marcelstoer** [comment]
> Do you want to give it a spin and see if you like this approach?

I don't understand in detail _what_ the script does (not my area of expertise) but I see merit in such an approach, thanks.
I could cherry-pick your commit into my branch but...

> I noticed two more references to esptool - both the 'flash' target in the Makefile

Grrr...another road block. No `esptool.py` means no `flash` target in the Makefile which in turn means no need for the `ESPPORT` variable in there.

_I_ have absolutely no need for the `flash` target but I don't know about others.

**Comment by jmattsson** [comment]
To be honest, the `flash` target is less useful these days than it was. Even just with the three modules on my desk (ESP-12E, NodeMCU-dev-0.9, ESP-01), I need to use three different flash settings (baud, mode, size), which the Makefile does not cater for. And when I do flash, I don't actually use the NodeMCU bundled esptool.py. I guess what I'm getting at is, while there is an argument to be made for having a `flash` target, there are now a couple of arguments *against* it too, and not just the ideological/best-practice should-we-submodule-it.

This isn't my project, but for what it's worth, I wouldn't miss the `flash` target either.

**Comment by marcelstoer** [comment]
https://travis-ci.org/nodemcu/nodemcu-firmware/builds/77910079 failed after `esptool.py` was replaced with `mkespimage.py` (I cherry-picked https://github.com/dius/nodemcu-firmware/commit/0ee772312fe5179653f07782fb437c2d467afd07 into this PR branch) but I need to come back to this at a later date, no time right now.

**Comment by zerog2k** [comment]
I use flash target, but just because it saves typing due to being two parts. If we have a monolithic image to flash starting from 0x00000, it makes flashing slightly easier.
On the other hand, fork and submodule seems to be the approach with the least overall impact to existing setup.
I would imagine most users who are pulling and building nodemcu will:
1. likely want to flash from same machine (not always, but I'd wager, most of the time)
2. are probably savvy enough to install or already have installed esptool elsewhere.

As a user of nodemcu, I would vote for fork and submodule for completeness for those who are not so savvy with esp sdk, etc.

**Comment by jmattsson** [comment]
@marcelstoer That build failed because the srec conversion you have there expected two bin files, whereas my mkespimage branch generated a combined bin image.

**Comment by marcelstoer** [comment]
@jmattsson I realize I ventured deeply into unknown territory with the turns this PRs is taking. AFAIU we can do away with `srec_cat` all together if using `mkespimage.py`. All the [current instructions](https://github.com/nodemcu/nodemcu-firmware/blob/master/.travis.yml#L15) seem to be doing is concatenating to two `.bin` files into one, padding/filling the gaps with a constant value without actually _transforming_ the input files. So, with only 1 input file left there's nothing to concatenate or pad, right?

More importantly though...I'd really like to get feedback from @nodemcu, @vowstar  or @MarsTechHAN what the chances are this PR will eventually get merged. Do you guys support the direction this PR is going?

**Comment by jmattsson** [comment]
@marcelstoer Yep, that's my understanding too.

**Comment by TerryE** [comment]
Yup, I like this approach. :smiley:

**Comment by marcelstoer** [comment]
Guys, thanks for all the feedback. I learned a fair share. I'm closing this PR because I need start over and create a PR against `dev` rather than `master`.

**Pull request closed without merging**
