### PR TITLE
Typo in HMC5883L module example

### PR DESCRIPTION
**Pull request by DavidMStraub**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is compliant with the [contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

\<Description of and rational behind this PR\>

Committers supporting this PR: leave blank

### CODE REVIEW

**Comment by dnc40085** [comment]
From [contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md#working-with-git-and-github):
>Pull requests for new features and major fixes should be opened against the dev branch.

**Comment by marcelstoer** [comment]
Thanks for spotting but @dnc40085 is of course right. I fixed the typo in `dev` myself.

**Comment by DavidMStraub** [comment]
Sorry, I wasn't aware that fixing a single letter in the docs counts as "major fix".

**Comment by marcelstoer** [comment]
It doesn't 😃 Thanks for pointing this out. We need to update that sentence.

**Pull request closed without merging**
