### PR TITLE
Revert "Rewrite ws2812 serialization code to use UART1 instead of bit-banging."

### PR DESCRIPTION
**Pull request by TerryE**
Reverts nodemcu/nodemcu-firmware#951.  Since we've had 2 :-1:  I've reverted my merge. I am taking a couple of weeks break from issue moderation.  Marcel, you can merge this revert.

### CODE REVIEW

**Comment by jmattsson** [comment]
Sorry to butt in, but why is the source branch on the nodemcu repo?

**Comment by TerryE** [comment]
Because that's how revert works. AFAIK. Marcel objected to my merging this PR prematurely, so I reverted it, and this revert click generated this branch on nodeMCU. I am a committee here but not an @Alkorin repo committee, so github want create the revert there. All getting a bit complicated.

**Comment by jmattsson** [comment]
Aaah, a github specialty, that explains it. Cheers.

**Comment by TerryE** [comment]
I think that this has been superseded, so I will close this and delete the `revert-951-ws2812-uart`branch in a day or so if no one objects.

**Pull request closed without merging**
