### PR TITLE
Remove deprecated rc module

### PR DESCRIPTION
**Pull request by nwf**
It has long been superseded by the rfswitch module.

Hold as PR until after next master cut.

### CODE REVIEW

**Comment by HHHartmann** [comment]
Shouldn't we announce a deprecation first instead of just having a module vanish without warning or explanation?

**Comment by nwf** [comment]
Well, the documentation already described it as "superseded", but I'm happy to wait for the `master` drop for this to land.

**Comment by marcelstoer** [comment]
Missing: removal of `rc.md` from `mkdocs.yml`. Now fixed.

**Comment by nwf** [comment]
Hm... This and #3123 passed CI even with the bad `mkdocs.yml`.

**Comment by marcelstoer** [comment]
Yes, but the docs build on RTD failed and that info isn't fed back to GitHub. Not sure if/how that could be achieved.

**Pull request merged**
