### PR TITLE
fix eclipse project

### PR DESCRIPTION
**Pull request by nodemcu**
compile ok.
gen bin ok.
clean ok.
flash not ok with esptool.py.
it seems that esptool.py can only flash a combined bin right.

### CODE REVIEW

**Comment by baracudaz** [comment]
I am using the following command to flash the firmware which works quite well:
'esptool.py --port /dev/tty.usbserial-XYZ write_flash 0x00000 nodemcu-firmware/pre_build/latest/nodemcu_latest.bin'

**Comment by nodemcu** [comment]
yes, flash one piece bin is OK.
but I don't know how to combine the generated 2 bins into one file with command line.

I can flash two piece of bins(eagle.app.v6.flash.bin and eagle.app.v6.irom0text.bin) in the flash, 
but it doesn't run.

But if I use another flash tool, the compiled 2 bins runs ok.
I am in windows 7.

**Comment by baracudaz** [comment]
Can you try something like this:
`${ESPTOOL} --port ${TTY} write_flash 0x00000 ${BINDIR}/eagle.app.v6.flash.bin
${ESPTOOL} --port ${TTY} write_flash 0x40000 ${BINDIR}/eagle.app.v6.irom0text.bin`

**Comment by nodemcu** [comment]
esptool.py -p com1 write_flash 0x00000 eagle.app.v6.flash.bin 0x10000 eagle.app.v6.irom0text.bin 0x7c000 esp_init_data_default.bin 0x7e000 blank.bin

now I am doing like this, 
do you mean call esptool 4 times?

**Comment by nodemcu** [comment]
enter flash mode do:
esptool.py -p com1 write_flash 0x00000 eagle.app.v6.flash.bin
leave flash mode automatic

enter flash mode again:
esptool.py -p com1 write_flash 0x10000 eagle.app.v6.irom0text.bin

this procedure works.
but have to enter flash mode twice manually.

and after all done, it can start to prompt >
better run file.format() once.

**Pull request merged**
