### PR TITLE
Fix float math.pow when number was negative and power was odd

### LINKED ISSUE #1491: float exponentiation of negative values gives wrong result
### Expected behavior
(-0.5)^3 should result in -0.125

### Actual behavior
(-0.5)^3 results in +0.125

### Test code
```Lua
=(-0.5)^3
=(-0.5)*(-0.5)*(-0.5)
```
### NodeMCU version
branch: master
commit: 95e85c74e7310a595aa6bd57dbbc69ec3516e9c6
powered by Lua 5.1.4 on SDK 1.5.4.1(39cb9a32)

### Hardware
NodeMCU v2 - Lua based ESP8266

### PR DESCRIPTION
**Pull request by luismfonseca**
Fixes #1491.

- [X] This PR is compliant with the [contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [X] The code changes are reflected in the documentation at `docs/en/*`.

Committers supporting this PR: leave blank

### CODE REVIEW

**Comment by luismfonseca** [comment]
I run some tests and this still doesn't look 100% ok.

Here are mi specs:
```lua
require 'mispec'

describe('math.pow(a, b)', function(it)
    it:should('return 1 if power to 0', function()
        ok(eq(math.pow(0, 0), 1))
        ok(eq(math.pow(1, 0), 1))
        ok(eq(math.pow(123, 0), 1))
    end)
    
    it:should('power to even numbers, always resulting in a positive', function()
        ok(eq(math.pow(2, 2), 4))
        ok(eq(math.pow(-2, 2), 4))
        ok(eq(math.pow(-2, 4), 16))
    end)

    it:should('power to odd numbers', function()
        --ok(eq(math.pow(2, 3), 8)) -- fails
        --ok(eq(math.pow(-2, 3), -8)) -- also fails
        ok(eq(math.pow(-0.5, 3), -0.125))
    end)
end)

mispec.run()
```

The result were:
```lua
math.pow(a, b), it should:
> 
  * return 1 if power to 0
  * power to even numbers, always resulting in a positive
  ! it failed:	mispec.lua:31: 16 is not equal to 16
stack traceback:
	mispec.lua:31: in function 'eq'
	mispec_mathpow.lua:13: in function <mispec_mathpow.lua:10>
	[C]: in function 'pcall'
	mispec.lua:112: in function <mispec.lua:109>

  * power to odd numbers
  ! it failed:	mispec.lua:31: -0.125 is not equal to -0.125
stack traceback:
	mispec.lua:31: in function 'eq'
	mispec_mathpow.lua:19: in function <mispec_mathpow.lua:16>
	[C]: in function 'pcall'
	mispec.lua:112: in function <mispec.lua:109>


Completed in 0.21 seconds.
Success rate is 33.3% (2 failed out of 3).
```

So it seems that `math.pow(2, 4) == 16` returns `false` in the `float` build. It returns `true` on the `integer` build though, so I think this function still needs some work.

**Comment by devsaurus** [comment]
This change fixes the wrong calculation of `x^y` for `x < 0` and integer y. Though it still neglects fractional values of y.
The original code works around this by forcing x to positive range (which introduced the current error). Can this condition be reported to the upper caller as NaN or something else instead?

**Comment by luismfonseca** [comment]
If the `x` is negative `y` is fractional, then the result is a complex number.

So I agree that it would make sense to return sort of error...

**Comment by luismfonseca** [comment]
I've updated the PR, now returns `NaN` in that scenario.

**Comment by devsaurus** [comment]
Works out of the box on Lua layer - thanks Luís!

**Pull request merged**
