### PR TITLE
Fix DHT11 10times BUG, add auto-select feature, fix program bug in md

### PR DESCRIPTION
**Pull request by MarsTechHAN**

### CODE REVIEW

**Comment by MarsTechHAN** [comment]
But it use several lines of extra codes... So maybe not a good idea? I thought

**Comment by MarsTechHAN** [comment]
Sorry for mistake, re-process the pull request to dev branch

**Comment by chadouming** [comment]
You were right, this does use a lot more memory. I will try to find a way to make it with less line of codes

**Comment by MarsTechHAN** [comment]
I think, it may not use that much of mem...? If you think it really is, how about just pre-calculate all the bytes? and if it is DHT22, combine those bytes later?

**Comment by chadouming** [comment]
Why not calculate all the byte dht22 style and replace empty one by zeros ?

**Pull request closed without merging**
