### PR TITLE
Merge dev to dev096

### PR DESCRIPTION
**Pull request by vowstar**
Merge dev to dev096, make sure it latest.

### CODE REVIEW

**Comment by pastukhov** [comment]
> =dht.read(2)
0	26	99	300	900

**Comment by pastukhov** [comment]
```lua
> =dht.read(2)
0	25	46	100	700
```

**Comment by vowstar** [comment]
@pastukhov Yeah, 25.100 Centigrade, 46.700 %RH.

**Comment by pastukhov** [comment]
Thanks!

**Comment by vowstar** [comment]
@pastukhov Thank you for give us issue and help us make NodeMCU better!

**Pull request merged**
