### PR TITLE
Mqtt rometatable

### LINKED ISSUE #1946: mqtt module for esp32?
Just wonder when can we have mqtt feature for esp32? very looking forwards to this.

### PR DESCRIPTION
**Pull request by ryanplusplus**
Fixes #1946.

- [x] This PR is for the dev branch rather than for master.
- [x]  This PR is compliant with the other contributing guidelines as well (if not, please describe why).
- [x]  I have thoroughly tested my contribution.
- [x]  The code changes are reflected in the documentation at docs/en/*.

> This pull request adds support for the mqtt protocol and is based on https://github.com/tuanpmt/espmqtt as suggested in issue #1946. This implementation simplifies mqtt support over the AWS IOT library implementation and has tried to maintain compatibility with the existing NodeMCU MQTT module. Where the underlying library does not provide support (eg. table-based unsubscribe function), it has been noted in the doc.

> Secure (TLS) MQTT support has not been tested (in progress), but there is no reason it should not work out of the box.

This is an amendment to @goughy's PR (https://github.com/nodemcu/nodemcu-firmware/pull/2307) that makes the requested changes.

### CODE REVIEW

**Comment by devsaurus** [comment]
Thank you very much @ryanplusplus and @goughy!

**Comment by ryanplusplus** [comment]
Thanks @devsaurus!

**Comment by marcelstoer** [comment]
I hardly dare to ask but I must...

We have [many reported issues](https://github.com/nodemcu/nodemcu-firmware/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mqtt) for the existing (ESP8266) MQTT module. Despite, or because, it being our [2nd most popular non-basic module](https://nodemcu-build.com/stats.php). It originally also branched off Tuan's lib.

Did anyone working on this new module spot anything that we could backport to help fix those existing issues?

**Comment by ryanplusplus** [comment]
@marcelstoer My work here was limited to switching the metatable to RO and doing some spot checks on target so I haven't dug into the underlying library. @goughy?

**Comment by devsaurus** [comment]
While updating to latest esp-idf, I figured that Espressif ships this mqtt library now as [part of the sdk](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/mqtt.html). This integrates also support for MQTT over SSL, Websocket and Websocket Secure.
On the long term, we could re-base the `mqtt` module onto the native esp-idf mqtt library (looks like a drop-in replacement) and add support for the additional transport methods (probably more effort).

**Comment by ryanplusplus** [comment]
@devsaurus I took a crack at it here: https://github.com/nodemcu/nodemcu-firmware/pull/2509

**Pull request merged**
