### PR TITLE
Do not allow execution to continue after a PANIC

### PR DESCRIPTION
**Pull request by jmattsson**
As discussed in #801, I thought I'd already pushed this.

### CODE REVIEW

**Comment by TerryE** [comment]
Johnny, will this do what you intend? Surely a `while(1) {}` loop will simply trigger the WDT? I am thinking  aloud on my tablet rather than my laptop, but  IMO the best approach would be to dump some valedictory diagnostic into the RTC and latch a "PANIC" restart reason.

**Comment by jmattsson** [comment]
Aye Terry, it [does precisely that](https://github.com/nodemcu/nodemcu-firmware/issues/801#issuecomment-160844777). This isn't a fix for @pjsg's *actual* issue, this is only to prevent the subsequent flood of Weird Stuff(tm) that otherwise happens after you've hit a panic and can lead you on a wild goose chase. Continuing Lua execution after a panic is (very very) wrong, and that''s what this one-liner ensures doesn't happen.

I'm not opposed to extending it with further diagnostics, though having a #define to switch it off would be preferrable (we use every word of available RTC memory for actual data storage on some of our projects,
so we'd rather sacrifice the diagnostic capability). Knowing what information to squirrel away to be useful is more your area of expertise than mine, so I'll let you do that bit ;)

**Comment by pjsg** [comment]
Could this while(1) loop be placed in place of the c_exit that was commented out. If someone (in the future) uses the lua_atpanic call to replace the panic handler, then this problem will happen again.

**Comment by TerryE** [comment]
@jmattsson Johny, one of the changes that I added along with my strip debug was to re-implement proper tracebacks.  See `lua.c`, reporter `docall()` calls `traceback()` which now calls `debug.traceback()` as this is now implemented.  It would be a good enhancement if the panic routine did a proper traceback before going into the shutdown death loop.

Possibly the simplest way would be to move the static traceback() to `lauxlib.c:luaL_traceback()` and add the `docall()` logic inline in `panic()`.

**Comment by jmattsson** [comment]
Both good ideas, I'll put both on my to-do list!

**Comment by nickandrew** [comment]
I modified it to optionally halt on panic rather than reboot. Just for use while debugging.

```diff
diff --git a/app/include/user_config.h b/app/include/user_config.h
index b4e7e5b..53b119e 100644
--- a/app/include/user_config.h
+++ b/app/include/user_config.h
@@ -26,6 +26,8 @@
 #define BIT_RATE_DEFAULT BIT_RATE_9600
 #endif /* DEVELOP_VERSION */
 
+/* Define this to halt forever on panic, rather than automatic restart */
+#define PANIC_HALT
 
 #define NODE_ERROR
 
diff --git a/app/lua/lauxlib.c b/app/lua/lauxlib.c
index 1ce21f3..75a2fdd 100644
--- a/app/lua/lauxlib.c
+++ b/app/lua/lauxlib.c
@@ -816,7 +816,11 @@ static int panic (lua_State *L) {
   luai_writestringerror("PANIC: unprotected error in call to Lua API (%s)\n",
                    lua_tostring(L, -1));
 #endif
+#if defined PANIC_HALT
+  while (1) { system_soft_wdt_feed(); }
+#else
   while (1) {}
+#endif
   return 0;
 }
 
```

Could be useful to add?

**Comment by TerryE** [comment]
Nick, I am not sure what this would add other than avoiding the boot message, as the ESP to all intents and purposes would be locked up and need a H/W reboot.  

But as to implementing this type of option, there is now a minimal debug compiled in by default.  This provides `traceback` and `getregistry`.   It would be simple add, say, `degug.setPanicAction()` to make this configurable at runtime.  You might want to wrap this code in a `DEBUG_PANIC_STALL` conditional.

**Comment by nickandrew** [comment]
> Nick, I am not sure what this would add other than avoiding the boot message, as the ESP to all intents and purposes would be locked up and need a H/W reboot.

That's right, it's strictly for debugging use. I'm seeing the console messages on ESPlorer and when it panics I can scroll back through the full console output at my leisure. ESPlorer doesn't allow scroll back while the device is still outputting text, so it's difficult to review the logs if the device is continually rebooting.

I'll check out the minimal debug. Not sure how I can use it (I suppose it's undocumented) but I'd need to call it from C, because it's the C functions in which I am detecting the error. Changing the lua code tends to make the panic disappear.

**Comment by TerryE** [comment]
See my last comment on #813.  My patch shows you how to do this.

**Comment by TerryE** [comment]
@nickandrew Nick, I am going to merge this one as it is a lot better than the current continue and then die messily and confusingly as is the current behaviour.  This is the best option for typical Lua developers.  I am currently developing a more sophisticated firmware and module developer variant which gives better info, but will implement this as a subsequent PR.

**Comment by nickandrew** [comment]
@TerryE No worries! Looking forward to it. I probably did something wrong following your comment in #813 cause I've been getting reboots rather than tracebacks. I'll have another go at it. And I'll keep feeding the WDT in my local branch to halt rather than reboot, as it's so useful to me to have the boot-run-crash cycle be a one shot.

**Pull request merged**
