### PR TITLE
U8G add support for ST7920 128x64 LCDs

### PR DESCRIPTION
**Pull request by MilanLochovsky**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [ ] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/en/*`.

\<Description of and rationale behind this PR\>

Tested on LCD 12864B V2.0 with this parameters:

spi.setup(1, spi.MASTER, spi.CPOL_LOW, spi.CPHA_LOW, 8, 8) -- work with CPOL_HIGH and CPHA_HIGH too
cs  = 1 -- GPIO5, can be another pin
dc  = 200 -- Not used internaly, use SW DC switch
res = 0 -- GPIO16 can be another pin      
disp = u8g.st7920_128x64_hw_spi(cs, dc, res) -- Constructor

Sorry for my english.

### CODE REVIEW

**Comment by eku** [comment]
AFAIK [u8g](https://github.com/olikraus/u8glib) is no longer developed. Should we move to [u8g2](https://github.com/olikraus/u8g2)?

**Comment by devsaurus** [comment]
> We should move to u8g2!

**Comment by MilanLochovsky** [comment]
@eku  - Sorry, but I need version for esp8266 and this repository haven't support for u8g2. Ant u8g works fine!

**Comment by eku** [comment]
@MilanLochovsky you can still use your extension to u8g in your forked repo. No need to merge this into the upstream repo.

**Comment by MilanLochovsky** [comment]
@eku - but what nodemcu repo for ESP8266 uses u8g2? I only wrote (but this is not true, i rewrite existing solutions) interface for ST7920 displays, where using many peoples and actual repos for ESP8266 (master/dev) using u8g library. After repos for ESP8266 using u8g2 library, i can (but any other pepole) use this code for working ST7920 too. Only where i see u8g2 library is repo for ESP32.

**Comment by marcelstoer** [comment]
> We should move to u8g2!

What's the harm of adding support for another display to u8g until u8g2 is available? Assuming the contribution is up to our standard of course...That isn't the case yet AFAICS (missing documentation, odd commit list).

**Comment by marcelstoer** [comment]
No indication from the author to fix the issues mentioned above, idle for a month -> closing

**Pull request closed without merging**
