### PR TITLE
ESP32 Makefile: Auto-detect CPU architecture

### PR DESCRIPTION
**Pull request by mk-pmb**
- [ ] This PR is for the `dev` branch rather than for `master`.
  - Seems like Github uses the wrong (i.e. master branch's) PR template
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/*`.

\<Description of and rationale behind this PR\>
The repo we download from only has x86_64 anyway currently, but a
download error will be much more informative than bogus errors from
an incompatible compiler.

### CODE REVIEW

**Comment by HHHartmann** [comment]
I'm pretty sure @TerryE has a version for ARM architecture for raspi.

**Comment by marcelstoer** [comment]
> Seems like Github uses the wrong (i.e. master branch's) PR template

Templates are available to collaborators when they are merged into the repository's default branch.

> a download error will be much more informative than bogus errors from an incompatible compiler.

Not sure I agree. While technically correct I feel that seeing a "404: Not Found" somewhere is even less obvious. If the only supported platform is Linux x86_64 anyhow we might as well ensure this in the Makefile with a precondition check.

**Comment by mk-pmb** [comment]
> I feel that seeing a "404: Not Found" somewhere is even less obvious.

Well I for one would then try to "fix" the broken download URL and discover that no version for my arch is available, but the source code is. So I can then decide whether to use another computer or compile that source for the platform I tried.

**Comment by mk-pmb** [comment]
I made a better error message that explicitly suggests the option of compiling the toolchain yourself.

**Comment by marcelstoer** [comment]
> I'm pretty sure @TerryE has a version for ARM architecture for raspi.

It's here: #2958

**Pull request merged**
