### PR TITLE
Networking rampage and accumulated fixes

### PR DESCRIPTION
**Pull request by nwf**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

This represents the work done thus far on a few issues; #3032 and easy aspects of #3004 (xref #3006) as well as refactoring and simplification around the network-facing things I use regularly.  I've been carrying these patches locally for a while and would like to push them upstream, at least to `dev`, for others to beat about a bit and so that other things stop feeling quite so blocked on these.  Much of this has been subject to testing via the test harness in my https://github.com/nwf/nodemcu-firmware/tree/dev-active branch (recall #2983), so I feel fairly confident in having not broken anything obvious.

The `mqtt` and `tls` "stop using espconn->reverse" refactoring could be done for other network-facing modules (`http`, `coap`, and `websocket`) as well and would probably be similarly beneficial.  Then we can remove the `->reverse` field from `espconn` and make a little more progress on #3006.  I don't feel confident in changing code in the remaining ones, absent test support.

ETA: removed `espconn->reverse` from `tls`, too, and fixed a stack imbalance issue in the new TLS cert/key callback code.

### CODE REVIEW

**Comment by nwf** [comment]
ETA, again: found and fixed a memory leak in the new `tls` cert/key callback API (just a typo, sorry).  I've adjusted my test harness to exercise the new API better and believe that this class of bug is no longer present.

**Comment by marcelstoer** [comment]
Cool! I like every PR that removes more code than it adds. Can we land this on `dev` sooner rather than later?

**Comment by nwf** [comment]
*I*'m happy to hit merge and deal with any fallout, but I suspect it would be better if someone else gave things a quick run-through first. ;)

**Comment by marcelstoer** [comment]
I think it would very valuable (and thus welcome by the community) if we merged dev back to master in the coming weeks. It's been almost six months but there are a few things pending: https://github.com/nodemcu/nodemcu-firmware/milestone/14. So, I wouldn't mind landing it on dev soonish as it looks quite mature.

**Comment by nwf** [comment]
I'm worried about the `tls` callback changes (1cc2040), which probably merit some more discussion than they've gotten (as part of #3062).  I've pulled those from this PR and will open another for the next round of rampaging.

**Comment by nwf** [comment]
Argh, I didn't really mean to squash all those together.  I'm feeling jittery about more of them, now, too, but whatever, I think I can live with some egg on my face and follow-up commits to fix bugs as we find them.

**Pull request merged**
