### PR TITLE
add a new httpserver module

### PR DESCRIPTION
**Pull request by hanfengcan**
Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

I use the lua module `httpserver` to do a project. but this module seem memory leak. I try to fix, but failed. 

so, I write this new module. it is a similar module to [http/httpserver](../../lua_modules/http/httpserver.lua), but more stable memory consumption.

In fact, I copy some code from old module to new module.

### CODE REVIEW

**Comment by nwf** [comment]
Please don't.  Rewriting from scratch is fun, but not a great approach.  If there's an issue with the existing `httpserver`, just fix it in place.

That aside, this is clearly derivative from the existing `httpserver` and so should not strip the existing copyright and license notice.

The use of `xpcall` in `send_header` seems incredibly dubious; this code is squashing any possibility of error handling in favor of printing to the console.

Can you articulate why `cfini` needs to explicitly `nil` out `req` and `res`?  I didn't think we'd be holding on to those in closure after the existing `cfini` was done.

Also note that `http2` is quite confusing, given the existence of https://en.wikipedia.org/wiki/HTTP/2

**Comment by hanfengcan** [comment]
sorry, I am not add the license notice.

the asset will make the nodemcu reboot, so I use the xpcall

maybe we are able to fix the memory leak of the httpserver together and then I cancel this PR

btw, the name of httpserver2 just to describe it fork from httpserver2😊

**Comment by hanfengcan** [comment]
Today, I try to fix the memory leak again. I almost modified all over the code to make it look like the new module, include closure. 

 But, no use.

**Comment by nwf** [comment]
To respond only to "the asset will make the nodemcu reboot, so I use the xpcall": the *point* of an assertion is to throw an error, which can be caught by either wrapping code or by the top-level handler, which reboots.  If you don't want that behavior, don't use an assert!

Please attempt to characterize the memory leak: which object is being retained, and how, before mutating the code in an effort to fix it.

**Comment by hanfengcan** [comment]
thanks

I just check the type of header and header.headers. hint like wifi.sta.config `config table not found` and stop the program while the type are wrong

About the memory leak, there are some information in #2772. the memory decrease until `not enough memory`

Possible I can try to modified the new module to make it look like the old module.  maybe to find the problem and fix it

**Comment by marcelstoer** [comment]
I'm definitely against maintaining another HTTP Server module ourselves. If it's got issues (memory or otherwise) then those should be fixed.

However, instead we might even decided to remove the current module and tell users to use https://github.com/marcoskirsch/nodemcu-httpserver instead. I never used it, I didn't analyse its code but it has been around for a long time and seems quite popular (and @HHHartmann contributed to it).

**Comment by hanfengcan** [comment]
I know. let me try to fix it

**Comment by HHHartmann** [comment]
The module is quite good. Unfortunately it is not maintained anymore for no apparent reason.

**Comment by mjg14** [comment]
@HHHartmann -- which module? This one, or the Marcos Kirsch one? In general: If I wanted to serve a single, simple page (with variable data on it), and react to a few buttons or links on that page by making the nodeMCU do things, which one would you recommend?

**Comment by HHHartmann** [comment]
The Marcos Kirsch one is a complete project including network configuration and uploader. Recently it also got adapted to work with LFS. You only need to add your one lua file which generates the desired webpage.
It has problems however if your (POST) request has a largish body as it first receives the while body and then calls your Lua code. However return ing largish HTML pages is not limited, as it uses coroutines and can send the page as you build it.
Here or in httpserver.lua as a matter of fact it is vice versa (if i understood the code correctly). The body of a request can be as large as needed but the reply is limited by memory size.
Also you will need to add some code for startup/network config and to match the web URL to the Lua file to execute.
The Marcos Kirsch variant can also do authentication for you. It has lots of examples which will get you started quickly.

**Pull request closed without merging**
