### PR TITLE
MQTT Client - CONNACK processing

### PR DESCRIPTION
**Pull request by jfollas**
- Process the CONNACK message received from the broker after Connect
- Provide feedback to Lua via failure callback on client:connect()
- Also provide failure information for other situations not covered by CONNACK

### CODE REVIEW

**Comment by jfollas** [comment]
Re: Issue #1122

**Comment by pjsg** [comment]
Thank you for this.

Can you create a function that calls the callback (if present) and invoke that in all the places that you added -- rather than duplicating the code. There is (already) quite a lot of duplicate code in mqtt.c!

**Comment by pjsg** [comment]
Thank you. This looks plausible. We still have a significant issue in the MQTT code that it saves and uses lua_State pointers later. I suspect that we want to do that cleanup later....

**Comment by TerryE** [comment]
> We still have a significant issue in the MQTT code that it saves and uses lua_State pointers later. I suspect that we want to do that cleanup later....

Phil, this is pretty straight forward, so it would be nice if you include this as soon as convenient for you. Many thanks Terry

**Comment by pjsg** [comment]
I added a PR for this #1129

**Comment by pjsg** [comment]
@jfollas Can you resolve the conflicts please?

**Comment by jfollas** [comment]
@pjsg Rebase complete.

**Comment by pjsg** [comment]
Looks good to me..... Merged

**Pull request merged**
