### PR TITLE
Add MQTT support to NET module

### PR DESCRIPTION
**Pull request by tuanpmt**
Testing working ok, please check, test and make sure it does not have a problem/conflict with your current code.
This is the first time I write a module for LUA, so you need to check carefully.

Thanks.

http://www.esp8266.com/viewtopic.php?f=19&t=1278

### CODE REVIEW

**Comment by nodemcu** [comment]
I merged this to new branch mqtt.
check this branch out.
I think maybe it's better to create a mqtt module separately?  not combined with net module?

**Comment by tuanpmt** [comment]
If you want to create a mqtt module separately with net, only need copy net.c => mqtt.c, and rename its functions. Because mqtt use all resources of net module, except server function (small).

**Comment by layerzerolabs** [comment]
Firstly, this great work just keeps getting better, with the opening up of the source now the rewards are really starting to build - many other folks can contribute (like this mqtt addition) so nice one - you (plural) rock!!

The slight drawback of having separate branches is that fixes in the main-line might not make it into this branch - for example the SPI module is currently available in master but not this branch.

What are the problems in integrating this into the main branch? Is it because of consuming lots of heap?

Thanks and apologies if this is a noob question!

**Comment by nodemcu** [comment]
mqtt in new branch because it's under rapid development , the api may changes a lot.
and of course it will be merged to master asap.

**Comment by tuanpmt** [comment]
Yes. I agree.
I have fixed some bugs today, and I have not updated it to LUA :))

**Comment by layerzerolabs** [comment]
Ok thanks to you both for explaining it, I'm glad now that I understand it is for development ease.

Thanks again - it's really wonderful to be able to have such a dialog with the work at the cutting edge!

**Comment by nodemcu** [comment]
@tuanpmt 
wait a few minutes, I will push a separated mqtt.c.
and I am reference the api from [mqtt.js](https://github.com/mqttjs/MQTT.js)
but I haven't set up a test server yet. the code only pass compile, no test yet.
please review the code, I'm not familiar with the mqtt protocol....

**Comment by tuanpmt** [comment]
Wait,
Today I have a lot of changes to my MQTT code, and I have not updated it to LUA module. So you wait for me then do the update.
except mqtt.js api does not have LWT, its api is ok

**Comment by tuanpmt** [comment]
I write this blog is not finished, but hope it helps you understand the basic of MQTT (write english result is somewhat troubling to me :laughing: )
http://tuanpm.tumblr.com/post/108428048879/what-is-mqtt-how-to-use-it-with-esp8266

**Comment by nodemcu** [comment]
pushed already:(
only the api form is adopted.
"send"--->"publish"
"mqtt"--->"Client"
and some para and callback.

**Comment by layerzerolabs** [comment]
On Sun, 18 Jan 2015 05:58:28 -0800, tuanpmt wrote:
> I write this blog is not finished, but hope it helps you understand
> the basic of MQTT (write english result is somewhat troubling to me  
> )
>
> 
> http://tuanpm.tumblr.com/post/108428048879/what-is-mqtt-how-to-use-it-with-esp8266
> [1]
>
> --
> Reply to this email directly or view it on GitHub [2].
>
> 	*
>
> Links:
> ------
> [1]
> 
> http://tuanpm.tumblr.com/post/108428048879/what-is-mqtt-how-to-use-it-with-esp8266
> [2]
> 
> https://github.com/nodemcu/nodemcu-firmware/pull/108#issuecomment-70409224

 Well, English is the only language which I feel qualified in - would 
 like to add lua, C, Chinese etc.!

 Some minor corrections to your excellent blog post just to make it more 
 readable:

    Instead of
 "So what MQTT, very simple, you just google “what is mqtt” or “mqtt 
 slide”. And here, we only briefly and understand some definitions 
 “subscribe”, “publish”, qos, retain, last will and testament (lwt)."
    Consider
 "So what is MQTT? To get a good overview simply search for “what is 
 mqtt” or “mqtt slides”. In this article, we will briefly review the main 
 definitions: “subscribe”, “publish”, "qos", "retain", "last will and 
 testament" (lwt)."

    Instead of
 "We have the some nodes, called mqtt client connects to the mqtt server 
 called broker. Each client will register a few channels, eg 
 "/client1/channel1", "/client1/channel2", when it register a channel, 
 called subscribe. and it will receive data when another client sends 
 data to the subscribed channel. Manipulation send data to a channel 
 called publish."
    Consider
 "In an MQTT system, many nodes (called mqtt clients) connect to a mqtt 
 server (called broker). Each client will typically register a few 
 channels, eg "/client1/channel1", "/client1/channel2", this registration 
 process is called subscribe. Each subscribing node will receive data 
 when another client sends data to the subscribed channel. When a node 
 sends data to a channel it is called publish."

 But overall, a very good post that explains the main features of MQTT 
 very well, nice work!!

 Kind regards

 Gareth

**Comment by tuanpmt** [comment]
Haha, thank you Gareth,
I fix it , and I think will email you to ask fix more things
:+1:

**Pull request closed without merging**
