### PR TITLE
DS18B20 Lua module - removing integer version related code

### PR DESCRIPTION
**Pull request by vsky279**
Fixes - no reported issue.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

This PR removes code supporting integer version of the firmware. As float version is now standard I think there is no reason to have integer version support in standard volume.

### CODE REVIEW

**Comment by pjsg** [comment]
I'm not sure that I'm happy with this -- the integer builds are not going away yet. It might make sense to have two versions -- one for float builds and one for integer builds.

**Comment by vsky279** [comment]
Ok. I will add integer version of the module. I just don't like the garbage in the standard module version.

**Comment by vsky279** [comment]
I think we should decide whether to merge this or close the PR. Philip @pjsg?

**Comment by pjsg** [comment]
I vote to merge this one.....

**Pull request merged**
