### PR TITLE
BMEXXX sensor documentation update (Lua 5.3 compatibility)

### PR DESCRIPTION
**Pull request by vsky279**
Fixes - no reported issue>.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

BME280 and BME680 sensor modules documentation includes examples that are
- not Lua 5.3 compatible (`("%d"):format(3/2)` fails as 3/2 has no integer representation)
- were intented for integer version so includes code that is not needed in now standard flow version of the firmware.

### CODE REVIEW

**Comment by pjsg** [comment]
Again, I'm not convinced that you should be removing compatibility with some versions of the firmware.

**Comment by vsky279** [comment]
I don't like the current code not being compatible with Lua 5.3. Another way to make it compatible but also working in integer version is to add `math.floor`, i.e.
```Lua
local Tsgn = (T < 0 and -1 or 1); T = Tsgn*T
print(("T=%s%d.%02d"):format(Tsgn<0 and "-" or "", math.floor(T/100), T%100))
```
instead of just
```Lua
print(("T=%.2f"):format(T/100))
```
Do we need such complexity in an example?
I tend to think that if someone goes for the integer version, he/she has to build it himself, so I assume he/she knows what he's doing, knowing all the implications.

Anyway in the new BME280 driver (#3132) returned values are float so it is not integer version compatible. Should it be?

**Comment by marcelstoer** [comment]
The examples in the docs should work with whatever defaults we have in the firmware (5.1 vs. 5.3). If an example only works with int or float then it should mention that clearly.

**Comment by vsky279** [comment]
This PR has
\+ readability of the example and it's simplicity
\- one version for float another for integer version

It seems that consent is that compatibility is winning over simplicity (simply said) so I will close this PR.

**Pull request closed without merging**
