### PR TITLE
Next release snap

### PR DESCRIPTION
**Pull request by marcelstoer**
This was triggered by Gregor's comment at https://github.com/nodemcu/nodemcu-firmware/pull/3633#issuecomment-1930439746.

It's been ages since we last snapped something back to the `release` branch. What we documented at https://github.com/nodemcu/nodemcu-firmware/blob/release/CONTRIBUTING.md#handling-releases is mostly still correct 😄

### CODE REVIEW

**Comment by HHHartmann** [comment]
Would like to add 1 or 2 pull reques  first.

**Comment by marcelstoer** [comment]
@HHHartmann which ones did you have in mind?

**Comment by HHHartmann** [comment]
I would suggest these at least:
- [x] #3637 
- [x] #3632
- [x] #3633

and maybe this one, but it would need a little bit of love first

- [x] #3450

And of course I'd still like to get this integrated:
- [x] #3230

**Comment by marcelstoer** [comment]
The first four seemed like no-brainers. Hence, I felt confident to merge them 😄 

As for the last one, I'm completely lost, not my world.

**Comment by HHHartmann** [comment]
When merging this PR a github workflow should start creating the release note together with attached luac.cross binaries for windows. So give it some time.
Trigger is:
``` 
on:
  push:
    tags:
      - '3.*-release_*'
```

**Comment by HHHartmann** [comment]
found some more changes that hepled me:
- [x] #3638

**Pull request merged**
