### PR TITLE
Add SSL/TLS remarks to docs

### LINKED ISSUE #1325: add TLS cipherlist to documentation
please document the supported ciphers for TLS as many of them (especially RC4) are disabled in current distributions.

http.get "https://www.howsmyssl.com/a/check" shows:
TLS 1.1

TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_RC4_128_MD5

### PR DESCRIPTION
**Pull request by marcelstoer**
fixes #1325

### CODE REVIEW

**Comment by devsaurus** [comment]
Why maintain 3 copies of the same information?

**Comment by marcelstoer** [comment]
We currently don't have a good place to document such cross-cutting concerns. Where would you place that?

**Comment by hex2a** [comment]
It would be better to document and maintain the cipher list in one place. (maybe in the net module documentation, as you should set the certificate with net.cert.verify)

**Comment by devsaurus** [comment]
Like @hex2a proposed, net would be most intuitive also in my opinion. The other modules could briefly mention the list in net.

> if more modules are "affected".

I'm not aware of any - and a quick grep for `espconn_secure` didn't bring up further instances.

**Comment by marcelstoer** [comment]
Fine for me. I updated `http.md` and `mqtt.md` to point to `net.md` instead and force-pushed the changes.

**Pull request merged**
