### PR TITLE
net socket documentation clarification

### LINKED ISSUE #2321: net socket documentation clarification
The Lua Developer FAQ has the [following example of socket usage](https://nodemcu.readthedocs.io/en/latest/en/lua-developer-faq/#so-how-is-the-lua-registry-used-and-why-is-this-important):
> srv:on("connection", function(sck, c)
>     svr:send(reply)
> end)

As far as I can tell from the wording this is intended as an example
of memory leakage.  Could it please be annotated with an unambiguous
"This is how not to do it"?  Or a fuller working example added, such as:

> local udpskt
> udpskt = net.createUDPSocket()
> if udpskt ~= nil
> then
>     udpskt:on("sent", function(s, c) s:close() end)
>     udpskt:send(UDPPort, broadcast, "Message")
> end

Thanks - Will

### PR DESCRIPTION
**Pull request by joysfera**
Hopefully helps to fix #2321.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/en/*`.

My first PR (ever), untested because I haven't managed to convince the RTD to build the docs, sorry.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Congratulations to your first PR 👏 

The entire FAQ page has a few (Markdown) formatting issues - and they become apparent whenever someone submits a PR 🙁I try to live by "form follows function" and, therefore, the content is more important than its presentation.

Writing this comment takes a lot more time than just fixing what you added but I hope a few people will, over time, benefit from this "investment".

> untested because I haven't managed to convince the RTD to build the docs

True, it doesn't trigger on PRs. The contributing guidelines have a chapter about writing documentation: https://github.com/nodemcu/nodemcu-firmware/blob/master/CONTRIBUTING.md#writing-documentation. I can understand that running (which likely means _installing_) MkDocs locally is considered overkill if you just want to fix a sentence here or there. I assume you edited directly in GitHub? Its preview mode would have allowed you to verify that the link is valid.

For a link to be valid on GitHub it has to be a regular Markdown link to e.g. `docs/en/modules/net.md` as the file is called `net.md`. When the HTML documentation is created the files are not longer Markdown and thus `.md` is stripped; both in the file names and all links. This happens automatically which means that authors can simply stick to the full GitHub form.

Where it gets tricky is with linking to in-page anchors as they are built differently by GitHub and MkDocs/RTD. While on GitHub it is [`#example-5`](https://github.com/nodemcu/nodemcu-firmware/blob/master/docs/en/modules/net.md#example-5) it would have to be [`#example_5`](https://nodemcu.readthedocs.io/en/latest/en/modules/net/#example_5) (note the underscore) on RTD - you can't please both. However, linking to heading anchors (function names) is safe. `#netsocketon` is the same on both GitHub and RTD.

**Comment by joysfera** [comment]
FYI, I have edited locally in vim (no idea how to edit in GitHub), then checked the resulting MD file in https://stackedit.io/ to see that the resulting MarkDown looks OKish, then created an account at RTD, synced accounts, uploaded manually the whole NodeMCU tree and fought with the RTD to render 'dev' instead of 'latest'. Took few hours but didn't quite succeed: http://joynodemcu.readthedocs.io/en/dev/en/lua-developer-faq.html
All in all I spent like four hours on this single sentence fix. Not quite encouraging. Hopefully I learnt something along the way.

**Comment by marcelstoer** [comment]
Woah, kudos for all the effort! Just do a `pip install mkdocs` followed by `mkdocs serve` next time.

**Comment by marcelstoer** [comment]
> no idea how to edit in GitHub

Go to https://github.com/joysfera/nodemcu-firmware/blob/master/docs/en/lua-developer-faq.md and click the pen icon next to the trash can.

nodemcu-firmware_lua-developer-faq_md_at_master_ _joysfera_nodemcu-firmware

> joysfera deleted the `joysfera:dev`  branch 2 hours ago

I'll likely want to re-create that before the next PR.

**Comment by cwrseck** [comment]
joysfera - thanks for looking at this.  I steered clear because of my total ignorance of the process, but given your summary I may well take a shot the next time around.

Thanks again - Will

**Pull request merged**
