### PR TITLE
Update information in Readme document.

### PR DESCRIPTION
**Pull request by vowstar**
Edit version and introduction infomation.
Add DHT sensor lib description, a lot of people don't know about it.

### CODE REVIEW

**Comment by nickandrew** [comment]
See #769

**Comment by TerryE** [comment]
@vowstar, If you don't mind -- it would make sense for Nick to cherry pick any inputs here otherwise we will get merge conflicts with both authors working on the readme.

**Comment by nickandrew** [comment]
Done. #817

**Comment by vowstar** [comment]
Thanks!

**Pull request closed without merging**
