### PR TITLE
TTL support in net module

### LINKED ISSUE #1455: Enable TimeToLive for net/UDP
8<------------------------ FEATURE REQUEST ------------------------------------
### Justification

TTL tells routers when to forward IP multicast packets.  A TTL of 0 or 1 restricts UDP to the same subnet; allowing a configurable TTL, or at least a value of 32 would support LUA apps running in on premise in more complicated networks.
Ref: [http://searchnetworking.techtarget.com/definition/time-to-live](url)
### Workarounds

Are there any workarounds you currently have in place because the feature is missing?
no

8<------------------------ END FEATURE REQUEST --------------------------------

### PR DESCRIPTION
**Pull request by djphoenix**
Fixes #1455.

Actually checked only that TTL values changes in Wireshark.
@mikep01 check that it works as you expect if you can.
Also tagging @luismfonseca as net internals expert :)

### CODE REVIEW

**Comment by marcelstoer** [comment]
Ready for merge after the next master drop.

**Comment by luismfonseca** [comment]
> Also tagging @luismfonseca as net internals expert :)

I'm not worthy of this title at all :o

It looks good, if anything I'd propose a different API. This `net` module has a total of `get*` functions, so I think that splitting the get to a separate function: `getttl` could be better. Although, now that I've just typed it, all those `t`s look a bit weird...

**Comment by marcelstoer** [comment]
> It looks good, if anything I'd propose a different API. This `net` module has a total of `get*` functions

4 is not that many 😉 I'm fine with this function being both a setter and getter.

**Comment by mikep01** [comment]
Just got 'round to this and I don't think I can test it.  The net UDP module i/f has changed with a relatively big impact to my lua code.  I'm going to have to stick with my old version rather than try to manage two separate code streams for my users (who already have the old firmware installed).  Sorry about that.

**Comment by mikep01** [comment]
Updated my impl to use 2.1.0 (anticipating a fix for Krack), added and tested the TTL setting for my UDP connections.  It appears to be working well, the packets now flow across my network segments.

**Pull request merged**
