### PR TITLE
ESP32: Add option to set IP/dns config

### LINKED ISSUE #2085: ESP32: Missing feature for wifi setip/sethostname
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
wifi.sta.sethostname() 
wifi.sta.setip()
wifi.sta.setmac()

### Justification
Really miss this functionality in ESP32

8<------------------------ END FEATURE REQUEST --------------------------------

### PR DESCRIPTION
**Pull request by x-logLT**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

This commit adds support for setting:
* Hostname
* Static IP / Dns server (Sta mode)
* Changing AP network ip config
* Setting DNS server IP for DHCP

Fixes #2085 

For now this is for testing/feedback, I'll add documentation then I have more time.

### CODE REVIEW

**Comment by devsaurus** [comment]
Interesting addition, thanks.

I don't yet understand how the decision for DHCP vs. fixed IP is taken in station mode. Is this implicit by calling the API function?

**Comment by x-logLT** [comment]
Yes, the API fuction first disables DHCP client and then sets the IP for that network interface.

**Comment by devsaurus** [comment]
Do the functions have to be called before `wifi.sta.connect()` then?
What is the interaction when `wifi.sta.config()` was configured for automatic connection? Like in
```lua
wifi.sta.config({ssid="mynet", password="12345678", auto=true}, true)
```

**Comment by x-logLT** [comment]
It can be called at any point as it does not interact with wifi stack, but with lwip. Also because of this, network config is not saved to wifi nvs.

**Comment by devsaurus** [comment]
> network config is not saved to wifi nvs.

Ok, maybe we should add to the docs then that in case of configured auto connection the IP config is always done with DHCP after boot.

Regardless of this details, the ability for manual config is a meaningful addition :+1:

**Comment by jpeletier** [comment]
Besides documentation, what else is preventing this PR from being merged?

**Comment by devsaurus** [comment]
> Besides documentation, what else is preventing this PR from being merged?

Nothing IMO.

**Comment by devsaurus** [comment]
@x-logLT do you plan to add documentation soon?

**Comment by x-logLT** [comment]
Was swamped with other work, but back now, should sort it out till the end of the week

**Comment by LDmitryL** [comment]
@x-logLT Do you have the ability to add another option **"mode"** to set the _"Wi-Fi Protocol mode 802.11 bgnlr"_. Interest is the mode: 

> Long Range (LR) mode is an Espressif-patented Wi-Fi mode which can achieve a one-kilometer line of sight range. It has better reception sensitivity, stronger anti-interference ability and longer transmission distance than the traditional 802.11 b mode.

**Comment by x-logLT** [comment]
@LDmitryL  it should be possible, maybe also create new feature request.

**Comment by LDmitryL** [comment]
> @LDmitryL it should be possible, maybe also create new feature request.

@x-logLT I already created a request #2611! But nobody wants to help me! Now you're my "last hope"

**Comment by devsaurus** [comment]
@x-logLT can we expect documentation?

**Comment by x-logLT** [comment]
@devsaurus pushed documentation commit a while ago.

**Comment by devsaurus** [comment]
@x-logLT ah, missed that, sorry.
@marcelstoer you flagged requested changes for this pr - all resolved then?

**Pull request merged**
