### PR TITLE
Merge dev to dev096

### PR DESCRIPTION
**Pull request by vowstar**
Merge dev to dev096

### CODE REVIEW

**Comment by clixx-io** [comment]
Hello,

I'm trying to use this, but just struggling a bit.

Where can I find the .bin file for this?

I've done this, but I can't seem to get different .bin files than are in
the Master tree. Any Suggestions?:

C:\Users\David Lyon\esp8266\nodemcu-firmware>git checkout -m dev
M       tools/esptool.py
M       tools/makefile.sh
Branch dev set up to track remote branch dev from origin.
Switched to a new branch 'dev'

C:\Users\David Lyon\esp8266\nodemcu-firmware>git branch
* dev
  master

C:\Users\David Lyon\esp8266\nodemcu-firmware>git checkout -m dev096
M       tools/esptool.py
M       tools/makefile.sh
Branch dev096 set up to track remote branch dev096 from origin.
Switched to a new branch 'dev096'

C:\Users\David Lyon\esp8266\nodemcu-firmware>git pull
Already up-to-date.

**Comment by GeorgeHahn** [comment]
The binaries in the repository are pretty old.

[This](https://github.com/nodemcu/nodemcu-firmware/releases) is probably the newest build around; if you want something newer or from a dev branch, you probably need to build it yourself.

**Comment by clixx-io** [comment]
Hi George, thanks.

I tried that firmware. Still no ws2812

C:\Users\David Lyon\esp8266>python esptool/esptool.py -p COM4: write_flash
0x000
00 nodemcu-firmware_v20150213.6.bin
Connecting...
Erasing flash...
Writing at 0x00062200... (100 %)

Leaving...

> ws2812.writergb(4, string.char(255, 0, 0))

stdin:1: attempt to index global 'ws2812' (a nil value)

>

Ok, thanks for the tip - I'll figure out how to build it.

**Comment by GeorgeHahn** [comment]
Ws2812 was actually disabled a few weeks ago - if you go through the commit history, you should see the commit that did it.



—

**Pull request merged**
