### PR TITLE
Update to SDK 1.5.4

### LINKED ISSUE #1144: Upgrade SDK to 1.5.3
PR #917 mentioned waiting for 1.5.2. It seems this is out now. Not sure I have the expertise to create a PR for it but figured it should be tracked. 

http://bbs.espressif.com/viewtopic.php?f=46&t=1702

### PR DESCRIPTION
**Pull request by djphoenix**
Build success, bootup success, seems like all features keeps working.
Seems like CI using "esp-open-sdk.zip" from tools folder, maybe needed to update also. 

Fixes #1144, #884.

### CODE REVIEW

**Comment by marcelstoer** [comment]
@dnc40085 can I ask you to also verify this branch against #1231 and the new `wifi_fpm_auto_sleep_set_in_null_mode` function?

**Comment by marcelstoer** [comment]
Thanks a lot Yury!

> Seems like CI using "esp-open-sdk.zip" from tools folder, maybe needed to update also.

Yes, that may be. If you want to change it and create a PR please look at #884 first.

**Comment by djphoenix** [comment]
@marcelstoer updated it, CI green.

**Comment by dnc40085** [comment]
>@dnc40085 can I ask you to also verify this branch against #1231 and the new `wifi_fpm_auto_sleep_set_in_null_mode` function?

Tested and verified, everything seems to be working fine.

+1 for this PR

**Comment by marcelstoer** [comment]
Thanks Yury but you didn't actually fix #884, did you? AFAICS you updated the tool chain and compressed it with XZ instead of GZ. This shrinks the compressed file from 32MB to 20MB. However, the uncompressed content grew from 105MB to 112MB which indicates you didn't strip out libs and sources we don't need.
I quickly deep-diffed the two files and their content seems largely identical.

@TerryE when you created #884 you claimed that 
> This will more than half the size of the `.tar.xz` file compared to the `.tar.gz` version

from which I conclude you did, at that time, have a list of stuff you removed from the tool chain?

**Comment by djphoenix** [comment]
I don't really know which stuff can be stripped out without affection to build process. If you can prepare list of excluded files (or possible white-list?), I'll repack it.

**Comment by djphoenix** [comment]
@marcelstoer @TerryE what's new?
Propose land this PR at current state and reopen (bump) 884 to get sdk smaller...

**Comment by TerryE** [comment]
@marcelstoer @djphoenix Yuri, I'll take a look today and post back.

**Comment by marcelstoer** [comment]
@djphoenix I actually suggested you create a separate PR for the SDK upgrade.

**Comment by djphoenix** [comment]
If it would not break/corrupt build - OK, will cleanup this PR and we landed.

**Comment by djphoenix** [comment]
@marcelstoer ready to land or not (then why?)

**Comment by TerryE** [comment]
>  Yuri, I'll take a look today and post back.

Sorry working 12 hrs a day on the house at the moment -- we've got two crews in and I am dancing around trying to avoid stopping them.   I know that I am being a blocker here, but I do suggest that this needs full review, if not by me then by one of the other committers :(

Again -- Sorry Yuri.

**Comment by marcelstoer** [comment]
Terry, your comment primarily concerns the tool chain changes (#884), right? They're no longer part of this PR.

As for the SDK upgrade I will verify what I can today and/or tomorrow.

**Comment by marcelstoer** [comment]
@djphoenix I did some testing tonight (wifi, node, gpio, net, http, mqtt, spi) - looks good apart from two tiny issues. You forgot to update the NodeMCU version in a couple of places:
- https://github.com/nodemcu/nodemcu-firmware/blob/dev/README.md (search for 1.5.1)
- https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/include/user_version.h#L9
I'll merge once this is fixed.

**Comment by djphoenix** [comment]
OK, updated all references that I was found.

**Pull request merged**
