### PR TITLE
WIP: Espconn delenda est

### PR DESCRIPTION
**Pull request by nwf**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

These are addressing #3004, but there is a long way to go.  Still, open PRs early and often!

### CODE REVIEW

**Comment by TerryE** [comment]
My goodness, someone else with a smattering of Latin!! I will put this on my TODO list

**Comment by TerryE** [comment]
@nwf Nathaniel just scanning through the top level diff, this seems to be more trimming of dead code.  I can't see any material patching to live code, so IMO this is a case of "does it compile and link" andI am happy to fully delegete sign-off to you on this.

**Comment by nwf** [comment]
So far yes, all I've done is remove unused code, since that was very easy to do and, importantly, test.  The longer-term goal is indeed to rip out `espconn` in its entirety because it's just needless abstraction over LwIP.

**Comment by TerryE** [comment]
@nwf Nathaniel, can I leave you to resolves the conflicts and do the merge?  Thanks.

**Review by TerryE — APPROVED** [review]
@nwf Nathaniel, can I leave you to resolves the conflicts and do the merge? Thanks.

**Pull request closed without merging**
