### PR TITLE
SSL rampage

### PR DESCRIPTION
**Pull request by nwf**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

Update us to mbedtls 2.17 and then angrily rampage around Espressif's goo.  It turns out that they basically have a second lwip just for SSL.  This is completely bogus and should go away.  Some of it can go away right now because it's unused; the rest is used and will require, among other things, making our primary lwIP build with NO_SYS==0, which requires some understanding of mutexes and such.

Anyway, this is not really a PR per se so much as a request for review and guidance.

### CODE REVIEW

**Comment by marcelstoer** [comment]
@TerryE would it be a problem for you if we merged this ahead of your large #2912? The changes are confined to mbedTLS.

**Comment by nwf** [comment]
If it's good to go, let me make sure that we're sync'd up with mbedtls 2.17 before landing this one.

**Comment by pjsg** [comment]
Does this mean that we can now configure the incoming/outgoing ssl buffers independently? This will significantly improve interoperability and memory consumption!!

**Comment by marcelstoer** [comment]
>...2.17 seems still-born? Or we could stick with 2.16.3...

I wasn't able to work out their release strategy. However, as per https://tls.mbed.org/tech-updates it seems 2.16 is their newest LTS branch. That maybe explains why 2.17, 2.18, etc. aren't announced and the only exist as tags (but not releases) on GitHub. The latest in this line currently is 2.19.1.

**Comment by TerryE** [comment]
@marcelstoer,  we're going to have to do an intelligent rebaseline /  merge anyway, and we're not getting the testing effort that we really need so let's unblock some of these critical issues for now.

**Comment by nwf** [comment]
@marcelstoer In that case, I guess the "go big or go home" is 2.19.1.  I'll see if jumping up breaks anything for us when I have a minute.

@pjsg Oh, that would be kind of nice, but I think we should keep the 4K buffer sizes as the default.

@TerryE I apologize for having not had time to do any real work on NodeMCU in months.  Day job significantly ramped up its time consumption.

**Comment by pjsg** [comment]
I would leave them as 4k each for now, but we could change the incoming one to 6k and the outgoing one to 2k and significantly improve interoperability without consuming extra memory.

**Comment by dtran123** [comment]
@pjsg , did you mean MBEDTLS_SSL_MAX_IN_CONTENT_LEN and MBEDTLS_SSL_MAX_OUT_CONTENT_LEN. I am not sure if this is supported on the latest mbedtls ?

**Comment by pjsg** [comment]
I checked some time ago (maybe a year or more ago), and it was a feature in the current version of mbedtls, but not in the version that was in our codebase. This PR is adding support for the IN/OUT_CONTENT_LEN and we can use that fact to improve our interoperability without increasing the total RAM demands.

**Comment by dtran123** [comment]
Super. That opens open up new possibilities for sure to control/tune the in and out buffers!

**Comment by nwf** [comment]
This is a very slightly less aggressive rampage now, in that it lands the latest commit on the 2.16.3 series, which is the latest one they seem to believe in supporting.  However, importantly, this series now includes a test program (`lua_tests/tls-test.expect`) that performs some basic sanity checking of the TLS stack.  I intend to expand this functionality, and I think this kind of test infrastructure is what we want for #2145.

**Comment by nwf** [comment]
I have moved the test infrastructure out to its own PR, #2983, as I do not think it should be blocked by TLS changes.

**Comment by marcelstoer** [comment]
@TerryE do you mind if we land this on `dev` now or would it cause too much (merge) trouble?

**Comment by nwf** [comment]
Given TerryE's thumbs up, I'm going to go ahead and click merge.  Sorry if this breaks anything for anyone.

**Pull request merged**
