### PR TITLE
Add streaming support for hx711 device

### LINKED ISSUE #2733: Add support for reading continuously from an HX711
### Missing feature
The current HX711 module does not allow you to read continuous values from the ADC. 

### Justification
This is very useful if you are trying the chart a timeseries. The HX711 comes with two speeds -- 10Hz and 80Hz -- selected by a hardware pin. It would be nice to read the data at that rate. 

### Workarounds
None

### PR DESCRIPTION
**Pull request by pjsg**
Fixes #2733 .

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

The current hx711 is deficient in a couple of ways. It only allows reading from channel A with a fixed gain, and it only supports single reads. This PR fixes both of these problems by allowing the full choice of inputs and gains, and also adds a streaming callback interface that returns multiple samples in a buffer. The sample rate is either 10Hz or 80Hz -- and this depends on how the hardware is configured (i.e. it isn't software controllable).

### CODE REVIEW

**Comment by marcelstoer** [comment]
Ideally we could get the original author @christakahashi to review this but that's probably unlikely to happen.

**Comment by christakahashi** [comment]
I'm no longer equipped to test this code.  I can read it over to check that it appears to work right for the HX711 hardware.  If that's helpful let me know.

**Comment by marcelstoer** [comment]
> I can read it over to check that it appears to work right

Sure, any type of review is certainly welcome.

**Comment by marcelstoer** [comment]
Argh, this failed CI. @pjsg would you mind taking a look?

```
hx711.c:18:1: error: unknown type name 'task_handle_t'
 static task_handle_t tasknumber;
 ^
hx711.c: In function 'hx711_data_available':
hx711.c:117:5: error: implicit declaration of function 'task_post_medium' [-Werror=implicit-function-declaration]
     task_post_medium(tasknumber, control->active);
     ^
hx711.c: In function 'luaopen_hx711':
hx711.c:332:3: error: implicit declaration of function 'task_get_id' [-Werror=implicit-function-declaration]
   tasknumber = task_get_id(hx711_task);
   ^
cc1: all warnings being treated as errors
../../Makefile:422: recipe for target '.output/eagle/debug/obj/hx711.o' failed
make[2]: *** [.output/eagle/debug/obj/hx711.o] Error 1
make[2]: Leaving directory '/home/travis/build/nodemcu/nodemcu-firmware/app/modules'
../Makefile:380: recipe for target '.subdirs' failed
```

Source: https://travis-ci.org/nodemcu/nodemcu-firmware/jobs/583107655#L1187

**Comment by TerryE** [comment]
Marcel, do whatever works best. This is a one off that I can cope with. 😊

**Comment by pjsg** [comment]
Yes -- I'll fix it up tomorrow. My guess is that some header inclusion stuff changed since I submitted it. It builds fine on my local system (or it did a few months ago)

**Pull request merged**
