### PR TITLE
ESP32: Ledc driver module

### PR DESCRIPTION
**Pull request by larsstenberg**
Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

Started on LEDC module, this is work in progress started pull request to get early feedback since this is my first module.

### CODE REVIEW

**Comment by jmattsson** [comment]
I suspect we might need some strategy around the timer usage, but this looks like a good start. @devsaurus you're way more across the ESP32 stuff than I am at the moment, would love your thoughts here :)

**Comment by jmattsson** [comment]
@larsstenberg give us a shout when you want us to have a thorough review here :)

**Comment by larsstenberg** [comment]
Well now would be ok :)

**Comment by larsstenberg** [comment]
Makes sense, i will make a object oriented approach instead =)

**Comment by larsstenberg** [comment]
ledc

Seems to be working great =)

**Pull request merged**
