### PR TITLE
Disabled automatic detection of larger flash sizes

### PR DESCRIPTION
**Pull request by Manawyrm**
The autodetection is broken and causes a number of strange reliability issues, see here: 
http://www.esp8266.com/viewtopic.php?f=18&t=1418&p=9082#p9082
and here: 
http://www.esp8266.com/viewtopic.php?f=18&t=1180

and numerous other threads in the esp8266 forum. 

Of course this is not a fix, but it will work as a workaround to fix the crashes on short term.

### CODE REVIEW

**Comment by vowstar** [comment]
Sorry for that we can only accept PR to dev instead master.
https://github.com/nodemcu/nodemcu-firmware/issues/176
This issue we will consider, because many people use the 4MByte or other flash larger than 512kBytes.

**Comment by MarsTechHAN** [comment]
How about the first time auto detection, And save data in somewhere in Flash?

**Comment by vowstar** [comment]
I guess I have find the solution, waiting a PR

**Comment by Manawyrm** [comment]
Sounds good. Shall I then close this PR?

**Comment by vowstar** [comment]
Keep this as an issue, waiting us final fix.

**Comment by vowstar** [comment]
I think this issue is fixed. Please test.

**Pull request closed without merging**
