### PR TITLE
SDK-3.0 tranche updates

### LINKED ISSUE #2729: Build against recent SDK version rather than original release
Follow-up to https://github.com/nodemcu/nodemcu-firmware/issues/2689#issuecomment-484037820

We used to pull in the latest revision of an SDK IIRC. With 3.0 we seem to have switched to using the initially released version.

Unless there are really good reasons that speak against it we should be using the latest revision to profit from any upstream fixes.

> so that the builder can decide whether to select the Release SDK or the latest (as at the Makefile)

I disagree. We should stick to a version we are happy with. That way we can provide a known to be working combination to our users. I don't think it help contribute to our effectiveness if we had to handle issues here that really are SDK issues. Whatever breaks will be reported here.

### PR DESCRIPTION
**Pull request by TerryE**
Fixes #2729, #2743,  #2751 and #2754 

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/*`.  _Not applicable_

### Changes in this PR

-  `Makefile` now supports different SDK versions as per #2729.  The default is the latest SDK 3.0.1-dev (e4434aa) version.
-  `app/Makefile` now includes the `-DMEM_DEFAULT_USE_DRAM` and `app/lua/lauxlib.c` explicitly allocates dram.
-  `app/include/user_config.h` adds IRAM_DATA_ATTR to map static data into iRAM. `ld/nodemcu.ld` adds the `.iram0.data.` psects to iRAM.
-  `app/esp-gdbstub/gdbstub.c`, `app/lua/lrotable.c`, `app/lwip/core/dns.c`, `app/user/user_main.c`, `app/spiffs/spiffs.c` add IRAM_DATA_ATTR to some static data elements.
- `node.c` one line fix for #2754
- `tools/nodemcu-partition.py` fix pathing issue.

We probably need to have some 3.0 SDK overview, but I will do this as a separate PR.

### CODE REVIEW

**Comment by TerryE** [comment]
I see that the [Travis build for Windows luac.cross](https://travis-ci.org/nodemcu/nodemcu-firmware/jobs/533552759) failed.  I need to investigate why.

**Comment by EgorOA** [comment]
Sorry, but todays build (built by https://nodemcu-build.com/)
[nodemcu-dev-19-modules-2019-05-17-20-20-16-integer.zip](https://github.com/nodemcu/nodemcu-firmware/files/3193128/nodemcu-dev-19-modules-2019-05-17-20-20-16-integer.zip)
is not running properly. It does cycle reboot with such message
>Formatting file system. Please wait...
>
> ets Jan  8 2013,rst cause:2, boot mode:(3,6)
>
>load 0x40100000, len 17248, room 16 
tail 0
chksum 0x4b
load 0x3ffe8000, len 2592, room 8 
tail 8
chksum 0x92
load 0x3ffe8a20, len 8, room 0 
tail 8
chksum 0xb6
csum 0xb6

and so on...

**Comment by NicolSpies** [comment]
@TerryE, after flashing the image built using Docker with the following feedback:

`SDK ver: 3.0.1-dev(fce080e) compiled @ Apr 16 2019 15:02:05
phy ver: 1145_0, pp ver: 10.2`
`Formatting file system. Please wait...` 
`boot not set`
`ota1 not set`
`ota2 not set`
`rf cal sector: 11`
`freq trace enable 0`
`rf[112] : 00`
`rf[113] : 00`
`rf[114] : 01`
A reboot follows and the cycle repeats.

I have used `#define LUA_FLASH_STORE` to define the size during compile time. Where should I set the parameters indicated as not set ?

**Comment by TerryE** [comment]
@EgorOA  @NicolSpies. Yup, I get the same if I don't use `nodemcu-partition.py` to set up the partition table.  I will track down the issue in the debugger and push a fix today.

**Comment by NicolSpies** [comment]
@TerryE , the max LFS size is 256Kb (`#define LUA_FLASH_STORE 0x40000`), I am already need 128Kb (`#define LUA_FLASH_STORE 0x20000`). What about setting it to max as default and using `#define FLASH_AUTOSIZE` as default. The first format will then take long. After that if required users can use `node.setpartitiontable()` to set the `lfs_size` and `spiffs_size` respectively to requirements. After that formatting and access times will be faster according to the new settings.

**Comment by TerryE** [comment]
> The first format will then take long

The problem with this is that there is no visual feedback of progress or that the formating is underway if you connect to the UART after the initial `Formatting file system. Please wait..`  It would be better if the formatter did a `...` progress bar, writing a dot every 100Kb formatted, say.  Anyway, I am doing a bot of NodeMCU wokr later.  I'll take a look.

**Comment by TerryE** [comment]
We are crashing randomly inside the Espressif SDK 3.0 version of the `flash_erase()` function.  More investigation needed.

**Comment by TerryE** [comment]
I don't think that we should be discussing an open issue on a closed PR, so I have opened this as a separate issue to track it properly.

**Pull request merged**
