### PR TITLE
trailing spaces cleanup

### LINKED ISSUE #2648: Please cleanup trailing spaces
There are a lot of trailing spaces that reduces readability and should be cleaned up.

### PR DESCRIPTION
**Pull request by c-e-p-x-u-o**
Fixes #2648

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

There are a lot of trailing spaces that reduces readability and should be cleaned up.

### CODE REVIEW

**Comment by c-e-p-x-u-o** [comment]
Sorry, last three commits should go into separate pull request. Could you discard them?

**Comment by marcelstoer** [comment]
> Could you discard them?

Nope. You should reset your branch to 310c3a7 and force-push the branch.

**Comment by c-e-p-x-u-o** [comment]
> reset your branch

I've deleted c-e-p-x-u-o/nodemcu-firmware and forked it again.
Is it still possible to do this?

**Comment by marcelstoer** [comment]
Nope, then you need create a new PR -> closing

**Comment by c-e-p-x-u-o** [comment]
Sorry for this, I'll be more careful next time.

**Comment by marcelstoer** [comment]
No worries. See if you find https://github.com/nodemcu/nodemcu-firmware/blob/master/CONTRIBUTING.md#working-with-git-and-github helpful.

**Pull request closed without merging**
