### PR TITLE
Added node.setcpufreq(mhz) function.

### PR DESCRIPTION
**Pull request by markusgritsch**
This function allows setting the CPU frequency to node.CPU80MHZ or node.CPU160MHZ.

Forum: http://www.esp8266.com/viewtopic.php?f=21&t=1369

### CODE REVIEW

**Comment by eliabieri** [comment]
Nice, waited a long time for this.

-- 

Elia Bieri
whateveryouwant@eliabieri.com

**Comment by nodemcu** [comment]
tested and wouldn't smoke 8266 right? :)

**Comment by markusgritsch** [comment]
No worries. It's safe :)

**Comment by markusgritsch** [comment]
While we're at it, has anyone an idea why the linker gives me an out of memory error when compiling the dev branch in float mode?  http://www.esp8266.com/viewtopic.php?f=23&t=2030
I mean, it seems that travis-ci does not have this problem.

**Pull request merged**
