### PR TITLE
Fix some bugs and problems in gossip

### PR DESCRIPTION
**Pull request by HHHartmann**
Fixes issues in gossip.

- [x] This PR is for the `dev` branch rather than for the `release` branch.
- [x] This PR is compliant with the [other contributing guidelines](/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

During working with gossip I found some bugs and weaknesses.

### CODE REVIEW

**Comment by HHHartmann** [comment]
Please review and/or merge

**Comment by HHHartmann** [comment]
@alexandruantochi would you care to have a look?

**Comment by HHHartmann** [comment]
Anyone mind if I merge this?

**Comment by marcelstoer** [comment]
I'll merge it. It's been up for review for nearly two weeks, the original author didn't even reply...you did what you could.

**Comment by HHHartmann** [comment]
Thx

**Pull request merged**
