### PR TITLE
Implement SDK event monitor

### PR DESCRIPTION
**Pull request by dnc40085**
This PR implements the SDK event monitor discussed in issue #870

### CODE REVIEW

**Comment by dnc40085** [comment]
Hmmm, compiled fine locally...

**Comment by TerryE** [comment]
Time to enable cross references and digging into the map file. :smile:

**Comment by dnc40085** [comment]
I have no idea where I would even start

**Comment by TerryE** [comment]
I am not sure why you should be blowing up on iram1.  Johnny has done a lot to trim this back, so the point where you shouldn't have an issue.  The mapfile is at `app/mapfile` and the content is pretty self explanatory if you've looked at linker outputs before.  You need to read this in concert with the `ld` files.

**Comment by dnc40085** [comment]
I cant figure out how to reproduce this error locally, with all the default modules enabled, the compiler never spits out any errors. However, when I flash my esp-12e it does not boot.

**Comment by dnc40085** [comment]
I found the issue, I was using the `vsprintf` in `app/libc/c_stdio.c` instead of the one in the ROM, which was being added to iram1.

Thank you for the pointers on where to look.

**Pull request closed without merging**
