### PR TITLE
Fixes to softuart module

### LINKED ISSUE #2993: softuart.c:41:51: error: initialization makes integer from pointer without a cast [-Werror]
### Expected behavior
dev branch (commit 8c08e76) compiles

### Actual behavior
```text
CC app/modules/softuart.c
softuart.c:41:51: error: initialization makes integer from pointer without a cast [-Werror]
 static task_handle_t uart_recieve_task = NULL;
                                                   ^
cc1: all warnings being treated as errors
make[2]: *** [.output/eagle/debug/obj/softuart.o] Error 1
../../Makefile:422: recipe for target '.output/eagle/debug/obj/softuart.o' failed
make[2]: Leaving directory '/opt/nodemcu-firmware/app/modules'
make[1]: *** [.subdirs] Error 2
../Makefile:380: recipe for target '.subdirs' failed
make[1]: Leaving directory '/opt/nodemcu-firmware/app'
make: *** [.subdirs] Error 2
Makefile:380: recipe for target '.subdirs' failed
make: Leaving directory '/opt/nodemcu-firmware'
```

### Test code
https://github.com/mk-pmb/nodemcu-firmware-daily-vanilla/runs/371915996

### NodeMCU version
dev branch, commit 8c08e76

### Hardware
The Github cloud

### PR DESCRIPTION
**Pull request by galjonsfigur**
Fixes #2993

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.

I would be thankful if @mk-pmb could test it because to reasons unknown to me I couldn't reproduce the warning, even with `-Wall `option added.

### CODE REVIEW

**Comment by KT819GM** [comment]
After fix it compiled, before also got same error as @mk-pmb. Please take a look into `#define I2C_MASTER_OLD_VERSION` on _user_config.h_ it also throws some error if enabled:
`i2c_master.c:176:62: error: value computed is not used [-Werror=unused-value]
             READ_PERI_REG(RTC_GPIO_IN_DATA) & 1; asm volatile("nop;nop;nop;nop;");
`

**Comment by galjonsfigur** [comment]
I found the culprit - I was using older version of the compiler. Current compiler shows more warnings, especially with `Wall` in Makefile inside `modules` folder.
@KT819GM That would require a separate issue and PR - if you want you can open a new issue.

**Comment by KT819GM** [comment]
Apologies for being messy, will do separate issue.

**Comment by mk-pmb** [comment]
> I would be thankful if @mk-pmb could test it

✔ 5278944 builds for esp8266. :+1:

**Comment by NicolSpies** [comment]
@galjonsfigur, I have been testing the softuart send and receive functionality.

**Test Method** 
The **write method** was tested by writing a hex string and using a digital scope to compare the 8N1 frames transmitted with the string written using the softuart module.

The **on data** method (data receive) was tested by monitoring and decoding received 8N1 frames using the scope and comparing it with the data received by the softuart module.

**Results**
Frames written are **transmitted correctly** with 47us intervals between successive  frames when a string of hex numbers are converted to a string using the string.char function and then written using the softuart module.

Sequential frames received are **partially decoded correctly**. 
Every second frame is not decoded correctly. What happens is that the binary frame data received is shifted by one bit to the left for alternate frames. 
E.g. `0011` received is incorrectly decoded to `0110`. This bit shifting happens consistently on every alternate frame received. The first frame received is decoded correctly, the second one received is shifted, the third frame received is decoded correctly, the fourth frame received is shifted,... etc.

**Comment by galjonsfigur** [comment]
@NicolSpies Thanks for extensive testing. I will try to look into this - it's an interesting bug. The only thing I found so far is my mistake [here](https://github.com/galjonsfigur/nodemcu-firmware/blob/e274af1cf402e5c894a6ae2729c0f2194588f90f/app/modules/softuart.c#L117) - it's
```
uint8 next = s->buffer.length + 1 % SOFTUART_MAX_RX_BUFF;
```
but should be
```
uint8 next = (s->buffer.length + 1) % SOFTUART_MAX_RX_BUFF;
```

But I can't test it right now. I will try to make another PR regarding this issue as soon as I will confirm this.

**Comment by NicolSpies** [comment]
:+1: @galjonsfigur, I am not a C expert but it could be the problem. I will implement a workaround in Lua in the mean time and test the PR as soon as it is available.

**Pull request merged**
