### PR TITLE
Next master drop

### LINKED ISSUE #3066: When to drop the next master release
Sorry for opening an issue for this, but it seems right to discuss this in a visible place.

In https://github.com/nodemcu/nodemcu-firmware/pull/3060#issuecomment-610281199
@marcelstoer wrote:

> I think it would be very valuable (and thus welcome by the community) if we merged dev back to master in the coming weeks. It's been almost six months but there are a few things pending: https://github.com/nodemcu/nodemcu-firmware/milestone/14. So, I wouldn't mind landing this on dev soonish as it looks quite mature.

I would like to see some bugs fixed before we merge into master.
Uploading LFS.img with ESPlorer does not work anymore #2963
adc.readvdd33() #2925
enduser_setup "Handling POST" failure on 310faf7 and dev #2931

Especially the upload bug will leave a good part of the community without a working master.
The readvdd33 bug is a regression and I think should be fixed rather sooner than later.
They are both fixed in Terry's branch.
Also the broken enduser_setup should be addressed.

### PR DESCRIPTION
**Pull request by marcelstoer**
Fixes #3066

### CODE REVIEW

**Comment by nwf** [comment]
Looks right to me.

**Comment by marcelstoer** [comment]
Did you see 78ae85be1d7bd7cb0247fdc9446b30b48876b651? That was necessary because we have #3012 on master and dev. I resolved the conflict through the GitHub UI right in the browser.

Should be fine now. But it means that currently `git describe` returns

> 3.0-master_20190907-84-g78ae85be

on `dev` 😉

**Comment by nwf** [comment]
Thanks for fixing my error with #3012.  And I approve of the new `git describe` result.

**Comment by marcelstoer** [comment]
I change my mind and the strategy. The previous approach would have left this repository with a somewhat odd Git history. Instead I rebased `dev` onto `master` and resolved the conflicts from #3017 .
If you approve you can now select & hit that "Rebase and merge" button. Otherwise, the previous state is preserved in `dev-backup`.

**Comment by nwf** [comment]
It's done and I've taken the liberty of pruning `dev-backup`.

**Comment by marcelstoer** [comment]
@nwf Can I ask you to write release notes at https://github.com/nodemcu/nodemcu-firmware/releases? I won't have time for the next 2-3d. (A large part of) The community will have troubles dealing with the changes if there are no release notes to guide them.

**Pull request merged**
