### PR TITLE
Fix potential integer overflow in getnum

### PR DESCRIPTION
**Pull request by Crispy-fried-chicken**
Fix the vulnerability mentioned in https://github.com/nodemcu/nodemcu-firmware/issues/3626

### CODE REVIEW

**Comment by pjsg** [comment]
This should be targeted at the `dev` branch. And we probably need the same fix in the `dev-esp32` branch.

**Comment by Crispy-fried-chicken** [comment]
> This should be targeted at the `dev` branch. And we probably need the same fix in the `dev-esp32` branch.

I've changed the branch to dev, and as for `dev-esp32`, maybe I can create another PR?

**Comment by pjsg** [comment]
Yeah -- create another PR. Thanks

**Comment by Crispy-fried-chicken** [comment]
and I see some checks were not successful, how I change to make it success?

**Comment by Crispy-fried-chicken** [comment]
I've already create another PR which is https://github.com/nodemcu/nodemcu-firmware/pull/3634, please check it, thank you!

**Comment by pjsg** [comment]
Hmm -- I have no idea why the checks failed..... I'm not sure who uses the 8266 dev branch....

**Comment by HHHartmann** [comment]
we need this fix on the release branch to fix the windows build issue:
https://github.com/nodemcu/nodemcu-firmware/commit/193fe3593eb1537667179089535cdb7457327887#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

**Comment by pjsg** [comment]
Can you tee up a PR for that fix?

**Comment by HHHartmann** [comment]
Will do tomorrow

**Comment by HHHartmann** [comment]
Ah no,  As it seems, you just need to rebase this branch onto a current dev branch which will also contain the fix.

**Comment by Crispy-fried-chicken** [comment]
@HHHartmann I don't see any fix about this PR in https://github.com/nodemcu/nodemcu-firmware/pull/3635, maybe you should add it to fix it?

**Comment by HHHartmann** [comment]
@Crispy-fried-chicken sorry, the fix on master is not required. I thought that the check pipleine needed to be updated on the release/master branch. But this is not needed.
Rebasing this branch to dev is what should fix the checks as the correct definition is there.

**Comment by Crispy-fried-chicken** [comment]
@pjsg Hi, is it necessary to apply for a CVE for this vulnerability? This is very important to recognize our work, thank you!

**Pull request merged**
