### PR TITLE
Modified WDT feeder to use new API call.

### PR DESCRIPTION
**Pull request by karrots**
Fixed watchdog timer to use newer API call. Hope this is done right.

### CODE REVIEW

**Comment by karrots** [comment]
What is the correct header file to add to fix errors about the SDK functions not being declared? When I added user_interface.h it made the build not compile.

**Comment by karrots** [comment]
Duplicate of the better #703 PR closing this one.

**Comment by jmattsson** [comment]
Oops, I didn't mean to step on your toes here!

**Comment by karrots** [comment]
No worries. You found the other three my grep didn't find for some reason.

**Pull request closed without merging**
