### PR TITLE
Add support for ws2812 to accept table as a data source.

### PR DESCRIPTION
**Pull request by bbktsk**
Add support for ws2812 to accept table as a data source. Currently, it supports strings only and since lua strings are read only, this causes serious performance issues when working with larger number of LEDs. This commit adds new function write_table_rgb, which accepts a table of three-element rgb tables as an argument.
Also removed some code duplication to clean-up.

### CODE REVIEW

**Comment by TerryE** [comment]
> this causes serious performance issues when working with larger number of LEDs.

Only true if you are using a continuous pallet.  If you are sticking to a fixed set of 16 colours then you will only use 16 strings no matter how many lights.  I would suspect that you will often want runs or repeat patterns so you could consider enriching the vector syntax.  Just a suggestion.

**Comment by bbktsk** [comment]
@TerryE I do not follow. First, limiting myself to 16 colors with device capable of showing 16 millions is, well, limiting. Second, I'm driving a strip of 144 leds and although reusing predefined strings will be faster, I think that overhead of constructing a new control string out of 144 substrings every time will be still much worse than just overwriting a table. Or am I missing something?

**Comment by TerryE** [comment]
At the moment, the EGC is fired after every alloc, so this can slow down apps up to 10x. All I an saying is that sometimes getting good solid performance isn't very intuitive, so it's week with experimenting and benchmarking.

**Comment by bbktsk** [comment]
I found issue #790. Although the solution is different than mine, there's one interesting thing it does: instead of two separate functions for different argument types it uses a single function that dispatches based on argument type. Is this considered a good Lua style? Should I change my pull request to do the same thing?

**Comment by TerryE** [comment]
Why don't you two discuss this and come to a consensus.

**Comment by bbktsk** [comment]
I do not feel strongly one way or the other. My Lua experience is quite
limited and I do not know what is considered a good style with regard to
"overloaded" functions.

On Tue, Dec 22, 2015 at 7:23 PM, Terry Ellison <notifications@github.com>
wrote:

> Why don't you two discuss this and come to a consensus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodemcu/nodemcu-firmware/pull/869#issuecomment-166696236>
> .
>



-- 
--
Bob Koutsky

**Comment by Alkorin** [comment]
@bbktsk I've a current dev which accept a {g,r,b} table on the set function, I'll push it after some code cleaning.

For the moment I achive a rainbow with a 300 leds strips at ~60fps

**Comment by Alkorin** [comment]
Done: https://github.com/Alkorin/nodemcu-firmware/commits/ws2812-buffer

I currently have performance issues due to luaL_checkudata which is slow, if I replace it by lua_touserdata (same thing but without type check...) it's ~5 times faster :)

I've a precalculated colorMap
```
rainbow = {}
for i = 0, 179 do
  rainbow[i] = {makeColor(i*2, 100, 10)}
end
```

And here is my loop:
```
local i, buf = 0, ws2812.newBuffer(300); local set = ws2812.set; tmr.alarm(0, 20, 1, function()
    i = i + 1
    
    local rainbow = rainbow;
    for j = 0,299 do
        set(buf, j, rainbow[(j+i)%180])
    end
    buf:write(4)
end)
```

Current timings are : ~6ms for the loop + 10ms streaming to the strip => >60fps

**Comment by marcelstoer** [comment]
@bbktsk @Alkorin what's your plan with this? At least the code should be rebased on `dev` before we can merge it.

**Pull request closed without merging**
