### PR TITLE
No banner

### LINKED ISSUE #3021: disable startup banner
Please add support for disable startup banner

### Workarounds
comment out `print_version(L);` in `app/lua/lua.c`

### PR DESCRIPTION
**Pull request by 532910**
Fixes #3021.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

\<Description of and rationale behind this PR\>

### CODE REVIEW

**Comment by TerryE** [comment]
@532910 Sergio, you need to read the contribution guidelines.   The main issues here are:

1.  I don't think that we have a consensus on the requirements so a PR is premature IMO.
2.  You need to read the contribution guidelines, and in particular that you should base your changes on a pull of the latest `dev` version and not you potentially out of date version.
3.  IMO the comment in `user_config.h`is far too verbose.

But let's get one sorted first.

**Comment by marcelstoer** [comment]
I fixed 2. by changing the base from master to dev here on GitHub.

> add x inside the brackets

This was ignored so I fixed that as well BUT 

> PR is premature IMO

is still valid of course.

**Comment by 532910** [comment]
1. Agree!
2. I've read https://github.com/nodemcu/nodemcu-firmware/blob/master/CONTRIBUTING.md
Could you explain what have I done wrong? The steps I did:
* Forked from github web interface
```
% git clone git@github.com:532910/nodemcu-firmware
% cd nodemcu-firmware
% git checkout -b no-banner origin/dev
# modified files
% git push origin HEAD
```
* PR via github web interface

**Comment by marcelstoer** [comment]
> Could you explain what have I done wrong? The steps I did:
...
PR via github web interface

When you do this you need to select the "base" branch i.e. the one you want the PR to be merged into - which is normally the same you branched from. GitHub always suggests the default branch but you need to change that to `dev`. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#creating-the-pull-request -> step 4

You can easily verify that because the list of commits/changes in the PR is really long if you select the wrong base branch. If you picked the wrong one you can hit the "Edit" button at the top-right and [correct it](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository). That's what I fixed.

**Comment by nwf** [comment]
Just as a point of interest, in the non-interactive test framework I've been prototyping, I rely on the startup banner to detect when the device has booted as expected or rebooted unexpectedly.  I'm not sure why its presence would be a problem.  Moreover, I'm jittery about removing it entirely given that we get so many bug reports from people who really need to read it (#2903) -- if it were gone, there'd be no chance of them reading it, rather than merely a slim chance.

**Comment by 532910** [comment]
@nwf, see #3021. The banner is for users and development process. But it's bad for other devices.
For example I have a serial screen and I want no messages to be send to it without my permission.

**Comment by marcelstoer** [comment]
I'm ok with this as long as it's enabled by default.

**Comment by 532910** [comment]
It should be enabled by default, of course.

**Comment by nwf** [comment]
This PR looks fine to me (though I might suggest changing "very helpful for bug reports" to "mandatory for bug reports"), but...

You will probably be better served by changing the hardware a bit:
* a bit-bang UART on a GPIO entirely under your control,
* an AND gate and a GPIO gating one of the existing hard UARTs, or
* a dedicated UART chip (e.g. via I2C and a SC16IS740) that won't be spoken to without your permission.

**Comment by 532910** [comment]
> an AND gate and a GPIO gating one of the existing hard UARTs, or

Yes, that's exactly what I did.

**Comment by 532910** [comment]
> "very helpful for bug reports" to "mandatory for bug reports"

agree

**Comment by 532910** [comment]
> When you do this you need to select the "base" branch i.e. the one you want the PR to be merged into - which is normally the same you branched from.

Clear, Marcel thank you for comprehensive explanation!

**Pull request merged**
