### PR TITLE
Add support for BH1750FVI ambient light sensors

### PR DESCRIPTION
**Pull request by pawel-sw**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

### CODE REVIEW

**Comment by devsaurus** [comment]
Please add I2C id as parameter to the Lua functions, also see https://github.com/nodemcu/nodemcu-firmware/pull/2249#issuecomment-370220435.

**Comment by s-pw** [comment]
@TerryE it is a stateless component. If you store i2c_id during setup, you won't be able to use 2 sensors on 2 separate I2C buses.

**Comment by TerryE** [comment]
> @TerryE it is a stateless component. If you store i2c_id during setup, you won't be able to use 2 sensors on 2 separate I2C buses.

So what happens when you setup bus 0 and attempt to read bus 15243523 or even bus 1?    This is an ambient light sensor.. If the manufacturers really thought that the same bus master was going to need to read two sensors then the'd have exposed a couple of address pins as pull up / down pins on the IC.

**Comment by mickley** [comment]
I'm currently using a setup with two BH1750FVI sensors and my own lua module, and could forsee needing to use more than two.  The BH1750 actually does have an address pin too, so two are supported on the same bus, which is what I am doing.  This module doesn't have an option to use I2C address 0x5C (@s-pw).

Moreover, I think needlessly restricting useful features and forcing hack-style programming for stuff like multiple sensors is bad form.  I've had the same problem with BME280, which doesn't support multiple sensors on the same bus (#2241 ).  These are the sorts of basic things that should be supported for every sensor!

**Comment by TerryE** [comment]
> I think needlessly restricting useful features and forcing hack-style programming for stuff like multiple sensors is bad form

In which case the setup should return a userdata object and all further references should use use Lua class features.  I didn't suggest that you should hack this.  Do single instance _or_  multi-instance properly.

**Pull request closed without merging**
