### PR TITLE
ESP8266 add webserver module

### PR DESCRIPTION
**Pull request by NiklausS**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

#2956

\<Description of and rationale behind this PR\>

This is a simple webserver. The reason i have written it initially was to allow for a web based develop environment. It is written as a c module as i run to often into memory shortages (this was before LFS). Furthermore especially the upload feature required some small additions in the net.c to achieve a decent performance and stability.

The main changes are the additions of the functions from httpd.c, the changes in net.c are basically the move from the local typedefs into a net.h, the addition of the hooks to the net_recv_cb, net_err_cb, net_sent_cb, net_listen and net_close. By intercepting earlier to received data, it can be written faster and expecially without furher memcopy to flash.When receiving a 500k file there is usually never more then 6k mem used.

### CODE REVIEW

**Comment by marcelstoer** [comment]
For the reasons stated in #2956 I vote to close this.

**Comment by HHHartmann** [comment]
+1 from me.

**Comment by NiklausS** [comment]
Well, that's sad.
It's was so super convenient and fast to upload and test lfs.images while i had some trouble lately with ESPlorer.
i really got used to this:

```
curl -H Expect: --data-binary @luac.out.1574191913 http://192.168.1.204/up\?filen=lfs.img
echo "node.flashreload ('lfs.img')" | curl -m 1 -d @ - 'http://192.168.1.204/cmd'
```

and other automated testcases.

In this case, it probably makes no sense if I also provide the patch for the dev-esp32.

**Comment by pjsg** [comment]
For easy upload, I run a tftpd server on the esp8266 and then when it gets the complete lfs.img, it automatically flashes it and restarts.

**Comment by NiklausS** [comment]
i know the tftpd, but when you want to upload from a browser out of javascript this does not work. Furthermore is the tftpd not for interactive commands in (REST).

**Comment by marcelstoer** [comment]
Do the Lua HTTP servers we mentioned not support POSTing/uploading binary data?

**Pull request closed without merging**
