### PR TITLE
Update mqtt.c fix for #679

### PR DESCRIPTION
**Pull request by kvakanet**
Patch for  "mqtt LWT qos and retain parameters are parsed incorrectly #679"

### CODE REVIEW

**Comment by marcelstoer** [comment]
That PR looks odd. Why do you have so many commits? The PR should actually just contain a single commit https://github.com/kvakanet/nodemcu-firmware/commit/3f3da64886650f1d9f83fde34b7753554ce4df11, no?

**Comment by kvakanet** [comment]
Hello!
The first time I do it.
Sorry.

**Comment by jmattsson** [comment]
Looks like this was a commit on master, not on dev. @kvakanet could you please rebase the PR so it's on top of dev, not master? (and re-test after that, naturally)

**Comment by karrots** [comment]
This can be closed due to the merging of #718

**Pull request closed without merging**
