### PR TITLE
Merge dev to dev096

### PR DESCRIPTION
**Pull request by vowstar**
Merge dev to dev096, make it latest.

### CODE REVIEW

**Comment by pastukhov** [comment]
on dev with 87341547d7ef9568387f2f13be16ef8109443682
```lua
> =dht.read(2)
0	0	24	400	600
```

**Comment by vowstar** [comment]
@pastukhov  Can you change a pin or wire? That's so strange ...

**Comment by pastukhov** [comment]
```lua
> =dht.read(5)
0	0	27	100	800
> =dht.read(5)
0	0	25	200	400
> =dht.read(5)
0	0	25	200	200
> =dht.read(5)
0	0	24	200	800
> =dht.read(5)
0	0	24	200	600
> =dht.read(5)
0	0	24	200	600
> =dht.read(5)
0	0	24	200	500
> =dht.read(5)
0	0	24	200	400
> =dht.read(5)
0	0	24	200	400
> =dht.read(5)
0	0	24	200	300
> =dht.read(5)
0	0	24	300	300
> =dht.read(5)
0	0	24	300	200
> =dht.read(5)
0	0	24	200	200
> =dht.read(5)
0	0	24	300	200
> =dht.read(5)
0	0	24	200	100
> 
```

**Comment by pastukhov** [comment]
@vowstar What module and pin do you use?

**Comment by vowstar** [comment]
@pastukhov Please try latest commit, this bug is fixed.

**Pull request merged**
