### PR TITLE
Add examples to the "bit" module documentation

### PR DESCRIPTION
**Pull request by adrianomelo**
- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

I missed having some examples for the `bit` module when I was checking the available operators. This PR request adds examples to this module.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Looks good, thanks. However, I would also confirm in a comment what the expected result is. Pattern:

```lua
print(bit.xxx(a, b)) -- prints 'n'
```

**Comment by adrianomelo** [comment]
Hey @devsaurus and @marcelstoer, thanks for reviewing the pull request and accepting the contribution. You guys are doing a fantastic job here. I started using the project last week, and everything works out-of-the-box. 

I agree with you @marcelstoer. The examples can have a better format. Maybe we can list some of the options and choose which one is better.

```lua
-- #1 (current)
print(bit.xxx(a,b) == c)

-- #2
print(bit.xxx(a,b)) -- prints c

-- #3
bit.xxx(a,b) -- returns c

-- #4
-- 1 is 0001, 2 is 0010 and it returns 0100 
bit.xxx(1, 2) -- returns 4
```

I like using a simplified binary representation of numbers (fourth option). However, I am not sure if it helps.

**Comment by marcelstoer** [comment]
Thanks for the 💐I like the 4th option best as it's the most expressive.

**Comment by marcelstoer** [comment]
@adrianomelo just to be sure (expectation management on my side), _you_ will update the documentation wrt Lua comments, right?

**Comment by adrianomelo** [comment]
Hi @marcelstoer, yes, I will update it. Sorry for the delay. I should be able to work on it later today.

**Pull request merged**
