### PR TITLE
Reimplement esp_init_data_default without hardcoded data

### PR DESCRIPTION
**Pull request by jimparis**
Fixes #1500.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/en/*`.

This builds upon #1526 from @jmattsson and replaces the hardcoded init data with contents from the SDK.

### CODE REVIEW

**Comment by dnc40085** [comment]
Tested on an esp-12(32m), works as advertised.

**Comment by jmattsson** [comment]
Hah, I wasn't aware of the `.incbin` directive. Learned something new, thanks :)

:+1: from me.

**Comment by marcelstoer** [comment]
I suggest that the `flash.md` changes from #1525 be merged into this PR for consistency reasons. They need to be merged at the same time anyway.

**Comment by jimparis** [comment]
Merged flash.md changes from #1525 and updated it to fit the current situation (which means that a lot of the detail was taken out, since NodeMCU users shouldn't have to care about it).

**Comment by marcelstoer** [comment]
Well done, thanks a lot @jimparis! However, I see no value in removing the init data addresses (https://github.com/nodemcu/nodemcu-firmware/pull/1527/files#diff-48f98dba177e62bebd22ee90be1ee586L79).

**Comment by vowstar** [comment]
Thanks, very cool solution!

**Pull request merged**
