### PR TITLE
Changed the ws2812 byte order from GRB to RGB

### PR DESCRIPTION
**Pull request by markusgritsch**
There seems to be interest in using the more intuitive RGB byte order to
specify the LED color. Also fixed the documentation.

### CODE REVIEW

**Comment by nodemcu** [comment]
Great job and thank you @markusgritsch 
could you pull this request to dev branch first please

**Comment by markusgritsch** [comment]
Created a pull request on dev branch.

**Comment by nodemcu** [comment]
merged to dev

**Comment by markusgritsch** [comment]
Is the module LUA_USE_MODULES_WS2812 in user_config.h disabled deliberately?

**Comment by markusgritsch** [comment]
Sorry, looked in the master branch -- never mind, everything is ok :)

**Comment by nodemcu** [comment]
yes, in master branch. commented out temporary.  because it's device specific.
I was thinking of provide a host/cloud to compile as custom-ed for all general module and device module.

**Comment by markusgritsch** [comment]
I see. It would be nice if the module would be enabled until this custom-compiled firmware feature is available. It uses only very little memory.

**Comment by flokli** [comment]
@nodemcu I'd also highly appreciate if the ws2812 module was enabled out of the box in the master branch as long as there is no solution for costumzied builds.

**Comment by clixx-io** [comment]
Or even if it was a special build ie 'nodemcu-latest-ws2812.bin' , that
would work also. I really wish to try it

**Comment by nodemcu** [comment]
although in dev branch, but now the latest pre_build bin is generated by travis and you can download
here [latest](https://github.com/nodemcu/nodemcu-firmware/releases/latest)

**Pull request closed without merging**
