### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by yeffrimic**
this is my first pull request if I do wrong please tell me :D

### CODE REVIEW

**Comment by TerryE** [comment]
@yeffrimic Yeffri, raise an issue discussing what you are trying to achieve.  We do expect a minimum level of expertise from potential contributors.

**Comment by yeffrimic** [comment]
i want to translate the wiki to spanish version

**Comment by TerryE** [comment]
Are you talking about the Wiki, or the full documentation set within the `docs` subfolder?  Either way, can I first suggest that you don't even bother with a PR but simple fork dev in your own repo and do a couple of pages in your repo for comment and feedback.

**Comment by marcelstoer** [comment]
@yeffrimic look at the recommendations I gave you with #973

**Pull request closed without merging**
