### PR TITLE
Mqtts

### LINKED ISSUE #2626: [esp32] MQTT mutual auth
Trying to get MQTT mutual authentication (client cert) work on esp32.

[Here is my attempt](https://github.com/kevinresol/nodemcu-firmware/commit/bea2c4813306d3c4ebe5a025df66a981120a12fb), trying to pass the cert/key PEM's to esp-mqtt.

And the lua call is:

```lua
mqttClient:connect(host, port, 1, 0, cacert, client_cert, private_key, on_ok, on_nok);
```

However, I am getting this error when connecting:

```
I (11446) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
E (11546) MQTT_CLIENT: Invalid MSG_TYPE response: 9, read_len: 0
I (11546) MQTT_CLIENT: Error MQTT Connected
I (11546) MQTT_CLIENT: Reconnect after 10000 ms
E (11556) MQTT_CLIENT: Client has not connected
```

`read_len` is zero meaning the response (9 in this case) is basically rubbish data in the buffer, we could ignore that.

[`select()`](https://github.com/espressif/esp-idf/blob/e2ae69f/components/tcp_transport/transport_ssl.c#L89) tells us the fd is ready to be read but [actually reading](https://github.com/espressif/esp-idf/blob/e2ae69f/components/tcp_transport/transport_ssl.c#L129) it yields `0` length. I guess that means the socket is closed. But I am not sure why.

I am not a C expert, I would like to have some guide on this problem. Thanks.

### PR DESCRIPTION
**Pull request by kevinresol**
Fixes #2626.

- [ ] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

Adds some options for MQTTS (secure MQTT).
- CA Cert (to verify server)
- Client Cert and Key (to let server verify client)

### CODE REVIEW

**Comment by kevinresol** [comment]
tbh I am don't like this API very much. There are too many arguments and I think using a table would be more appropriate.

**Comment by devsaurus** [comment]
Thanks a lot for your submission @kevinresol!

> There are too many arguments and I think using a table would be more appropriate.

I share this impression, but I don't have a proposal at the moment.
* Just the options related to the certificate in a table?
    `mqtt:connect(host[, port[, secure[, autoreconnect]]][, cert_table]][, function(client)[, function(client, reason)]])`
* Move everything into a table?
    `mqtt:connect(parameter_table)`
* Keep `mqtt:connect()` as it is and use a dedicated function to set up this before calling `connect()`?
    `mqtt:config(config_table)`

Any other ideas?

**Comment by jpeletier** [comment]
Hello @kevinresol & @devsaurus:

I just submitted a rewrite of the MQTT module... I was having a hard time using it. This means we got now a (hopefully) much more stable implementation and I know the details very well. The new source is heavily documented, so anyone can get up to speed in no time.

Regarding the API, I also think there are too many config parameters. Also, some parameters are configured in `mqtt.Client()` and some when you call `client:connect()`. I'd rather have only `client:connect(parameter_table)` (@devsaurus's 3rd option above); this is what maps the best to the underlying `esp_mqtt` library and saves memory (we don't have to remember config parameters submitted to `mqtt.Client()` until we actually connect).

I can refactor this very quickly to whatever we agree on. My only requirement is that any API change is backported to ESP8266 as well. Being able to share lua code among these two platforms is what makes NodeMCU a great choice for IoT projects.

**Comment by devsaurus** [comment]
> My only requirement is that any API change is backported to ESP8266 as well

An important aspect, especially when considering backward compatibility with existing Lua code.
With this in mind, the `client:connect(parameter_table)` would be an alternative to the existing variant with positional parameters. Both variants would need to be maintained in parallel, I'm afraid.

> Any other ideas?

Can we simplify bus also extend the existing API?
- `autoreconnect` is on the [path to deprecation](https://github.com/nodemcu/nodemcu-firmware/blob/11592951b90707cdcb6d751876170bf4da82850d/app/modules/mqtt.c#L1333)
- overload the current `secure` parameter with a table for certificate handling
    0 or nil: plain connection
    1: secure connection, no certs
    table: secure connection, certificates according table entries

**Comment by jpeletier** [comment]
@devsaurus I like the overload `secure` parameter idea to simplify things.
@kevinresol what do you think?. Would you take a stab at this? This change would need two PRs: ESP32 and ESP8266 so we maintain the implementations in sync.

**Comment by kevinresol** [comment]
@jpeletier thanks for your efforts! I could help testing the stuff. But I think I just don't have enough lua/c knowledge to implement anything more complex than this PR. Especially the memory management part.

I agree overloading the `secure` parameter is a good start if changing the API completely to a table-based one is too much work (involve backporting)

**Comment by devsaurus** [comment]
Kevin, I'd like to get this enhancement into the code base.
I could set up a new PR based on your code and the changes to the API according to above conclusion. I can't test it without an mqtt setup including certificates, so it would be helpful if you could test the PR before merge.

Are you ok with such an approach?

**Comment by kevinresol** [comment]
Yes I can help testing it.

Btw, I am using AWS IoT. It has some free quotas for a newly registered account for one year. If you wish to know how to set up one. Let me know.

**Comment by devsaurus** [comment]
Ok, great. I'll see how far I get.

**Comment by devsaurus** [comment]
Code was re-used in #2657 and merged to `dev-esp32`.
Thanks again, @kevinresol!

**Pull request closed without merging**
