### PR TITLE
Fix pipe unread (#3155)

### LINKED ISSUE #3155: Pipe Object Unread String Length Limitation
### Expected behavior
It is expected that the `pobj:unread(s)` method not be limited by the length of the string to be unread.
### Actual behavior
The  `pobj:unread(s)` method works up to string length of 256 characters. With string lengths longer than 257 characters, the following error is returned: `bad argument #-2 to 'read' (userdata expected, got no value)`. With very long strings, a panic and restart result.

A workaround in not to use  `pobj:unread(s)` but `pobj:write(s)` after a read.
### Test code
The `string` `'ttttttt.....ttttt'` has been shortened in the code sample for readability purposes.
```Lua
  pobj = pipe.create()
  pobj:write('tttttttt.......tttttttttt')

  data1=pobj:read()
  print(data1)

  data2=pobj:read()  
  if data2==nil then print("pobj empty after read") end  
  
  pobj:unread(data1)
  data3=pobj:read()
  print(data3)
```
### NodeMCU startup banner
```
NodeMCU 3.0.0.0 built with Docker provided by frightanic.com
	branch: dev
	commit: 50fcd72a5822b628708e4bd1c8f6ba04815289f3
	release: 2.0.0-master_20170202 +515
	release DTS: 202005151145
	SSL: true
	build type: float
	LFS: 0x30000 bytes total capacity
	modules: adxl345,bit,cron,crypto,encoder,file,gpio,http,i2c,net,node,ow,pipe,rtcmem,rtctime,sjson,sntp,softuart,struct,tls,tmr,uart,wifi
 build 2020-06-02 06:48 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
```
### Hardware
Standard ESP12F

### PR DESCRIPTION
**Pull request by nwf**
Fixes #3155.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.

### CODE REVIEW

**Comment by TerryE** [comment]
Nathaniel, I will take a look at this and get back to you :smile:

**Comment by marcelstoer** [comment]
> I will take a look at this and get back to you

If you leave the grammar fixes aside it's only three changed lines between 343 and 350 😉 👍 https://github.com/nodemcu/nodemcu-firmware/pull/3295/files#diff-48b84fd7a815bf800a334473a46b8299bc11531cbf5ac120fcf3d14720552204R343-R350

**Comment by nwf** [comment]
Ping @TerryE.  This is, I think, sufficiently well tested locally that I'd like to land it.  Perhaps @NicolSpies could test it?

**Comment by nwf** [comment]
Sorry to time out on you, @TerryE, but based on local testing I think this at least doesn't make anything *worse*.  We can always follow-up with later fixes if necessary.

**Pull request merged**
