### PR TITLE
MPR121 I2C Module

### PR DESCRIPTION
**Pull request by tcustodio**
Module and example for touch sensing IC MPR121

### CODE REVIEW

**Comment by MarsTechHAN** [comment]
If you are asking for a module...It will be a bad idea to create a issue.
Close it and post on esp8266.com will be a better one.

**Comment by marcelstoer** [comment]
> If you are asking for a module

Uuuhhm, a misunderstanding? He/she is _providing_ a module, it's a PR.

**Comment by tcustodio** [comment]
Hi, sorry if I did anything wrong. I'm new to git. I've provided a working module and example to use MPR121 through I2C. Hope it can be useful to anyone.

**Comment by MarsTechHAN** [comment]
Sorryyyyyyy......  :(
That's my fault... The program on my phone show something wrong information....Thanks for your PR, dong forget upload wiki :)

**Comment by marcelstoer** [comment]
> dong forget upload wiki

If you mean the user should update the wiki once the PR is merged...there's no wiki for Lua modules, is there?

**Comment by tcustodio** [comment]
The files are pretty well commented and it shouldn't be hard to understand how it works.

**Comment by MarsTechHAN** [comment]
@tcuatodio
😓All fault is about me......
My mind have some trouble inside...Dont care...

**Pull request merged**
