### PR TITLE
add 64m and 128m flash support

### PR DESCRIPTION
**Pull request by moononournation**
Add 64m and 128m flash support, please find further details at my instructables:
http://www.instructables.com/id/ESP-03-Upgrade-Flash-Memory-to-128-M-Bit/

- [x] This PR is compliant with the [contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

Committers supporting this PR:

### CODE REVIEW

**Comment by moononournation** [comment]
add 64m and 128m flash support, please find further details at my instructables:
http://www.instructables.com/id/ESP-03-Upgrade-Flash-Memory-to-128-M-Bit/

**Comment by marcelstoer** [comment]
Is upgrading the `esptool.py` to a current version necessary to make this work? Note that we actually want to get rid of our copy anyway, see #595 for details.

Other than that... 👍 Sure, why not support larger flash chips - except that next time someone wants to solder a 256Mbit chip to his module we need to change it again 😉

**Comment by moononournation** [comment]
Hi, update estool.py is not really necessary. But I found some out-sync
with the main code, e.g. not yet handle 16m-c1, 32m-c1 and 32m-c2.
According to ESP8266EX datasheet, it support maximum 128 Mbit flash, so I
think it does not require 256 Mbit code.

Leung

Marcel Stör <notifications@github.com> 於 2016年6月20日星期一 寫道：

**Comment by marcelstoer** [comment]
> According to ESP8266EX datasheet, it support maximum 128 Mbit flash

Sorry, I had missed that.

**Pull request merged**
