### PR TITLE
Fix nodemcu.ld

### PR DESCRIPTION
**Pull request by TerryE**
Fixes https://github.com/nodemcu/nodemcu-firmware/issues/2760#issuecomment-493900177

### CODE REVIEW

**Comment by NicolSpies** [comment]
@TerryE , I retract may statement about the SDK 3.0 stability when compared to SDK 2.2.1.

I have repeated the test done before the latest build with excellent results. No wdt resets. Over the re-test period of more than a hour the 100% failure rate changed to 100% pass rate.

What about applying the change of today to the build of Friday afternoon, I am keen to repeat my testing of the weekend on Friday's build.

**Comment by TerryE** [comment]
> What about applying the change of today to the build of Friday afternoon

I am not sure what you mean here d6980ad and a62db23 are minor tweaks to get SDK 3.0 working.  Have a look; there aren't any other functional differences.

**Comment by NicolSpies** [comment]
I was referring to `f1b5dfc` of Friday afternoon and `a62db23` of today but I see today's build includes the SDK-3.0 tranche updates of Friday, sorry.

**Comment by NicolSpies** [comment]
@TerryE , I continued testing against the latest build. I think SDK 3.0 is more prone to `wdt reset` compared to SDK 2.2.1. for TLS operations based as previously mentioned.  It is slowing my development down so I have decided to roll back to the last SDK 2.2.1 commit that I have been using for the last 1 1/2 months. :disappointed:

**Pull request merged**
