### PR TITLE
Next master snap

### PR DESCRIPTION
**Pull request by marcelstoer**
As always the PRs are listed in the milestone: https://github.com/nodemcu/nodemcu-firmware/milestone/9?closed=1

### CODE REVIEW

**Comment by marcelstoer** [comment]
Can we get this out the door please so LFS can land on `dev`?

**Comment by TerryE** [comment]
> Can we get this out the door please so that LFS can land on `dev`?

Sorry Marcel, I am running a few days behind partly because I had a bit of a problem overcoming my Candida infection which flattened me and I've had to totally change my diet to shake off, and partly debugging my LFS version of the FTP server, but I'll post on that separately even though it's nice to boot into a version with telnet, FTP and a bunch of other utitlities loaded and still have 45kb RAM free.

**Comment by marcelstoer** [comment]
👍 No worries, you're not the only one with merge permissions 😉

**Comment by TerryE** [comment]
Unfortunately this is i's dotting and t's crossing before we can merge the LFS version -- mainly integrating Johny's linker-magic static LFS allocator.

**Pull request merged**
