### PR TITLE
Write function in ws2812.buffer module

### PR DESCRIPTION
**Pull request by bogvak**
Fixes #\<GitHub-issue-number\>.

- [x] This PR is compliant with the [contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

This new function allows to write string to ws2812.buffer or copy data from another ws2812.buffer,
String writing could be very useful while creating animation from saved data or from data coming from network.

Copying data from another ws2812.buffer is very useful while creating advanced animated effects, transition from one frame to other etc,

#### Format
`ws2812.buffer:write(data)`
where `data'` is `string` or another `ws2812.buffer`

#### Returns
`nil`

Committers supporting this PR: leave blank

### CODE REVIEW

**Comment by marcelstoer** [comment]
@Alkorin what do you think of this?

**Comment by Alkorin** [comment]
Hum, isn't it the same as buf:set(0, data) ? Where data is a string ?

The new thing is to copy from an existant buffer. But we could implement :set(N, buffer) instead of adding a new function no ?

**Comment by bogvak** [comment]
Really sorry for long reply, sirs. You're definitely right I haven't paid enough attention that it's possible to pass full string to _buf:set_ function and it's better just to extend it to support _buffer_ passing as argument.

Will you commit me to do this?
Thanks!

**Comment by Alkorin** [comment]
Do it and I will review it ;-)

**Comment by marcelstoer** [comment]
> Do it and I will review it ;-)

This would go into a new PR then -> closing this one.

**Pull request closed without merging**
