### PR TITLE
Next master drop

### PR DESCRIPTION
**Pull request by marcelstoer**
@HHHartmann what about #3191?

### CODE REVIEW

**Comment by HHHartmann** [comment]
> @HHHartmann what about #3191?

Will fix it today

**Comment by marcelstoer** [comment]
@nwf @pjsg #3291 appears to have been merged instead of squash-merged. If you wanted to clean-up the commit history now would be the time to do that :)

**Comment by HHHartmann** [comment]
> > @HHHartmann what about #3191?
> 
> Will fix it today

Done. See #3322

**Comment by nwf** [comment]
Eh, I'm OK with the unsquashed merge.

**Comment by marcelstoer** [comment]
Approve & merge now?

**Review by nwf — APPROVED** [review]

**Pull request merged**
