### PR TITLE
Next release drop

### PR DESCRIPTION
**Pull request by marcelstoer**
Long overdue...

https://github.com/nodemcu/nodemcu-firmware/milestone/19?closed=1

### CODE REVIEW

**Comment by nwf** [comment]
Long overdue, no objections heard (and none from here)... here goes!

**Comment by marcelstoer** [comment]
Thanks! A question if I may, how did you manage to merge this one? You're listed as committer of all these changes and release/dev now diverged?
***
Screen Shot 2021-12-30 at 08 50 24

***

Screen Shot 2021-12-30 at 08 50 53

**Comment by nwf** [comment]
&#*^(&$@$.  I just hit the rebase-and-merge button.  Dammit, GitHub.  I'm going to commit some violence (force push) to move `release` to 0b9785585e41003d29a3971758286b5a9d0df688 instead of its current location.  I don't imagine this will actually cause problems because we probably haven't had many checkouts in the past 18 hours.  I'm sorry I didn't notice sooner.

**Comment by marcelstoer** [comment]
Thanks. I now also merged my MkDocs bump into `release` so that the dependabot warning would go away.

**Comment by marcelstoer** [comment]
Oh and thanks for the release notes! I deleted the draft release (pointing to the same tag) that @HHHartmann's [nice workflow](https://github.com/nodemcu/nodemcu-firmware/blob/release/.github/workflows/AutoCreateRelease.yml#L34) created automatically. Not sure if you didn't see it or had different reasons for creating a separate one.

**Comment by marcelstoer** [comment]
> Not sure if you didn't see it or

Maybe because [our guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/release/CONTRIBUTING.md#handling-releases) don't know about the auto-release yet 😄

**Comment by nwf** [comment]
Oh, I didn't see it. :(

**Comment by HHHartmann** [comment]
Too bad, that also removed the windows luac.cross binary which was attached to it.

**Comment by nwf** [comment]
Well nuts.  Can it be rescued?

**Comment by marcelstoer** [comment]
> that also removed the windows luac.cross binary which was attached to it

Sorry about that. Looks like _I_ am also not up-to-date wrt our release process anymore.

> Can it be rescued?

Yep

- I re-ran the release pipeline from https://github.com/nodemcu/nodemcu-firmware/actions/runs/1638510368 ("Re-run all jobs" to right)
- It re-created that draft release
- I downloaded the luac.cross asset from it
- Then uploaded it to the real release
- And deleted the draft again

**Comment by HHHartmann** [comment]
That's wonderful. As far as I can see the one from the last release would have worked too but it's much better this way

**Pull request merged**
