### PR TITLE
Correct integer types in BMP085 driver

### PR DESCRIPTION
**Pull request by andrmuel**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [~] I have thoroughly tested my contribution.
⇒ I only tested it on master; current dev fails for me
- [n/a] The code changes are reflected in the documentation at `docs/*`.

\<Description of and rationale behind this PR\>

### CODE REVIEW

**Comment by nwf** [comment]
These seem sensible enough to me, but I do not have one of these devices to test.  Any of the active maintainers have one?

@andrmuel Can you elaborate on why `dev` isn't working for you?

**Comment by andrmuel** [comment]
I was able to build the firmware on dev and flash it, but afterwards I was not able to flash any Lua code for testing.

In regards to testing with the BMP085: if you want to reproduce the original problem as well, that might be possible with heating it up to 30-40 deg C.

**Comment by HHHartmann** [comment]
That's probably due to bug #2963. It is fixed in #2912.
It was IIRC introduced with #2836. So you could rebase your branch to a commit before that and retry.

**Comment by andrmuel** [comment]
I'm not sure I understand correctly. The commit you are referring to is 14c1b8fd542beabba68646dab93f4862b364a4b3 (from Sep. 2019)? The commit before that would be c7ff86ff275c01497271b1f2542d6e750cc87ca6, and that is already part of master. It does work on the current master. What would be the benefit of testing it with an _older_ version of master (which contains less of dev)?

**Comment by HHHartmann** [comment]
The changes in this PR are very local, so that I would not expect any of the changes in dev to influence the outcome of the test. 
But I think there was another upload to mentioned somewhere which still works on current dev. 
Another alternative would be to flash the entire SPIFFS partition containing all the files you need.

**Comment by nwf** [comment]
Given the highly localized nature of this change, as @HHHartmann says, I've just merged it to `dev`.

**Pull request merged**
