### PR TITLE
NFC: Backport luaL_testudata to Lua 5.1

### PR DESCRIPTION
**Pull request by nwf**
And move luaL_checkudata to it, as in 5.3.

### CODE REVIEW

**Comment by HHHartmann** [comment]
Unfortunately `typeerror` also does not seem to be part of Lua 5.1

**Comment by nwf** [comment]
OK.  Having stopped to actually read C, it looks like this is now CI green.  Opinions?

**Comment by nwf** [comment]
Any objections to landing this?  It should be fairly devoid of consequence...

**Comment by HHHartmann** [comment]
LGTM

**Pull request merged**
