### PR TITLE
Documentation Change - Memory leak

### LINKED ISSUE #1303: Memory leak in socket:on("sent")?
Do we have a memory leak in `socket:on("sent")` or do I, again, miss something obvious?

Here's my simple test bed of a server that just returns `text/plain`:

```lua
srv=net.createServer(net.TCP)
print("Server created...")
print("Available heap: "..node.heap())
srv:listen(80,function(conn)
    conn:on("receive", function(c,request)
        c:on("sent", function() 
            print("Available heap: "..node.heap())   
            c:close()
        end)
        c:send("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nLED STATE=1\r\n")
    end)
end)
```

Much to my surprise available heap keeps decreasing and never recovers:
> Server created...
Available heap: 42352
Available heap: 43200
Available heap: 43392
Available heap: 42904
Available heap: 42616
Available heap: 42136
Available heap: 41776
Available heap: 41752
Available heap: 41464
Available heap: 41600
Available heap: 41224
Available heap: 41240
Available heap: 40872
Available heap: 40888
Available heap: 40520
Available heap: 40504
Available heap: 40160
Available heap: 39936
Available heap: 39536

To test what impact `socket:on("sent")` has I replaced it with an ugly `tmr.delay()`:
```lua
srv=net.createServer(net.TCP)
print("Server created...")
print("Available heap: "..node.heap())
srv:listen(80,function(conn)
    conn:on("receive", function(c,request)
        c:send("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nLED STATE=1\r\n")
        tmr.delay(50)
        print("Available heap: "..node.heap())
        c:close()
    end)
end)
```
Memory consumption seems to be a lot more stable this way:
> Server created...
Available heap: 42552
Available heap: 42376
Available heap: 42168
Available heap: 41984
Available heap: 41760
Available heap: 41592
Available heap: 41400
Available heap: 41600
Available heap: 41400
Available heap: 41600
Available heap: 40816
Available heap: 41128
Available heap: 40816
Available heap: 41136
Available heap: 40816
Available heap: 41128
Available heap: 41408
Available heap: 41608
Available heap: 41768
Available heap: 41784
Available heap: 41000
Available heap: 40944
Available heap: 41008
Available heap: 40944
Available heap: 41000
Available heap: 40944
Available heap: 41000
Available heap: 40944
Available heap: 41592

Then I also tested with using the sent callback directly in `send(string[, function(sent)])` but the behavior was the same as in the first example.

### PR DESCRIPTION
**Pull request by tinohager**
Fixes #1303.

- [x] This PR is compliant with the [contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `https://nodemcu.readthedocs.io/en/master/en/modules/net/#netsocketsend`.

The documentation have changed. See #1303

### CODE REVIEW

**Comment by tinohager** [comment]
The example in README.md uses different variable names, ok. But is there a leak due to this?

Yes there is a leak. Without different variable every request the heap shrinking

**Comment by marcelstoer** [comment]
Thanks, good catch!. That example from the original maintainer(s) is even on https://en.wikipedia.org/wiki/NodeMCU and nodemcu.com 😦 We'll fix one after the other.

**Comment by devsaurus** [comment]
Can somebody please provide any background or references why the original code would leak? From my (C-centric) perspective the callback function is self-contained, but maybe I'm missing something.

**Comment by marcelstoer** [comment]
Terry provided the explanation in [#1303](https://github.com/nodemcu/nodemcu-firmware/issues/1303#issuecomment-220780603).

**Pull request merged**
