### PR TITLE
Espressif SDK v2.2.1

### PR DESCRIPTION
**Pull request by nwf**
Minimally build and boot tested, but the changes look pretty boring.
Fixes https://github.com/nodemcu/nodemcu-firmware/issues/2395

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).

### CODE REVIEW

**Comment by devsaurus** [comment]
Looks good.

Espressif missed to update `ESP_SDK_VERSION_PATCH` to `1` in https://github.com/espressif/ESP8266_NONOS_SDK/blob/v2.2.1/include/version.h.
The firmware still reports
```
NodeMCU 2.2.0.0 build unspecified powered by Lua 5.1.4 on SDK 2.2.1(6ab97e9)
```

**Comment by nwf** [comment]
Bah humbug re: Espressif.  We could leave it be or change `user_version.h` either to replace

    #define NODE_VERSION_REVISION	ESP_SDK_VERSION_PATCH

with

    #define NODE_VERSION_REVISION	1

or just bump `NODE_VERSION_INTERNAL` instead?  I think I'd be more in favor of the last or the first, but this might just be bikeshedding.

**Comment by marcelstoer** [comment]
> We could leave it [...]

In light of the discussions in #2398 I don't think we should.

**Comment by nwf** [comment]
@marcelstoer How do you feel about calling this 2.2.0.1 while we wait on Espressif?

**Comment by marcelstoer** [comment]
@nwf I wouldn't do that. If Espressif fixes this we'd be shipping essentially the same SDK as before and, therefore, an change from 2.2.0.1 to 2.2.1.0 would feel odd to me.

**Comment by jmd13391** [comment]
Why don't we simply wait on SDK 2.2.1 until Espressif releases a fix?
Does anyone know if Espressif is aware of the issue?

**Comment by marcelstoer** [comment]
SDK is already released, that's what this PR is about. See my comment further up.

**Comment by nwf** [comment]
@marcelstoer Admittedly, I was imagining we'd wait until 2.2.2 or 2.3.0 or 3.0.0 or whatever to re-merge with upstream, so we'd not do a 2.2.0.1 to 2.2.1.0 transition.  I'm content to wait a bit to see what Espressif does.

**Comment by marcelstoer** [comment]
> I'm content to wait a bit to see what Espressif does.

They haven't even commented on my PR in a month...

**Pull request merged**
