### PR TITLE
Remove binaries from repository

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Replaced by [CI builds](https://github.com/nodemcu/nodemcu-firmware/releases)

### CODE REVIEW

**Comment by nodemcu** [comment]
the pre_build/latest/nodemcu_latest.bin is the firmware lately build,
as asked by many people, because they have a ref link to it.
any way to preserve a hard link with a "static" name in CI builds system?
all can we re-direct link pre_build/latest/nodemcu_latest.bin to some where else?

**Comment by GeorgeHahn** [comment]
Linking to https://github.com/nodemcu/nodemcu-firmware/releases/latest will always give the latest release as built by the CI, is that what you want?

**Comment by nodemcu** [comment]
actually they are using this link:
https://github.com/nodemcu/nodemcu-firmware/blob/master/pre_build/latest/nodemcu_latest.bin
can this link be re-directed? say click on this and re-direct to https://github.com/nodemcu/nodemcu-firmware/releases/latest

**Comment by GeorgeHahn** [comment]
Ahh, gotcha. I'm not aware of any way to do that. This PR would just break that link and give 404 errors to anyone who tried it.

**Comment by nodemcu** [comment]
the binary will be there for some days, until most of us get used to the new download location.
thank you any way.

**Pull request closed without merging**
