### PR TITLE
tmr.delay latency decrease

### PR DESCRIPTION
**Pull request by klukonin**
I'm adding watchdog clear to avoid sustem reboot.

Looks like it should work correct now.

### CODE REVIEW

**Comment by nodemcu** [comment]
if the delay us > 3000000, about 2~3 seconds.
the watch dog will fire and reset the chip.
please verify.

**Comment by klukonin** [comment]
Confirmed.

As I think, it will lbe better to add some instructions to the API page, rather than add a check to the delay function. So If someone need to make a delay about 1-3 seconds, let it be 1000 us delay, but 1000-3000 times. Unusual scenario. IMHO.

Second way is to devide tmr.delay into tmr.delay.s, tmr.delay.ms, and tmr.delay.us for second, milisecond and microsecond values. How do you think?

**Comment by klukonin** [comment]
Sorry, I'll add future commits to the dev branch.

**Comment by klukonin** [comment]
https://github.com/nodemcu/nodemcu-firmware/pull/346

**Pull request closed without merging**
