### PR TITLE
Try to make qos~=0 work better

### PR DESCRIPTION
**Pull request by pjsg**
There are two things in the PR

* Make sure that we send the next message in the queue whenever possible. This *should* fix all the delays. I can send multiple messages per second with non zero QOS now with no obvious delays (and no queue buildup). 

* Make sure that we don't save the lua_State pointer and use it later. This fails in all sorts of horrible ways in the presence of coroutines.

As a benefit, this actually reduces the number of lines of code.....

### CODE REVIEW

**Comment by pjsg** [comment]
I've added a fix for Issue #986 as well.

**Comment by TerryE** [comment]
Philip, I know nothing of this library.  Maybe Johny or Arnim, or one of the other MQTT contributors could look this over and comment then I'll commit it. @jmattsson @devsaurus @karrots?

**Comment by devsaurus** [comment]
I'll check for regressions here.

**Comment by devsaurus** [comment]
I can confirm that #986 is fixed.

On the downside it appears that my simple mqtt-driven application is broken by the PR. A sensor publishes messages every 5 minutes which are supposed to be picked up by the ESP. This doesn't work anymore as the mqt subscription won't fire the callback for all but the first message (a retained one).

I've isolated a simple testcase where the sensor is modelled by this csh script:
```csh
#!/bin/csh

set i = 0
while ( 1 )
        echo $i
        mosquitto_pub -i sensor -h server_ip -q 2 -r -t test_pr -m 0.0:0.0:$i.$i
        @ i = ( $i + 1 )
        sleep 5m
end
```

On the ESP side:
```lua
m = mqtt.Client("esp8266", 120, "", "")

m:on("message", function(conn, topic, data) 
    if data ~= nil then
        local arr = {}
        local i = 1
        data:gsub("[^:]+", function (a) arr[i]=a i=i+1 end)

        print(arr[1]..", "..arr[2]..", "..arr[3])
    end
end)

m:connect(server_ip, 1883, 0, 0, function(conn)
        print("connected, subscribing...")
        m:subscribe("test_pr", 2, nil)
end)
```

It works with the code on current `dev` branch.

**Comment by pjsg** [comment]
I'll take a look at this in the morning....

**Comment by pjsg** [comment]
I've fixed this. The bug turned out to be that it didn't send the PING on the two minute timeout and then it disconnected the session after a number of failed pings. The bug was an extra line of code that I had failed to remove. 

I will squash the commits once you are happy with it.

Sorry about that.

**Comment by TerryE** [comment]
> I will squash the commits once you are happy with it.

Be a rebel -- don't bother :wink:

**Comment by devsaurus** [comment]
Works fine now, thanks a lot! Green light from my side :+1:

**Pull request merged**
