### PR TITLE
Upgrade to SDK version 1.5.1 from Espressif

### PR DESCRIPTION
**Pull request by pjsg**
This PR just replaces the SDK .zip with the newest version from Espressif. It also updates the version numbers in various places.

This solves issue #901.

Verified by running previously failing code for 12 hours without failure. Previously would crash within 2 hours.

Only non-obvious change is to alter the '.extracted' file to mark which version of the SDK was extracted. This allows upgrading the SDK.

### CODE REVIEW

**Comment by jmattsson** [comment]
Nice, thanks for all the testing with #901!

You missed changing `NODE_VERSION_REVISION` to a 1 in user_version.h here though ;)

@TerryE @marcelstoer Seeing as #901 seems a bit more important than the timer issue in #907, I'd say we should probably just close the #917 PR. The remaining question then is whether we keep piling in zip files, or switch to downloading & caching them.

**Comment by TerryE** [comment]
My +1 is to download and cache them. Also +1 on #901 as there is a simple workaround for #907 and this code is going to be needed in the general case anyway

**Comment by jmattsson** [comment]
Alright, @pjsg would you mind updating this PR to do the download like #917? Just ignore the binpatch/libmain* parts in the makefile. Or throw it over the fence to me and I'll look at it tomorrow, that's fine too. Thanks!

**Comment by pjsg** [comment]
This now does the download. *HOWEVER* this means that when you run this for the first time with a new SDK, you need network access. This means that it does not work if you are running one of the standard docker images -- which appear to have been setup without network access. You can just run 'make' outside the docker image, and then you have to do the rest of the build inside. I'm not sure what the right approach is here.

I did change the size check to use wc rather than parse the output of ls -- this is more portable.

**Comment by TerryE** [comment]
> Wouldn't a MD5 or SHA1 verification be more reliable at detecting errors in the download vs a size check?

Yes MD5 or SHA1 is sufficient, but the failure mode that we are trying to detect is a TCP link failure.  All that is necessary in this instance is a length check; neither MD5 nor SHA1 is necessary.

If we want end-to-end link integrity then we should just switch _all_ of our http connections to https, or use a MD5 / SHA1 signature on all http transferred data. IMO, there's little point in assuring just one file.

**Comment by TerryE** [comment]
> This that it does not work if you are running one of the standard docker images -- which appear to have been setup without network access.

Hummmnn, perhaps you should swap from docker to a standard Ubuntu LTS 12.04-5 minimal server image as I describe in this [esp8266 wiki page](http://www.esp8266.com/wiki/doku.php?id=toolchain#how_to_setup_a_vm_to_host_your_toolchain).  I am a VirtualBox man; @marcelstoer is the docker expert, so he will need to comment on this.

**Comment by pjsg** [comment]
I converted to using a sha1 sum -- it makes the tests slightly simpler....

**Comment by TerryE** [comment]
@pjsg  As I said sufficient, but not necessary :smile:  Did you note my cross post on ufw?

**Comment by pjsg** [comment]
Actually, it turns out to be a local configuration problem on my system.... So I am much happier now.

**Comment by marcelstoer** [comment]
> it does not work if you are running one of the standard docker images -- which appear to have been setup without network access.

There's no such thing as a "standard Docker image", they're all different. The image creator decides what features it contains and how they're configured.
[My image for example](https://github.com/marcelstoer/docker-nodemcu-build/blob/master/Dockerfile) extends the [Ubuntu image](https://hub.docker.com/_/ubuntu/) and runs `apt-get` commands. It definitely does have network access - if the underlying OS or VM does.

**Comment by TerryE** [comment]
Hey, Marcel, that's just nitpicking, IMO. you have to use LTS 12.04-5 so the toolchain tarball is compatible with Travis CI.  I agree that you've extended it.  Good on you :)

**Comment by jmattsson** [comment]
Looks good to me, thanks Philip!

**Pull request merged**
