### PR TITLE
First round of mqtt fixes

### PR DESCRIPTION
**Pull request by nwf**
- [x] This PR is for the `dev` branch rather than for the `release` branch.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/*`.

This addresses #2987 and several things enumerated in #3068.  It passes the **extremely limited** testing of `tests/test-mqtt.expect` in my `dev-active` branch, but much, much more testing is in order.

As the subject of #3356 says, there remains something wrong with our mqtt implementation, even with these in place.

### CODE REVIEW

**Comment by nwf** [comment]
Anyone up for testing these or is "works for @nwf" good enough to hit merge? =P

**Comment by marcelstoer** [comment]
I had planned this for today but got "held up" tinkering with [the Cricket](https://www.thingsonedge.com/) - a quite unique module. Like it.
Maybe I'll find some time tomorrow. Otherwise I don't object to you merging it.

**Comment by marcelstoer** [comment]
Happy with my test results so far.

> This addresses #2987 and 

But you didn't remove DNS support for the hostname?!

> several things enumerated in #3068.

Could you tick off the ones fixed with this PR? Either by adding a `[x] ` or a ✅  those bullet items?

**Comment by nwf** [comment]
> Happy with my test results so far.
> 
> > This addresses #2987 and
> 
> But you didn't remove DNS support for the hostname?!

Indeed not, because people objected.  So this leaves `mqtt.c` doing a bit of an awkward dance around the LwIP DNS resolver; it is almost surely still wrong if someone races a `:close()` with DNS resolution, but people seem happier with that possible fatality than the inconvenience of a Lua wrapper, and I am all out of care to argue.

> > several things enumerated in #3068.
> 
> Could you tick off the ones fixed with this PR? Either by adding a `[x] ` or a  those bullet items?

They're marked as "[addressed?]" because I'm not really sure they are addressed.  The whole module is a [censored] mess and I'm really frustrated at the whole thing.  These are my best effort workarounds, that's all.

**Review by marcelstoer — APPROVED** [review]

**Pull request merged**
