### PR TITLE
Add ChiliPeppr as option for IDE

### PR DESCRIPTION
**Pull request by chilipeppr**
ChiliPeppr's web IDE is ready for primetime. I'd love to get this into the docs.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

### CODE REVIEW

**Comment by chilipeppr** [comment]
The rationale for this pull request is that ChiliPeppr's web IDE is a huge step forward for making the Nodemcu firmware for ESP32 relevant and easier to use for the developer community. ChiliPeppr's ability to let people fork the workspace and fork the widgets in it, creates an opportunity for Lua to become the dominant programming language for ESP32 with a bigger developer community than other competing platforms like Micropython, Javascript (Duktape), and the Arduino IDE.

**Comment by marcelstoer** [comment]
@drawkula gave a 👎, care to explain why?

**Comment by chilipeppr** [comment]
To add more color to the plans, I recently posted about a pure Lua
websockets client I wrote in the issues list. One of the next steps for
that is to let you program your esp via websockets instead of just via
serial port at 115kbaud. Chilipeppr would give you the Lua library to
install into init.lua so you can now program via TCP. Serial port Json
server is, at it's core, a websockets server. So this is a natural
progression.

If you watch my video on uploading animated gifs to esp32, it's slow, so
this would help.

It will also help pave the way to remote OTA updates for lua code.

**Comment by chilipeppr** [comment]
Excellent!

**Comment by marcelstoer** [comment]
The ESP32 branch version of this file is a bit behind the baseline. That should be fixed separately though.

- We never established criteria as for when to list a specific tools. It's difficult to be fair to all the tool developers. That's why we keep a disclaimer-like paragraph in the master version.
- If we allow ChiliPeppr to be listed in the ESP32 branch version why not on dev/master?

**Comment by devsaurus** [comment]
> - If we allow ChiliPeppr to be listed in the ESP32 branch version why not on dev/master?

For the reasons you gave in your first point, I'd say: too many to list in the docs.

With ESP32 it's different in my opinion. We have just generic support as a by-product from esp8266-based tools like ESPlorer - fortunately - and I couldn't name any tool or IDE that will work without hiccups on the ESP32. Now ChiliPeppr's ESP32 workspace is the first true IDE targeting the ESP32 Lua up to my knowledge. This, and its good documentation for getting users started from scratch is worth mentioning IMO. Note that I'm not affiliated with ChiliPeppr 😄 I had a first look just recently.

The ESP32 situation might change in the future and I'd be gladly confronted with the same luxury issue like the esp8266 platform (although I doubt this will happen soon).

**Comment by devsaurus** [comment]
I've added a note about the overall fitness of ESP8266 tools for the ESP32-based firmware (bded03540623248ec763440591c920b2072c3d7a).

**Pull request merged**
