### PR TITLE
Added dns submodule, with get/set dns server, new resolve method

### PR DESCRIPTION
**Pull request by jorgempy**
added:
net.dns.setdnsserver('ip',[index])
net.dns.getdnsserver([index]), 
net.dns.resolve('domain.com', function cb('ip' or nil if fail) )
      modified:   app/modules/net.c

### CODE REVIEW

**Comment by vowstar** [comment]
Wonderful PR but could you push it to dev branch? :)

**Comment by jorgempy** [comment]
sure, dev or dev096?

**Comment by vowstar** [comment]
All is OK, dev096 is a short-life version, please PR to dev and we will merge it. Thanks :)

**Comment by jorgempy** [comment]
done, pr #424 now the multicast join and leave that are in the master branch are missing though

**Comment by vowstar** [comment]
Ok, the dev branch will replace master branch after full testing

**Comment by jorgempy** [comment]
there's test code in #189 to test if you do it by hand. cheers.

**Comment by vowstar** [comment]
Thanks very much, cheers.

**Comment by dnc40085** [comment]
@jorgempy Since your other pull request #424 was merged could you close this one

**Pull request closed without merging**
