### PR TITLE
add tm1829 module to dev branch

### PR DESCRIPTION
**Pull request by h3ndrik**
This code is taken from the WS2812 module with modified timings and inverted logic levels

see #920: this is a resubmission after the module cleanup
also add some API description  (#774)

### CODE REVIEW

**Comment by marcelstoer** [comment]
Thanks a lot! I'd like to see two additional things:
- add your doc file at the right position (alphabetical) to https://github.com/h3ndrik/nodemcu-firmware/blob/dev/mkdocs.yml
- squash all your commits into one as per https://github.com/nodemcu/nodemcu-firmware/blob/master/CONTRIBUTING.md#general-flow

@devsaurus in https://github.com/nodemcu/nodemcu-firmware/issues/920#issuecomment-170825882 you mentioned some verification you wanted to perform?

**Comment by TerryE** [comment]
Can I give this a :-1:  or at least a hold.  We shouldn't be adding more modules which break the Espressif timing guidelines and cause the CPU to crater, until we agree a policy for addressing these issues.  In this case interrupts are disabled for ~40N µSec where N is the number of LEDs.

**Comment by devsaurus** [comment]
> @devsaurus in #920 (comment) you mentioned some verification you wanted to perform?

Not me. In general verification that the code in `old-master` SDK 0.9.6 is functional with a recent SDK. That's been the reason why the code wasn't pulled into `dev` as is.
Can be considered as done, now that @h3ndrik rebased the code onto `dev`.

**Comment by Alkorin** [comment]
Copy-and-paste programming, fonctions comments were wrong in ws2812 module, and ... same here :/

It looks like a similar protocol than ws2812, we could try to share code / use similar implementation.
I don't have any TM1829 here to test :/

**Comment by TerryE** [comment]
The main difference is that the logic is inverted that is each data bit is a low-high rather than high-low, so  whilst your encoding scheme can easily be mapped onto the 1xxxxxxxx0 bit sequences output by the uart, this will need to be shifted one sub-bit for the TM1289. We could get this to work, I think, but test HW and an oscilloscope will be needed.

**Comment by marcelstoer** [comment]
@h3ndrik do you intend to fix the code based on the the comments here? If not then please close he PR.

**Comment by marcelstoer** [comment]
No feedback in more than two weeks -> closing.

**Pull request closed without merging**
