### PR TITLE
Update user_config.h

### PR DESCRIPTION
**Pull request by 286920650**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [ ] This PR is for the `dev` branch rather than for the `release` branch.
- [ ] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/*`.

\<Description of and rationale behind this PR\>

### CODE REVIEW

**Comment by nwf** [comment]
Desk reject; template not filled out, no rationale.

**Comment by HHHartmann** [comment]
@286920650 you may however open an issue about the found build failure

**Comment by marcelstoer** [comment]
> you may however open an issue

Except that the setting is consistent with [the documentation](https://nodemcu.readthedocs.io/en/latest/modules/wifi/#wifistartsmart) and it's there for a reason I guess.

**Comment by HHHartmann** [comment]
> > you may however open an issue
> 
> Except that the setting is consistent with [the documentation](https://nodemcu.readthedocs.io/en/latest/modules/wifi/#wifistartsmart) and it's there for a reason I guess.

I can't follow you. What are you trying to say? It should be buildable, so its an error.

**Comment by marcelstoer** [comment]
Hhhmm, I don't see any indication of a build error here. What did I miss? The PR changes WiFi Smart from "default off" to "default on" which I object to. The stock firmware compiles fine with "default off" (all the cloud builds would otherwise fail).

**Comment by HHHartmann** [comment]
reopend to show test results again. The lua51 and lua53 64 bit build fail 

OK they don't fail anymore. Seems to have been a transient error.
See https://github.com/nodemcu/nodemcu-firmware/runs/1689068890 and
https://github.com/nodemcu/nodemcu-firmware/runs/1689068952

**Pull request closed without merging**
