### PR TITLE
Pwm2

### LINKED ISSUE #2667: new pwm module (pwm2)
### Justification
I guess there is no need to justify why 1kHZ limit of current SDK provided PWM is not good enough.

Lately I've played with https://github.com/StefanBruens/ESP8266_new_pwm. 
Its theoretical limit is 5MHz but I don't have equipment to confirm it. 
With my (cheap) oscilloscope I can observe up to 50kHz and it seems correct. 
Playing in smaller 1-5kHz range I haven't seen any duty cycle side effects either.
It would be great if someone can test it with better hw thought.
And I haven't tested with many pins, but that probably is only matter of time ;)

Stefan's library is for Arduino. I've adopted it as "pwm2" module for nodemcu.
https://github.com/fikin/nodemcu-firmware/tree/pwm2

The implementation is based around a driver, a header and lua bindings. Documentation has an example how that is programmed from lua pov.

Feedback is welcome! 

### Workarounds
Are there any? ;)

### PR DESCRIPTION
**Pull request by fikin**
Fixes #2667.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/en/*`.

Lets review the code and think of changes if needed.

### CODE REVIEW

**Comment by pjsg** [comment]
Can you restage this to the dev branch please?

**Comment by galjonsfigur** [comment]
The only problem I can see is that `ESP8266_new_pwm` project is GPL licensed and `nodemcu-firmware` is MIT. I don't know much about licenses but this could be a potential problem. Other than that this PR is very good idea - better PWM can be used to make more advanced things.

**Comment by fikin** [comment]
huh, that would certainly become a bother.
i ignored it until now but looking at some previous discussions for license change (https://github.com/StefanBruens/ESP8266_new_pwm/issues/16), feel kind of not very optimistic...
is rewrite the only way out of this?

**Comment by marcelstoer** [comment]
> `ESP8266_new_pwm` project is GPL licensed

Yep, that's a no-go :(

**Comment by nwf** [comment]
IANAL, IANYL, TINLA, &c, but: because `nodemcu` is licensed MIT, it can always be mixed in to GPL code, and the result shared under the GPL (just as it can be used as part of proprietary products).  There is nothing stopping a developer or end-user from mixing `ESP8266_new_pwm` and `nodemcu`, as this PR does, but the result will be that the whole thing is GPL and must be distributed as such.

None of this is meant to say that we should merge this PR -- indeed, I think the project will only accept such a module if it can also be MIT licensed -- merely to say that if the lack of interesting PWM support is a problem for down-stream users right now, they are free to do the integration themselves and take on the different licensing regime.

**Comment by fikin** [comment]
i'll re-write it under mit license so that it can make it to the master. would that be ok with you guys?

**Comment by nwf** [comment]
Be careful when rewriting that you do not implicitly create a derivative work; just typing in new code with the old code on screen is probably not legally sufficient.  I think past efforts on these lines have involved two people, one of whom documented the old thing's behavior as pertained to the wider system, and the other looked only at that documentation to produce the new software.  Again, though, I am not an IP lawyer.

**Comment by fikin** [comment]
fair enough. i've seen the code but i't rather do it my own way.
btw, just to confirm, is using hw_timer1 for pwm purposes ok from nodemcu pov?

**Pull request closed without merging**
